### PR TITLE
Start of CODE_OWNERS.md documentation

### PR DESCRIPTION
**Pull request by teqdruid**
Please modify the code-owners branch to fill in the '?'s

### CODE REVIEW

**Comment by stephenneuendorffer** [comment]
@hanchenye I think you should take ownership of the handshake dialect if you're interested.

**Comment by hanchenye** [comment]
@stephenneuendorffer Sure, I'll take ownership of the StaticLogic dialect. Do you think I should also take over the handshake dialect, or you actually mean StaticLogic?

**Comment by lattner** [comment]
Code owners should be humans, not organizations.  I'll be the owner for SV/RTL/FIRRTL until someone else is ready to take them over for me.

**Comment by lattner** [comment]
Also, I'd recommend referring to the LLVM Code owners policy:
https://llvm.org/docs/DeveloperPolicy.html#code-owners

Would it make sense to use the same formatting/header as llvm/CODE_OWNERS.txt. ?

**Comment by teqdruid** [comment]
Yeah, this is just a draft of suggestions. Wasn't going to complete it without signoff from each owner.

As for format: are there any tools which consume that format? If not, I prefer the table but not strongly. Also, I can't find the CODE_OWNERS.txt for MLIR. Am I just dense?

**Comment by stephenneuendorffer** [comment]
@hanchenye I think you should own the Handshake dialect too :)

**Comment by stephenneuendorffer** [comment]
@hanchenye If you don't want to, then I'm happy to do it.

**Comment by teqdruid** [comment]
@fabianschuiki I've got you down as the owner for LLHD. Do you want to take this on? Should I add an additional person?

**Comment by hanchenye** [comment]
@stephenneuendorffer I'll be more than happy to do this! Maybe it would be better to add both you and I to this dialect.

**Comment by fabianschuiki** [comment]
> As for format: are there any tools which consume that format? If not, I prefer the table but not strongly.

GitHub can read it and auto-add reviewers if you stick to their format: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners

**Comment by fabianschuiki** [comment]
> @fabianschuiki I've got you down as the owner for LLHD. Do you want to take this on? Should I add an additional person?

@teqdruid Yeah that's great, thanks!

**Comment by teqdruid** [comment]
The GH CODEOWNERS documentation specifies that whomever enables that feature needs to be an admin. I'm hoping GH will use it for recommendations as I'd rather not have it enforced by the system.

**Pull request merged**
