### PR TITLE
[MooreToCore] Add conversion support for module and instance.

### PR DESCRIPTION
**Pull request by cepheus69**
Due to the features of converting variableOp / netOp to coreIR have not been pushed yet. After those two features, more tests about converting SVModuleOp and InstanceOp will be added. This is an initial edition to support critical Moore IR transformation to core IR, if you have any advice please let me know.

### CODE REVIEW

**Comment by cepheus69** [comment]
The implementation of this PR has been moved from the original development branch to: https://github.com/fabianschuiki/circt/pull/31/files
Thanks to @fabianschuiki 😉 The new SVModuleOp and instanceOp give me more flexibility to create relevant conversion paths more easily. As they share many similarities with moduleOp & instanceOp in the HW dialect. Parameter and Attribute support will be much easier to follow.

**Review by fabianschuiki — COMMENTED** [review]
This looks nice! Can you add a few tests to check that `in` and `out` ports on `moore.module` and `moore.instance` get lowered properly to the HW ops?

**Comment by cepheus69** [comment]
> This looks nice! Can you add a few tests to check that `in` and `out` ports on `moore.module` and `moore.instance` get lowered properly to the HW ops?
Sure. These tests will be added soon. But it might be too simple for test cases because of lacking support of converting assignOp, variableOp and netOp.

**Review by fabianschuiki — APPROVED** [review]
Very cool! Thanks for adding the tests :partying_face:

**Comment by cepheus69** [comment]
> Very cool! Thanks for adding the tests 🥳

Thanks for you review! :smile_cat:

**Pull request merged**
