### PR TITLE
[PyCDE] Refactor global _Types module and support aliases.

### PR DESCRIPTION
**Pull request by mikeurbach**
The _Types is now just a regular instance with instance methods. These
methods now take a possible alias to apply to the requested type. The
aliases are stored and checked to ensure the same alias isn't handed
out to different types.

### CODE REVIEW

**Comment by mikeurbach** [comment]
@teqdruid starting to support these in pycde. The last step is going to be going through the registered aliases in the global _Types instance, and declare them. I was thinking there could be a method on _Types to do that, which System could call, or something like that.

**Comment by teqdruid** [comment]
It seems like we should be registering the typedecls in `maybe_create_alias` if it's newly added to the registry.

**Comment by teqdruid** [comment]
Were you thinking the typedecl stuff would be a separate PR?

**Review by teqdruid — APPROVED** [review]
Assuming the typedecls stuff is a separate PR, this looks good to me. Thanks!

**Comment by mikeurbach** [comment]
Yep I will follow up with actually adding the typedecls. I'll see how hard it will be to synthesize them inside `maybe_create_alias`. I was thinking that might be tough because we'll need an insertion point, and i'm not sure there will always be one when we want... but I'll definitely see about that.

**Comment by teqdruid** [comment]
You could just squirrel the InsertionPoint away in the _Types class, yes?

**Comment by teqdruid** [comment]
And shit. This won't work if one has multiple MLIR modules. This is why I ended up having to get the `hw.module`s back from MLIR IR. You should probably ditch the python registry and just find the scope and look up the typedecl in the MLIR IR directly.

**Comment by mikeurbach** [comment]
What I'm worried about is how to declare an aliases type as a PyCDE module's Inputs or Outputs, potentially before anything is being generated. If there's a top-level mlir::ModuleOp by then, no problem, but I am not yet sure that always holds.

**Comment by teqdruid** [comment]
Yeah, that's true...

**Comment by teqdruid** [comment]
> but I am not yet sure that always holds

It doesn't always hold. And there's probably no reasonable way to get the module when the types are created since they're bound to the context rather than the module.

I don't see any reasonable way to do this other than the approach you're taking. You just have to index the cache by module as well as name.

**Pull request merged**
