### PR TITLE
Updated github workflow caching

### PR DESCRIPTION
**Pull request by Ayushsunny**
Updated the github workflow caching to be based on the actual workflow content 
as mention in the issue #922

### CODE REVIEW

**Review by teqdruid — CHANGES_REQUESTED** [review]
This needs to be a combination of the workflow file and the llvm submodule hash. It also needs to be in both places.

**Comment by Ayushsunny** [comment]
> This needs to be a combination of the workflow file and the llvm submodule hash. It also needs to be in both places.
Okay Sir I got you in Workflow file but add both llvm submodule hash I didn't get that also both the places? but I was asked to change only that buildAndTest.yml file. 
Please help me sir as I am new to open source

**Comment by teqdruid** [comment]
There are two places in the `buildAndTest.yml` workflow file where the hash is computed. Both places need to be updated.

**Comment by Ayushsunny** [comment]
> There are two places in the `buildAndTest.yml` workflow file where the hash is computed. Both places need to be updated.

Sir, I have made the changes.
Can you please review it now

**Comment by mikeurbach** [comment]
It's still not quite right. You have the new feature to compute a hash based on the file, but that isn't being used in the two places. All it does right now is compute the hash.

In the `cache-llvm` steps, you will need to use the new output in the `key`. You can look at how npcomp is doing it to see the right syntax to specify this.

**Comment by Ayushsunny** [comment]
> It's still not quite right. You have the new feature to compute a hash based on the file, but that isn't being used in the two places. All it does right now is compute the hash.
> 
> In the `cache-llvm` steps, you will need to use the new output in the `key`. You can look at how npcomp is doing it to see the right syntax to specify this.

Okay Sir, So we are going to use this syntax in the `key` = 
```yaml
key: ${{ runner.os }}-llvm-18.04-install-${{ steps.get-llvm-hash.outputs.hash }}-${{ steps.get-workflow-hash.outputs.hash }} 
```

in place of this syntax = 
```yaml 
key: ${{ runner.os }}-llvm-nocode-sharedlibs-${{ steps.get-llvm-hash.outputs.hash }}
```

Am I going right @mikeurbach?

**Comment by mikeurbach** [comment]
Yep! Once you make this change, you should see that the github workflow takes much longer to complete for your branch. This is because the cache key is changed, so github will have to rebuild LLVM for us, which takes a while.

**Comment by teqdruid** [comment]
> key: ${{ runner.os }}-llvm-18.04-install-${{ steps.get-llvm-hash.outputs.hash }}-${{ steps.get-workflow-hash.outputs.hash }} 

Nit: the `llvm-18.04-install` is redundant since that's specified in the workflow. I would reduce it to just `llvm`.

**Comment by Ayushsunny** [comment]
> > key: ${{ runner.os }}-llvm-18.04-install-${{ steps.get-llvm-hash.outputs.hash }}-${{ steps.get-workflow-hash.outputs.hash }}
> 
> Nit: the `llvm-18.04-install` is redundant since that's specified in the workflow. I would reduce it to just `llvm`.

Thank you sir

**Comment by Ayushsunny** [comment]
Why I'm getting conflicts ?
@teqdruid @mikeurbach

**Comment by mikeurbach** [comment]
Seems like the `key` line has been changed on the `main` branch. If you pull down the latest `main` and rebase your change on that, you should be able to resolve the conflict.

**Comment by Ayushsunny** [comment]
> Seems like the `key` line has been changed on the `main` branch. If you pull down the latest `main` and rebase your change on that, you should be able to resolve the conflict.

Sorry Sir, I have messed up to this PR,
I'll open a new PR

**Pull request closed without merging**
