### PR TITLE
[Handshake] Support buffer initialization

### PR DESCRIPTION
**Pull request by mortbopet**
This commit adds support for buffer initialization. A list of integer values may be provided to sequential buffers, which will be made the reset values of the buffer registers when lowering to hardware.

### CODE REVIEW

**Review by mikeurbach — COMMENTED** [review]
The code seems to do what is intended, but I'm just curious about how this is going to be used. Is this new attribute something that StandardToHandshake will populate?

**Comment by mortbopet** [comment]
> Is this new attribute something that StandardToHandshake will populate?
Exactly! Sorry for not including that in the commit message.

**Review by mikeurbach — APPROVED** [review]
Ok, makes sense. I guess I have one question: would it make sense to always prime the register this way? In other words, should these initial values be an implementation detail of HandshakeToFIRRTL, rather than something a frontend can set and the lowering will handle generically. I'm still trying to understand why this initial value is needed, and whether there is any meaningful case when it is not needed. Regardless, this code is clear, so maybe after the next PR it will make sense to me.

**Comment by mortbopet** [comment]
I think a front-end needs to be able to set the initialization value of a register. An example could be the GCD implementation of fig 1 in https://dl.acm.org/doi/10.1145/3274280. Such a circuit requires the ability to prime a record (I'll soon push a PR where this is needed in standard-to-handshake).

**Pull request merged**
