### PR TITLE
[ExportVerilog] Handle printing of union types

### PR DESCRIPTION
**Pull request by youngar**

### CODE REVIEW

**Comment by teqdruid** [comment]
@youngar this does not produce valid unions. They have to be padded. Do you mind if I revert this in favor of my pr ?

**Comment by teqdruid** [comment]
https://github.com/llvm/circt/pull/5001 if you need this sooner, feel free to merge it. I'm just waiting for the tests to run.

**Comment by youngar** [comment]
No rush at all, I was just trying to hack in some kind of output for this so I could see what FIRRTL variant types might look like. Obviously should have done a bit more research in to how packed unions work.

**Comment by teqdruid** [comment]
Saw this and wanted to quickly stop you from going too far down the wrong path. Sorry for the curtness -- that first message was from my phone.

Union op support is not gonna be as easy as it was for structs. Is SiFive planning on implementing them? If not, I'll probably do it but it'll probably take me a few days.

**Pull request merged**
