### PR TITLE
Update LLVM to 7acd180

### PR DESCRIPTION
**Pull request by youngar**

### CODE REVIEW

**Comment by teqdruid** [comment]
Does this bump not require any changes to our code?! I can't remember the last time that happened!

**Comment by youngar** [comment]
I should have left the usual message in the description: letting CI build and cache LLVM while I get this working locally :). It remains to be seen what needs to be fixed, but I hope its not too bad!

**Comment by teqdruid** [comment]
Who's taking bets on whether or not it's gonna require changes?

**Review by seldridge — APPROVED** [review]

**Comment by youngar** [comment]
No changes required! Good thing I didn't place a bet..

**Comment by lattner** [comment]
Thank you!

**Pull request merged**
