### PR TITLE
[Handshake] Add sim driver with multiple inputs

### PR DESCRIPTION
**Pull request by Dinistro**
This PR introduces an integration test driver for the `StandardToHandshake` and `Handshake` which feeds multiple inputs into a circuit. 
Such a driver is a required to test the correctness of the task pipelining transformations in `StandardToHandshake`. 

Finally fixes https://github.com/llvm/circt/issues/3429

It would be nice if we could provide a list of inputs to the driver, but my understanding of SystemVerilog and `xsim` is not sufficient to add such a feature. If you guys have an idea on how one could do that, please let me know.

### CODE REVIEW

**Comment by mortbopet** [comment]
Nice - we definitely need more integration tests for `StandardToHandshake` so i welcome anything here.

For PyCDE, we've recently started to leverage `iverilog`+`cocotb` for integration testing (https://github.com/llvm/circt/blob/main/frontends/PyCDE/test/lit.cfg.py#L71-L83, https://github.com/llvm/circt/blob/main/frontends/PyCDE/test/cocotb_testbench.py). This is with some added syntactic sugar for PyCDE, but the point is that parts of CIRCT already leverage these two dependencies for testing.

I suspect writing a small Handshake cocotb library for implementing transactors to the in- and outputs of a handshake circuit would be fairly painless and easy to make generic enough to supply a list of inputs to the circuit ports. I could imagine it would look something like wrapping the handshake ports like [`hlt` over in CIRCT-HLS](https://github.com/circt-hls/circt-hls/blob/main/include/circt-hls/Tools/hlt/Simulator/HandshakeSimInterface.h) with underlying functionality the same as `send` and `awaitHandshake` from your PR.

**Comment by Dinistro** [comment]
Thanks for pointing this out to me. I'll look into it and see if I get this up and running.

**Comment by Dinistro** [comment]
I get some local issues with `iverilog` not being able to handle `automatic logic`. 
Do you know if it's possible to tell `firtool` to emit this differently, such that `iverilog` can handle it?

**Comment by mortbopet** [comment]
https://github.com/llvm/circt/blob/main/test/Conversion/ExportVerilog/disallow-local-vars.mlir might be relevant.

**Comment by Dinistro** [comment]
Thanks for pointing it out to me, it seems to indeed fix the issue.

**Comment by Dinistro** [comment]
I added one possible way of supporting cocotb. It does deliberately not use custom decorators, as copying things around messes up imports. 

The fact that there are always two files, one with the cocotb tests and another with the mlir input is not that nice, but the cocotb file could be reused for different DUTs.

**Review by mortbopet — COMMENTED** [review]
Awesome! This seems like a very convenient thing to have for writing handshake tests.

One thing i am wondering about - there still seems to be some implied expectations on the underlying semantics of the circuits in how outputs are awaited and checked, seeing that the outputs (in these tests) are set to always be ready. It works for the given tests due to the buffering within the circuit being sufficient to delay those outputs actually being valid until after `resCheck` is hit, but i fear that the solution is not general enough.

This already LGTM to merge, but just some comments in case you want to develop this further.
I think (fear) that what has to be done to support this is to wrap the ports within a Handshake wrapper class that upon **any** `await` statement will also await the output `ready`ness of any output, return control to the simulation in that case, and then record the output value in a buffer (this is what is done in `hlt`).
That buffer can then be checked at the end of execution.

**Comment by mortbopet** [comment]
> The fact that there are always two files, one with the cocotb tests and another with the mlir input is not that nice, but the cocotb file could be reused for different DUTs.

Not a worry for me - i prefer different file types to always be separated instead of clever tricks to mix them into one. Helps with syntax highlighting and dev.

One suggestion: since every test requires multiple files, it would probably be a cleaner structure to nest each test within its own directory.

**Comment by Dinistro** [comment]
> One thing i am wondering about - there still seems to be some implied expectations on the underlying semantics of the circuits in how outputs are awaited and checked, seeing that the outputs (in these tests) are set to always be ready. It works for the given tests due to the buffering within the circuit being sufficient to delay those outputs actually being valid until after resCheck is hit, but i fear that the solution is not general enough.

`resCheck` is an async tasks that starts to run once the `cocotb.start_soon` is executed. So does should not happen.
All the sending and receiving is done in "parallel" (fork, join style) and these tasks should execute due to all of them yielding once they wait for the next clock tick.

**Comment by Dinistro** [comment]
> One suggestion: since every test requires multiple files, it would probably be a cleaner structure to nest each test within its own directory.
That's a good point.

**Comment by mortbopet** [comment]
> resCheck is an async tasks that starts to run once the cocotb.start_soon is executed. So does should not happen.
All the sending and receiving is done in "parallel" (fork, join style) and these tasks should execute due to all of them yielding once they wait for the next clock tick.

In that case, this is even more awesome!

**Review by mortbopet — APPROVED** [review]

**Comment by Dinistro** [comment]
Having it in a subdirectory requires a hack to import the helper, but I guess this is fine. Building a python package for that or having everything in the same directory seems to be uglier.

**Pull request merged**
