### PR TITLE
Upgrade C++ standard to C++17

### PR DESCRIPTION
**Pull request by hanchenye**
See [this thread](https://llvm.discourse.group/t/rfc-update-c-standard-from-14-to-17/3951).

### CODE REVIEW

**Review by lattner — APPROVED** [review]
Thanks!

**Comment by teqdruid** [comment]
This won't apply to unified builds, which we are moving to for the Python bindings. How can we do this and get it to apply to unified builds?

**Comment by mikeurbach** [comment]
I hope we can just move it before the `if( CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR )` condition.

**Comment by youngar** [comment]
In CMake `set()` is scoped by by the current directory, so I think we can just move it out of the `if` statement to always apply without changing it for all of LLVM.  It looks like this is what Flang [does](https://github.com/llvm/llvm-project/blob/c1f068b8f1d5f6ca75acc07fdedf2e7416e834ec/flang/CMakeLists.txt#L6).

**Comment by mikeurbach** [comment]
I will add some c++17 code locally and try that out. If it works, I'll move the `set` out of the `if` statement.

**Comment by mikeurbach** [comment]
Looks like that works, so I moved these options out of the `if` here: https://github.com/llvm/circt/commit/76d984414af7016e4afc041bd56a3bf26a81774b

**Pull request merged**
