### PR TITLE
[FIRRTL] try adding a subaccess cache to the fir parser

### PR DESCRIPTION
**Pull request by youngar**
This is an experiement to add an implicit CSE for subindexes and
subfields to the FIRRTL parser.  Due to the nature of the FIRRTL textual
format, we create an incredible number of these things which slows down
the initial IR generation.  On my laptop this sped up parsing a test case from
13-15 second to 8-9 seconds.  Still haven't finished testing this...

### CODE REVIEW

**Comment by uenoku** [comment]
So clever! Is it necessary to consider scopes for subaccess cache? Can't we create unique subaccess near the input definition? (operation locations might be fuzzied though)

**Comment by youngar** [comment]
Yeah, we could have a sort of eager code motion to put the subaccesses right after the definition.  I couldn't decide if that was taking things too far or not, but it seems like a good idea. 
Since declarations can be inside WhenOps we have to decide if we want to clear out values from the cache when we pop a scope. It might be a bit trickier to track this (Maybe a DenseMap<Block *, Std::vector<std::pair<Value, unsigned>>?)

**Comment by uenoku** [comment]
> Maybe a DenseMap<Block *, Std::vector<std::pair<Value, unsigned>>?

Yeah, it makes sense.

**Comment by lattner** [comment]
This is a really great idea Andrew.  I agree that putting the accesses in the same block as the decl makes sense

**Comment by youngar** [comment]
I updated the code to insert the `subfield`/`subindex` ops directly after their declaration.  There was some test code shuffling to try to move some declarations closer to their uses to keep everything looking the same, but for tests with module ports i found it easiest to split some tests into multiple modules.

**Review by darthscsi — APPROVED** [review]
LGTM

**Pull request merged**
