### PR TITLE
[firtool] Add LowerGroups pass

### PR DESCRIPTION
**Pull request by seldridge**
Add the LowerGroups pass to firtool.  Add an end-to-end test that includes nested groups.

### CODE REVIEW

**Review by dtzSiFive — APPROVED** [review]
LGTM!

I don't have this paged in, is there a reason to lower groups so late? Any thoughts/concerns being balanced here?

Actually -- do our passes before this point handle groups properly? I don't think they do-- a few passes don't handle When's so would expect similar problems with groups (IMCP, canonicalizers?).

Maybe it should be scheduled around `ExpandWhens` so passes after that don't handle modules with not-all-in-same-block operate properly?
(of course the best answer is fixing passes so they run in more places, probably)

I'm not sure what early lowering may be losing, just wondering about where this best fits in pipeline.

Modulo above, LGTM,   Woohoo!

**Comment by dtzSiFive** [comment]
Well these passes would already crash in same ways on those inputs today, so from that perspective this doesn't make that worse, although would be good to either lower them away sufficiently early that the pipeline handles things (or fix up passes)?

**Comment by seldridge** [comment]
One thing missing that helps this discussion is we need a pass `GroupSink` (analogous to [`mlir::ControlFlowSink`](https://mlir.llvm.org/doxygen/ControlFlowSink_8cpp_source.html)) which aggressively sinks all operations into groups.

The constraints are then: 

1. `GroupSink` should run before `LowerGroups`. (It's easier to move stuff across a group boundary than an instance boundary.)
2. `LowerGroups` should run before `LowerXMR` as the former creates probe types.

The question is then when should `GroupSink` be run? I had thought that this benefits from running as late as possible as it seems like later in the pipeline means more optimizations have happened and more things can be moved into groups. However, this is more of a feeling than a logical argument.

Scheduling `{GroupSink, LowerGroups}` right after `ExpandWhens` seems like it would also work.

**Comment by seldridge** [comment]
Also, a very naive extension of `ControlFlowSink` to `GroupSink` works for things that are standard SSA operations. I.e., https://github.com/llvm/circt/pull/6184 works for nodes and combinational logic. For this to really be useful it needs all the backedge analysis that `SVExtractTestCode` has. 🥲

**Comment by seldridge** [comment]
Moved it just after the module pass couplet of `ExpandWhens` and `SFCCompat`.

**Pull request merged**
