### PR TITLE
[FIRRTL] Emitted generated modules as private

### PR DESCRIPTION
**Pull request by nandor**
Generated modules internal to the design should not be externally visible. Modules for memory taps are now private and subject to IMCP. Tests have been adjusted to keep their outputs live by wiring them to the toplevel.

### CODE REVIEW

**Review by darthscsi — APPROVED** [review]
This seems right.  Maybe @youngar has a comment?

**Review by dtzSiFive — APPROVED** [review]
LGTM!

What does public/private visibility on extmodule's mean, does it mean anything yet?  I'd guess privately visible declaration of a module (vs declaration of a private module), but I think for now it's not significant.  WDYT?

**Review by uenoku — APPROVED** [review]
LGTM

**Comment by nandor** [comment]
@dtzSiFive The semantics we are pinning down here is to move the visibility of the extmodule to whatever it expands to. If an extmodule it private, once it is materialized, it stays private. However, if it is public, it is reasonably for whatever replaces it to be public as well.

**Comment by youngar** [comment]
Makes sense to me.  One question I find interesting is if we treat the generated bind file as private or not. It's basically optional behaviour or code that the user can opt in to.  In a way it's a part of the public interface of the compilation unit. If the user is allowed to bind the extracted modules manually, then these modules are actually public.  Since we are subjecting these modules to IMCP and the like, it means that they can only be bound as they are in the bind file.

**Pull request merged**
