### PR TITLE
Add boilerplate for an "Analysis" library

### PR DESCRIPTION
**Pull request by mortbopet**
This commit adds the necessary files and code for a new "Analysis" library.

### CODE REVIEW

**Review by mikeurbach — APPROVED** [review]
LGTM, thanks!

Just curious, what analysis do you envision? I've been looking into memref access analysis with the upstream Affine tools, for example. That could definitely go here.

**Comment by mortbopet** [comment]
@mikeurbach I've been working on a very simple bitwidth analysis pass, which could come in handy for conversions that need to decide on bit-widths for i.e. `index` types.
As you'll see, the utility of the to-be proposed PR is doubtful (this will be explained in the PR), but it is a starting point, and something that seems like would naturally fit in an "Analysis" category of passes.

**Comment by youngar** [comment]
If we're following MLIR's example, the `Analysis` library doesn't usually have any passes.  There are a few passes that are just there to test the analyses, but they go into a top level `Transforms` library.  If your pass is transforming the IR, then maybe it belongs in a Transforms lib?

**Comment by mortbopet** [comment]
Sorry for prematurely merging the commit.

@youngar the analysis that i intend to propose indeed does not modify the IR, and (as you mention) has a separate pass used to test the analysis. I was not aware of those test passes being placed elsewhere (in the `Transforms` library, but I can refactor this commit/my upcoming commit if we'd want to adhere to this standard.

**Comment by youngar** [comment]
> Sorry for prematurely merging the commit.
It's not a problem!

Its less clear to me where these simple analysis passses should go.  One benefit to doing it this way is that the analysis passes will be grouped separately from the rest of the passes in the documentation.  My opinion is to leave it the way it is, but I would understand if people would rather not stray from MLIR.

**Comment by mikeurbach** [comment]
I skimmed this too fast, and I agree "Analysis" shouldn't have anything to do with passes, except for test passes. I'm all for having `circt/include/Analysis` and `circt/lib/Analysis`, just like MLIR, but I tend to think `circt/include/Analysis/Passes.h` shouldn't exist. 

c.f. MLIR's setup:

Includes: https://github.com/llvm/llvm-project/tree/main/mlir/include/mlir/Analysis
Libs: https://github.com/llvm/llvm-project/tree/main/mlir/lib/Analysis
Tests: https://github.com/llvm/llvm-project/tree/main/mlir/test/Analysis
Test passes: https://github.com/llvm/llvm-project/tree/main/mlir/test/lib/Analysis

If the simple analysis pass you're talking about goes beyond a test pass to exercise the analysis, I think it would go in `circt/include/Transforms`/`circt/lib/Transforms`.

BTW, is this in addition to the Comb known bits analysis? https://github.com/llvm/circt/blob/main/include/circt/Dialect/Comb/CombOps.h#L43

**Comment by mortbopet** [comment]
I think it would be best to stay in line with upstream MLIR best-practices. Since the pass in my upcoming PR is purely for testing reasons, i'll rework the tablegen'd things in this PR to be located in `circt/test/lib/Analysis`.

@mikeurbach the pass is a (very) simple bit width inference pass, to be used for estimating bit width constraints on values throughout the program (for instance inferring a width for  `index` type values).  I hope to get a PR up sometime tomorrow!

**Comment by youngar** [comment]
Thanks for digging in to where the pass should live, I agree with the plan 👍

**Comment by mikeurbach** [comment]
> bit width inference pass

Ok, maybe touch base with @lattner, he mentioned something that sounds similar here: https://github.com/llvm/circt/issues/1282#issuecomment-905043851

**Comment by lattner** [comment]
Having an analysis library makes sense to me to me, and there are many ways we can do this.  For example, the `InstanceGraph` pass for FIRRTL is in lib/Dialect/FIRRTL instead of another library.

In the case of the HW world, we are going to be practically crosscutting multiple different dialects (SV/Comb/HW, maybe Seq someday) so having a dedicated analysis library would make more sense than putting the code in any of those dialects in particular.

I commented on the other downstream patch, but I really prefer to keep test passes in the lib/ hierarchy.  MLIR upstream is mixed on this, people started putting things in test/.  This is a problem for me for a number of reasons, I'd prefer if we keep the passes in the lib/ directory.

**Comment by lattner** [comment]
Also yes, I do still plan to revise and reimagine the KnownBits thing.  Its use in canonicalize is an antipattern I pulled from LLVM, there are more efficient and scalable ways to solve the same classes of problem.

**Pull request merged**
