### PR TITLE
[CMake] Ensure the build directory for generated Python exists.

### PR DESCRIPTION
**Pull request by mikeurbach**
Ninja is able to generate this, but make does not, and the build
fails.

### CODE REVIEW

**Comment by mikeurbach** [comment]
@teqdruid I think this should fix the issue you were seeing with `make` based builds.

@stellaraccident for context, we found the build works fine with `ninja`, but with `make` this directory doesn't get created automatically, and the `mlir-tblgen` calls fail. And for various reasons, we want to support `make`. Is there a better way to solve this? Perhaps the `declare_mlir_dialect_python_bindings` function could ensure the directory exists? Or maybe there's another way?

**Review by stellaraccident — APPROVED** [review]
Makes sense to do this locally for now. I should poke upstream in this way and make a generic fix.

**Review by teqdruid — APPROVED** [review]
Thanks!

**Comment by teqdruid** [comment]
> And for various reasons, we want to support `make`

That reason being that Ninja doesn't do rebuilds correctly on my system for... reasons.

**Comment by teqdruid** [comment]
This fixed that error. New error: when I run `cmake --build build -j10 --target check-circt-integration`, I get:

```
....
[ 97%] Built target CIRCTMLIRPythonModules.extension._mlirTransforms.dso
[ 97%] Built target CIRCTMLIRPythonModules.extension._mlirLinalgPasses.dso
[ 97%] Built target CIRCTMLIRPythonModules.extension._mlirGPUPasses.dso
[ 97%] Built target CIRCTMLIRPythonModules.extension._mlirConversions.dso
[ 97%] Built target CIRCTMLIRPythonModules.extension._mlirSparseTensorPasses.dso
[ 97%] Built target CIRCTMLIRPythonModules.extension._mlirAllPassesRegistration.dso
[ 97%] Built target CIRCTMLIRPythonModules.extension._circt.dso
[ 97%] Built target CIRCTMLIRPythonModules.extension._mlirAsyncPasses.dso
[ 97%] Built target CIRCTMLIRPythonModules.extension._mlir.dso
gmake[3]: *** No rule to make target 'tools/mlir/python/dialects/_async_dialect_ops_gen.py', needed by 'tools/circt/lib/Bindings/Python/CMakeFiles/CIRCTMLIRPythonModules'.  Stop.
gmake[2]: *** [CMakeFiles/Makefile2:82114: tools/circt/lib/Bindings/Python/CMakeFiles/CIRCTMLIRPythonModules.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:91010: tools/circt/integration_test/CMakeFiles/check-circt-integration.dir/rule] Error 2
gmake: *** [Makefile:26257: check-circt-integration] Error 2
```

**Comment by mikeurbach** [comment]
> gmake[3]: *** No rule to make target 'tools/mlir/python/dialects/_async_dialect_ops_gen.py'

Hmmm, I'm not sure about this. `CIRCTMLIRPythonModules` depends on `MLIRPythonSources`, which should include the file gmake is complaining about. I've only tested the Ninja generator, but I can try to reproduce this and fix it.

**Comment by mikeurbach** [comment]
FWIW I can reproduce this.. I will try to find a fix.

**Comment by teqdruid** [comment]
Sorry, I've been out all day and just got back (so I haven't had a chance to dig into this myself).

**Comment by mikeurbach** [comment]
It's strange, and again only happens with make not ninja. For one, we don't actually care about the file make is complaining about, so I've [replaced](https://github.com/llvm/circt/blob/56262a1ecadd98c9180dbb3aae2b47c0078b1b95/lib/Bindings/Python/CMakeLists.txt#L128)

```
MLIRPythonSources
```

with

```
MLIRPythonSources.Core
MLIRPythonSources.Dialects.builtin
```

To try and scope the dependencies to what we actually care about. In this case, depending on the builtin dialect like that still fails to find the `_builtin_ops_gen.py` file. I am not sure why...

I tried tweaking [this](https://github.com/llvm/llvm-project/blob/bdf4c7b738ee3dfbcd468ec347beec58b6e43a5a/mlir/cmake/modules/AddMLIRPython.cmake#L256) upstream to point to `${ARG_ADD_TO_PARENT}` instead of `${_dialect_target}`, and somehow removing that indirection appeased make and the project built. However, at runtime I realized the generated file hadn't been added to `build/tools/circt/python_packages/circt_core/mlir/dialects/`. The `builtin.py` and the `_builtin_ops_ext.py` files were there, but the generated file didn't appear to have been generated at all.

I'm not sure the tweak I made made any sense, but it seems like something fishy is going on with `declare_mlir_dialect_python_bindings` that works for the ninja generator but not make. Another possibility is there is some bug specific to the make generator, but I haven't looked into that.

I'm gonna have to step away from this for the evening, but if it's blocking development, I guess I'd recommend using ninja+ccache to try and speed up the rebuilds with ninja while we figure out make.

**Comment by mikeurbach** [comment]
Well, I just realized the file we don't actually need the builtin dialect dependency, so we can effectively work around this until we figure out how to include generated files for the upstream dialects. I'm pushing a patch to this branch that does that.

**Comment by mikeurbach** [comment]
This doesn't solve the problem in any way... but I just checked and it should work with upstream MLIR right now.

**Pull request merged**
