### PR TITLE
[Python] Enable release tag

### PR DESCRIPTION
**Pull request by rsetaluri**

### CODE REVIEW

**Review by mikeurbach — COMMENTED** [review]
I think it makes sense to enable this, but just my own understanding, what is the goal here? Does this need to also set CIRCT_RELEASE_TAG?

**Comment by rsetaluri** [comment]
The goal is just to get the right string in the version comment header (`// Generated by CIRCT circtorg-...` vs. `// Generated by CIRCT unknown git version`).

From https://github.com/llvm/circt/blob/main/CMakeLists.txt#L198-L199 it looks like by default it is `circtorg`...are we ok with this? Should we explicitly set it to something else? Maybe `firtool` since it's tied to those releases?

**Comment by mikeurbach** [comment]
I think the default is fine, but might not give a very useful output with circtorg since we don't actually tag releases with that.

In general I am not a fan of having Python wheel releases tied to firtool releases, but for now that is the situation since those of us using firtool do make regular releases and we want the Python wheels to be compatible.

It's already using the firtool tag to pick the wheel version here: https://github.com/llvm/circt/blob/d8b2ba6db6d5d227540121ba747c3b8d04588abf/lib/Bindings/Python/pyproject.toml#L17

So I think there is no additional harm in making this continue to be tied to firtool releases if you want to use `firtool`. You should get a nice `Generated by CIRCT firtool-1.43.0`, whereas with `circtorg` it wouldn't have a nice clean version number since we don't actually make those tags regularly.

**Comment by rsetaluri** [comment]
> In general I am not a fan of having Python wheel releases tied to firtool releases, but for now that is the situation since those of us using firtool do make regular releases and we want the Python wheels to be compatible.

Agree with this. But seems like it's fine functionally...

> 
> It's already using the firtool tag to pick the wheel version here:
> 
> https://github.com/llvm/circt/blob/d8b2ba6db6d5d227540121ba747c3b8d04588abf/lib/Bindings/Python/pyproject.toml#L17
> 
> So I think there is no additional harm in making this continue to be tied to firtool releases if you want to use `firtool`. You should get a nice `Generated by CIRCT firtool-1.43.0`, whereas with `circtorg` it wouldn't have a nice clean version number since we don't actually make those tags regularly.

Also agreed. Updated to have `firtool` release tag.

**Review by mikeurbach — APPROVED** [review]

**Comment by mikeurbach** [comment]
Nice, thanks for adding this.

**Pull request merged**
