### PR TITLE
[VSCode] Add some more flags to the example workspace

### PR DESCRIPTION
**Pull request by GeorgeLyon**
Suggested by @stellaraccident, these might improve build performance.

### CODE REVIEW

**Comment by lattner** [comment]
Cool, do they?  :-)

**Comment by GeorgeLyon** [comment]
They will likely make incremental builds faster (due to reduced linking time) and clean builds slower. I haven't yet run thorough tests of build times (IMO, just doing a couple of builds on your local machine is insufficient to make such claims, a more robust test harness is usually necessary)

**Comment by stellaraccident** [comment]
`LLVM_USE_SPLIT_DWARF` should be a pure win. Aside from some release scenarios, I don't think it has a downside. My SSDs are quite happy with less shuttling of hundreds of megs/gigs of debug info around :)

**Review by teqdruid — APPROVED** [review]
LGTM

**Pull request merged**
