### PR TITLE
[SV] Allow sv.wire in any non-procedural region.

### PR DESCRIPTION
**Pull request by mikeurbach**
The previous verifier required sv.wire to exist in the top-level body
of a hw.module. This relaxes the verifier to allow wires in any
non-procedural region.

### CODE REVIEW

**Comment by mikeurbach** [comment]
Is it sufficient to check just that the parent is non-procedural? It seems like if the direct parent is non-procedural, further ancestors should not be. But I took a quick look, and don't see that explicitly being verified. Should this look up the whole chain of ancestors to be safe, or is just checking the parent ok?

**Review by seldridge — APPROVED** [review]
LGTM

I was trying to check that `verifyInNonProceduralRegion` will compose correctly. I.e., I think the actual check is that this is in entirely non-procedural regions all the way to the root `HWModuleOp`. However, glancing at the ODS for SV it looks like this is already the case.

**Review by darthscsi — APPROVED** [review]
Yes, non-procedural regions should never be in procedural regions.

**Comment by mikeurbach** [comment]
Just realized sv.wire already has the verifyInNonProceduralRegion check from the NonProceduralOp trait: https://github.com/llvm/circt/blob/15b970f4b77245430139d8eb2153f8645ec022d2/test/Dialect/SV/errors.mlir#L139. So I think I can actually just remove the extra verifier on top of that.

**Pull request merged**
