### PR TITLE
[Handshake] Add buffer on all merge outputs

### PR DESCRIPTION
**Pull request by mortbopet**
As far as i interpret the theory, buffers are only needed to break combinational cycles in the style of dataflow circuits that we generate. However, i am starting to suspect that there is something within our flow which requires buffers to be placed on all "logical" cycles as well. Deadlock has been observed in some circuits where control flow is a loop with multiple basic blocks in the loop (b0->b1->b2->b3->b1). This might also be correlated with memory accesses within those blocks, but further investigation is needed.

Nevertheless, experimentally, almost all deadlocks are removed when we add a sequential buffer to break combinational cycles, and for any remaining merge-like operations, add a FIFO buffer on their output, which alleviates the situation described above.

### CODE REVIEW

**Review by mikeurbach — COMMENTED** [review]
This makes sense to me, after updating the tests.

> almost all deadlocks are removed

I'm curious in what situations this strategy is not sufficient.

**Comment by teqdruid** [comment]
If you haven't seen it, [Bounded Dataflow Networks and Latency-Insensitive Circuits](https://dspace.mit.edu/bitstream/handle/1721.1/58834/Vijayaraghavan-2009-Bounded%20Dataflow%20Networks%20and%20Latency-Insensitive%20Circuits.pdf?sequence=1&isAllowed=y) helped a bunch when I was trying to implement this sort of thing in the past.

**Comment by mortbopet** [comment]
@teqdruid thank you for the reference, it is a good read! The interesting difference between this work and (as far as i understand) BDNs are that we're not assuming a fifo between each component/basic block/... the theory that the handshake dialect/Dynamatic builds (http://arcade.cs.columbia.edu/df-memocode17.pdf) on mostly states that buffers are only needed to break combinational cycles, and any buffer beyond that is purely for optimization purposes.

**Comment by mikeurbach** [comment]
I have read both those references before while working on these problems myself, but one point from Compositional Dataflow Circuits just jumped out to me:

> Such buffering is mandatory on loops in the Kahn network and on channels with initial tokens (see §2.2)

This PR seems to be the best way to address "loops in the Kahn network", as I mentioned before. The part about "and on channels with initial tokens" is interesting though... I wonder if some strategically placed buffers for initial tokens, along with the change in this PR, would solve the remaining deadlocks.

Either way, I think this is a good step forward in the work to provide minimal buffering for functional correctness!

**Pull request merged**
