### PR TITLE
Update MLIR

### PR DESCRIPTION
**Pull request by GeorgeLyon**
This is the same branch as https://github.com/llvm/circt/pull/573 but moved into the repo so that it is easier for others to access.

As of this writing, I'm still trying to track down the missing `_mlir__mlir_ciface_llhd_init` symbol. Help is appreciated.

### CODE REVIEW

**Comment by teqdruid** [comment]
I've been able to repro the issue locally via docker (with another commit). Assuming you've got docker set up, you can just run `utils/run-docker.sh` and get the error.

**Comment by GeorgeLyon** [comment]
Yup, I've actually been able to repro the issue without Docker locally, but haven't yet gotten to figuring out a fix

**Comment by teqdruid** [comment]
Does 'ciface' mean C (api) interface?

**Comment by GeorgeLyon** [comment]
That would make sense! I was curious about that

**Comment by teqdruid** [comment]
Doesn't look like it's c api:

```c++
  auto invocationResult = engine->invoke("llhd_init", arg);
  if (invocationResult) {
    llvm::errs() << "Failed invocation of llhd_init: " << invocationResult;
    return -1;
  }
```

```c++
  template <typename... Args>
  llvm::Error invoke(StringRef funcName, Args... args) {
    const std::string adapterName =
        std::string("_mlir_ciface_") + funcName.str();
    llvm::SmallVector<void *> argsArray;
    // Pack every arguments in an array of pointers. Delegate the packing to a
    // trait so that it can be overridden per argument type.
    // TODO: replace with a fold expression when migrating to C++17.
    int dummy[] = {0, ((void)Argument<Args>::pack(argsArray, args), 0)...};
    (void)dummy;
    return invokePacked(adapterName, argsArray);
  }
```

**Comment by teqdruid** [comment]
@fabianschuiki Can you help out with this?

**Comment by teqdruid** [comment]
Looks like `llhd_init` is a generated function: https://github.com/llvm/circt/blob/d994757a0d5778d0c4d6bc387792e2caa48de051/lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp#L1113

**Comment by youngar** [comment]
The `ciface` name mangling is done when the LLVM MLIR lowers to real LLVM.  The default linkage for functions is ` CArg<"Linkage", "Linkage::External">:$linkage,`, which didn't change.  Maybe try dumping the llvm ir and seeing what is there?  On my working/in the past version i see that `llhd_init` is one of the functions generated.  It might be worth noting that this function is inserted by a re-writer pattern during lowering.
``` mlir
// ./build/bin/llhd-sim -dump-llvm-ir test/Dialect/LLHD/Simulator/sim_arbitrary_signal_size.mlir
define void @llhd_init(i8* %0) local_unnamed_addr !dbg !3 {
  %2 = tail call i8* @malloc(i64 0), !dbg !7
  tail call void @allocEntity(i8* %0, i8* getelementptr inbounds ([10 x i8], [10 x i8]* @instance.root.root, i64 0, i64 0), i8* %2), !dbg !7
  %3 = tail call dereferenceable_or_null(2) i8* @malloc(i64 2), !dbg !9
  %4 = bitcast i8* %3 to i1*, !dbg !9
  store i1 true, i1* %4, align 1, !dbg !9
  %5 = tail call i32 @allocSignal(i8* %0, i32 0, i8* getelementptr inbounds ([10 x i8], [10 x i8]* @instance.root.root, i64 0, i64 0), i8* %3, i64 1), !dbg !9
  %6 = tail call dereferenceable_or_null(4) i8* @malloc(i64 4), !dbg !10
  %7 = bitcast i8* %6 to i16*, !dbg !10
  store i16 -256, i16* %7, align 2, !dbg !10
  %8 = tail call i32 @allocSignal(i8* %0, i32 1, i8* getelementptr inbounds ([10 x i8], [10 x i8]* @instance.root.root, i64 0, i64 0), i8* %6, i64 2), !dbg !10
  %9 = tail call dereferenceable_or_null(64) i8* @malloc(i64 64), !dbg !11
  %10 = bitcast i8* %9 to i256*, !dbg !11
  store i256 12345678901234567890123456789012345678901234567890, i256* %10, align 4, !dbg !11
  %11 = tail call i32 @allocSignal(i8* %0, i32 2, i8* getelementptr inbounds ([10 x i8], [10 x i8]* @instance.root.root, i64 0, i64 0), i8* %9, i64 32), !dbg !11
  ret void, !dbg !7
}

```

**Comment by youngar** [comment]
The symbol name mangling looks a little weird to me, is it supposed to have `_mlir_` on it twice? Maybe it has something to do with this change? https://github.com/llvm/llvm-project/commit/d6efb6fc86a6ded63fc50e3a31377a1f4aa33c6e

**Comment by GeorgeLyon** [comment]
Thanks for the hints @youngar! Honestly, this is all going a bit over my head, but I checked that `llhd_init` is indeed being emitted in the IR:

``` mlir
define void @llhd_init(i8* %0) local_unnamed_addr !dbg !3 {
  %2 = tail call i8* @malloc(i64 0), !dbg !7
  tail call void @allocEntity(i8* %0, i8* getelementptr inbounds ([10 x i8], [10 x i8]* @instance.root.root, i64 0, i64 0), i8* %2), !dbg !7
  %3 = tail call dereferenceable_or_null(2) i8* @malloc(i64 2), !dbg !9
  %4 = bitcast i8* %3 to i1*, !dbg !9
  store i1 true, i1* %4, align 1, !dbg !9
  %5 = tail call i32 @allocSignal(i8* %0, i32 0, i8* getelementptr inbounds ([10 x i8], [10 x i8]* @instance.root.root, i64 0, i64 0), i8* %3, i64 1), !dbg !9
  %6 = tail call dereferenceable_or_null(4) i8* @malloc(i64 4), !dbg !10
  %7 = bitcast i8* %6 to i16*, !dbg !10
  store i16 -256, i16* %7, align 2, !dbg !10
  %8 = tail call i32 @allocSignal(i8* %0, i32 1, i8* getelementptr inbounds ([10 x i8], [10 x i8]* @instance.root.root, i64 0, i64 0), i8* %6, i64 2), !dbg !10
  %9 = tail call dereferenceable_or_null(64) i8* @malloc(i64 64), !dbg !11
  %10 = bitcast i8* %9 to i256*, !dbg !11
  store i256 12345678901234567890123456789012345678901234567890, i256* %10, align 4, !dbg !11
  %11 = tail call i32 @allocSignal(i8* %0, i32 2, i8* getelementptr inbounds ([10 x i8], [10 x i8]* @instance.root.root, i64 0, i64 0), i8* %9, i64 32), !dbg !11
  ret void, !dbg !7
}
```

Hopefully someone from the LLHD side of things will just know the fix. If that happens, feel free to push directly to this branch (which has the advantage of having cached the LLVM build already).

**Comment by mikeurbach** [comment]
No promises, but just an FYI I'm building this version of LLVM and I'll try taking a look at the LLHD error this morning. I'm not familiar with the LLHD to LLVM conversion and execution, so again no promises.

**Comment by youngar** [comment]
@mikeurbach I just got this compiling locally, my tiny computer takes forever when I have to update LLVM. I'm finding that changing the code to use `invokePacked()`, which I think has the old behavior, fixes the issue.  It has something to do with the C function wrapper interface, which the some docs mention [here](https://mlir.llvm.org/docs/LLVMDialectMemRefConvention/#c-compatible-wrapper-emission).  Possibly the new version of `invoke` assumes that the functions are marked with the attribute `llvm.emit_c_interface`?
```c++
  auto invocationResult = engine->invokePacked("llhd_init", arg);
```

**Comment by mikeurbach** [comment]
Interesting.. I hadn't seen those docs, but catching up. It does seem like this was just a breaking change to `invoke` upstream (or we were in a fragile state here in CIRCT). If switching `invoke` -> `invokePacked` works, that sounds good to me.

**Review by mikeurbach — APPROVED** [review]
:+1: thanks for the fix @youngar. I just confirmed this locally and it looks good to me.

**Pull request merged**
