### PR TITLE
Bump LLVM for Canonicalizer Perf. Regression Fix

### LINKED ISSUE #1700: Performance Regression (After LLVM Merge?)
There's a pretty comical performance regression that showed up last night. This is suspected to be related to the LLVM merge.

Screen Shot 2021-09-02 at 12 36 51

See: [circt.org/perf](https://circt.org/perf)

### PR DESCRIPTION
**Pull request by seldridge**
Fixes #1700.

Signed-off-by: Schuyler Eldridge <schuyler.eldridge@sifive.com>

### CODE REVIEW

**Comment by mikeurbach** [comment]
FYI I think the commit is pointing to the master branch of `circt/llvm` but in general we've been updating main. Also, if possible can you update the history without creating a merge commit? It's mildly more convenient to keep the history of `circt/llvm` identical to `llvm/llvm-project`. For PRs, I think this is the one good time to use rebase and merge.

**Comment by seldridge** [comment]
🤔 Thanks for the heads up... Is it fine if I do some forcible pushing to clean up `circt/llvm`?

Also, are we approaching a point where we can drop the `circt/llvm` indirection? (Is there any patch set that we're maintaining there that matters?)

**Comment by seldridge** [comment]
I fixed this quickly (which involved some history rewriting) and updated `circt/llvm`. I have a branch with the old merge history if we need to recover it for whatever reason. Sorry about that.

**Comment by teqdruid** [comment]
I can't think of the last llvm patch we needed significantly before it was
gonna land in llvm... So we can probably ditch the mirror.

**Comment by mikeurbach** [comment]
> I can't think of the last llvm patch we needed significantly before it was
gonna land in llvm... So we can probably ditch the mirror.

Agreed. I believe this mirror was originally to stage graph regions, but we haven't been staging a change of that magnitude for some time. Also, thanks @seldridge for aligning the history, that's what I had in mind.

**Comment by lattner** [comment]
+1 for dropping the mirror!

**Pull request merged**
