### PR TITLE
Fix InnerSymDCE, add support for erasing+setting inner symbols

### LINKED ISSUE #4391: [InnerSymDCE] inner symbols on ports are not DCE'd, fields not handled/considered
Module ports are not considered for removal in InnerSymDCE, such as this example:

```mlir
firrtl.circuit "Simple" {

  firrtl.module @Simple() {
    %out = firrtl.instance child sym @child @Child(out out : !firrtl.uint<1>)
  }
  firrtl.module @Child(out %out : !firrtl.uint<1> sym @outsym) {
    %c0_ui1 = firrtl.constant 0: !firrtl.uint<1>
    firrtl.strictconnect %out, %c0_ui1 : !firrtl.uint<1>
  }
}
```

Where `@outsym` is dead and can be removed.

### PR DESCRIPTION
**Pull request by dtzSiFive**
Fixes #4391 .

FIRRTL-only version of #4418.

### CODE REVIEW

**Comment by dtzSiFive** [comment]
More limited FIRRTL-only version if the changes in 4418 or #4789 are too much .

**Comment by dtzSiFive** [comment]
Closing in favor of various split-out PR's.

**Comment by dtzSiFive** [comment]
Let's get this fixed while working out the InnerSymbol story in HW.

**Review by mikeurbach — APPROVED** [review]
We discussed this a while back, and I think it looks good to me.

**Pull request merged**
