### PR TITLE
[StaticLogic] Add initiation interval attribute for pipelines.

### PR DESCRIPTION
**Pull request by mikeurbach**
This attribute represents the initiation interval (II) of a
pipeline. For now, it is a simple integer representing the II computed
by the Scheduling infrastructure.

### CODE REVIEW

**Comment by mikeurbach** [comment]
As promised in #2157 this adds an II attribute. This is just the necessary addition to parse/print/attach it to a pipeline. There is still a TODO in the verifier to actually check the II is correct w.r.t. the op's semantics, but I'd like to leave that to the next PR, since there will be some additional helper methods to define to make that simple.

**Comment by mortbopet** [comment]
What's the incentive for creating a dialect attribute for this? How do you see the attribute evolving to something more than just an integer?

I'm also a bit worried about forcing it to be part of the parsed operation; i'd hope to be able to hand-write a staticlogic pipeline and then let the analysis infrastructure determine the II of the loop - and have II be a regular attribute like
```mlir
staticlogic.pipeline.while iter_args(%arg0 = %false) : (i1) -> (i1) attributes {II = 2 : i32} {
```

**Comment by mikeurbach** [comment]
I was just thinking there's not really any point in having it be a dialect attribute. I remember the HLS dialect PR initially had something about pipeline style, but even then that was just an enum. I'll just use an IntegerAttr for this.

The reason I added it as an inherent attribute on the operation in ODS is because it seems like something we want to force transformations to consider. For example, see the discussion in this recent thread: https://llvm.discourse.group/t/on-querying-an-operations-intrinsic-core-vs-external-user-defined-attributes/4498. If we just stick it in the generic attributes dictionary, the conservative thing for generic passes to do is drop it.

I'm intrigued by the idea of inferring the II. That's not that much different than verifying it.... so it should be possible. How about if I make it an optional integer? When present it will be verified.

**Comment by jopperm** [comment]
I agree that the II should be an inherent attribute because it's part of the semantics of the pipeline operation. The downstream lowering pass will look at it to construct the controller/FSM logic accordingly, I presume.

It's important that this is different from a future `#hls.pipeline<II = ...` attribute, which I'd interpret like the usual pragmas, i.e. as a *hint* to the compiler to try and pipeline the annotated construct with the given II, but if that's not possible, any larger II is also fine.

I think the `OptionalAttr<IntegerAttr>` is just right here.
* If you construct the pipeline from a scheduled `affine.ForOp` or similar, then you set the II from the scheduling problem's solution.
* If you build the pipeline and its stages some other way (meaning, you schedule by hand), you can omit it and invoke some helper to infer it from the value defs and uses across the stages.
* The verifier re-uses the inference code, and checks if the value of the II attribute is larger than the inferred II.

**Comment by mikeurbach** [comment]
Thanks for the feedback @jopperm, that is what I had in mind. If it's all the same to you guys I'll do that in a follow up PR to keep the scope of the current PR small.

**Review by jopperm — APPROVED** [review]
> If it's all the same to you guys I'll do that in a follow up PR to keep the scope of the current PR small.

Yeah, makes sense. This one LGTM!

**Review by mortbopet — APPROVED** [review]
LGTM; with II being an optional attribute, maybe there should also be a test where the attribute is not present.

**Pull request merged**
