### PR TITLE
Remove explicit phase annotations

### PR DESCRIPTION
**Pull request by rwy7**
Rather than tracking phases at a fine-grained level in the types, we are going to be tracking phase at the granularity of ports.

### CODE REVIEW

**Review by dtzSiFive — APPROVED** [review]
This backs out the string-related changes re:phase type interface usage (only user so far in landed PR's), right?

LGTM!

Should this (or follow-on) also remove the phase type interface?

**Comment by rwy7** [comment]
I think I'm going to keep the phased type interface, and will use it to validate what types can appear in a property-port.

**Comment by dtzSiFive** [comment]
> I think I'm going to keep the phased type interface, and will use it to validate what types can appear in a property-port.

Oh!! Yeah, totally, my mistake.  Sounds great! :+1: .

**Review by youngar — APPROVED** [review]

**Comment by rwy7** [comment]
Nevermind, I am removing the phased type interface after all 🥲

**Pull request merged**
