### PR TITLE
[FIRRTL][Inliner] Support per-field syms, update local users.

### LINKED ISSUE #5598: [FIRRTL][Inliner] Handle inner symbols with fieldID != 0
Inliner only handles top-level symbols.  Consider this small example modified from its lit test on renaming scenarios:

```mlir
firrtl.circuit "CollidingSymbolsFields" {
  hw.hierpath private @nla1 [@CollidingSymbolsFields::@foo, @Foo::@bar, @Bar]
  firrtl.module @Bar() attributes {annotations = [{circt.nonlocal = @nla1, class = "nla1"}]} {}
  firrtl.module @Foo() attributes {annotations = [{class = "firrtl.passes.InlineAnnotation"}]} {
    %b = firrtl.wire sym [<@b,1,public>] : !firrtl.bundle<a: uint<1>, b: uint<1>>
    firrtl.instance bar sym @bar @Bar()
  }
  firrtl.module @CollidingSymbolsFields() {
    firrtl.instance foo sym @foo @Foo()
    %collision_b = firrtl.wire sym @b : !firrtl.uint<1>
    %collision_bar = firrtl.wire sym [<@bar,1,public>] : !firrtl.bundle<a: uint<1>, b: uint<1>>
  }
}
```

Point inliner at it (` circt-opt -firrtl-inliner`) to see the resulting failure due to not understanding/inspecting/handling symbols that aren't on fieldID=0:

```
inliner-perfield-nocheck.mlir:10:20: error: redefinition of inner symbol named 'b'
    %collision_b = firrtl.wire sym @b : !firrtl.uint<1>
                   ^
inliner-perfield-nocheck.mlir:10:20: note: see current operation: %1 = "firrtl.wire"() {annotations = [], inner_sym = #hw<innerSym@b>, name = "collision_b", nameKind = #firrtl<name_kind droppable_name>} : () -> !firrtl.uint<1>
inliner-perfield-nocheck.mlir:5:10: note: see existing inner symbol definition here
    %b = firrtl.wire sym [<@b,1,public>] : !firrtl.bundle<a: uint<1>, b: uint<1>>
```

### PR DESCRIPTION
**Pull request by dtzSiFive**

### CODE REVIEW

**Comment by dtzSiFive** [comment]
cc https://github.com/llvm/circt/issues/5598 -- TODO: link issue from commit/PR, include test.

**Comment by prithayan** [comment]
Shouldn't the following `@nla2` annotaiton become a local annotation, instead of being dropped,
```
firrtl.circuit "CollidingSymbolsFields" {
  hw.hierpath private @nla1 [@CollidingSymbolsFields::@foo, @Foo::@bar, @Bar]
  hw.hierpath private @nla2 [@CollidingSymbolsFields::@foo, @Foo::@b_0]
  firrtl.module @Bar() attributes {annotations = [{circt.nonlocal = @nla1, class = "nla1"}]} {}
  firrtl.module @Foo(in %x : !firrtl.bundle<a: uint<1>, b: uint<1>> sym [<@b_0,1,public>,<@foo,2,public>]) attributes {annotations = [{class = "firrtl.passes.InlineAnnotation"}, {circt.nonlocal = @nla2, class = "nla2"}]} {
    %b = firrtl.wire sym [<@b,1,public>,<@bar_0,2,public>] : !firrtl.bundle<a: uint<1>, b: uint<1>>
    firrtl.instance bar sym @bar @Bar()
    %1 = firrtl.ref.rwprobe <@Foo::@b_0> : !firrtl.uint<1>
    %2 = firrtl.ref.rwprobe <@Foo::@bar_0> : !firrtl.uint<1>
    %3 = firrtl.ref.rwprobe <@Foo::@foo> : !firrtl.uint<1>
  }
  firrtl.module @CollidingSymbolsFields(in %x : !firrtl.bundle<a: uint<1>> sym [<@b_0,1,public>]) {
    firrtl.instance foo sym @foo @Foo(in x : !firrtl.bundle<a: uint<1>, b: uint<1>>)
    %collision_b = firrtl.wire sym @b : !firrtl.uint<1>
    %collision_bar = firrtl.wire sym [<@bar,1,public>,<@bar_0,2,public>] : !firrtl.bundle<a: uint<1>, b: uint<1>>
  }
}
```
output with this PR: 
```
firrtl.circuit "CollidingSymbolsFields" {
    hw.hierpath private @nla1 [@CollidingSymbolsFields::@bar_1, @Bar]
    firrtl.module @Bar() attributes {annotations = [{circt.nonlocal = @nla1, class = "nla1"}]} {
    }
    firrtl.module @Foo(in %x: !firrtl.bundle<a: uint<1>, b: uint<1>> sym [<@b_0,1,public>, <@foo,2,public>]) attributes {annotations = [{circt.nonlocal = @nla2, class = "nla2"}]} {
      %b = firrtl.wire sym [<@b,1,public>, <@bar_0,2,public>] : !firrtl.bundle<a: uint<1>, b: uint<1>>
      firrtl.instance bar sym @bar @Bar()
      %0 = firrtl.ref.rwprobe <@Foo::@b_0> : !firrtl.uint<1>
      %1 = firrtl.ref.rwprobe <@Foo::@bar_0> : !firrtl.uint<1>
      %2 = firrtl.ref.rwprobe <@Foo::@foo> : !firrtl.uint<1>
    }
    firrtl.module @CollidingSymbolsFields(in %x: !firrtl.bundle<a: uint<1>> sym [<@b_0,1,public>]) {
      %foo_x = firrtl.wire sym [<@b_0_0,1,public>, <@foo_0,2,public>] : !firrtl.bundle<a: uint<1>, b: uint<1>>
      %foo_b = firrtl.wire sym [<@b_1,1,public>, <@bar_0_0,2,public>] : !firrtl.bundle<a: uint<1>, b: uint<1>>
      firrtl.instance foo_bar sym @bar_1 @Bar()
      %0 = firrtl.ref.rwprobe <@CollidingSymbolsFields::@b_0_0> : !firrtl.uint<1>
      %1 = firrtl.ref.rwprobe <@CollidingSymbolsFields::@bar_0_0> : !firrtl.uint<1>
      %2 = firrtl.ref.rwprobe <@CollidingSymbolsFields::@foo_0> : !firrtl.uint<1>
      %collision_b = firrtl.wire sym @b : !firrtl.uint<1>
      %collision_bar = firrtl.wire sym [<@bar,1,public>, <@bar_0,2,public>] : !firrtl.bundle<a: uint<1>, b: uint<1>>
    }
  }

```

**Comment by dtzSiFive** [comment]
> Shouldn't the following `@nla2` annotation become a local annotation, instead of being dropped,

Thank you for pushing for breakages, this is a tricky thing to handle! Really appreciate it!

Regarding the example-- ah, yes.  Okay so I somewhat intentionally didn't bother trying to make this work (note it presently crashes on your input) re:updating old-style NLA's (leaf reference isn't just the module, but points to the symbol in particular) since that looked super hard and I /think/ we don't need that anymore?

I'm not sure, though, will investigate a bit more.  Please LMK if that sounds wrong!  If not, I actually meant to push on (and perhaps bug you about) whether no longer needing to support leaf references (old-style NLA's) could significantly simplify the pass?  The only symbols in NLA's we should need to update these days, I think/hope, are the ones on instances (which can't have per-field symbols anyway).  WDYT?

**Review by prithayan — APPROVED** [review]
I think I agree, we need not complicate the implementation further to support old-style NLAs. 
LGTM.

**Comment by dtzSiFive** [comment]
> Thank you for pushing for breakages, this is a tricky thing to handle! Really appreciate it!
> 
> Regarding the example-- ah, yes. Okay so I somewhat intentionally didn't bother trying to make this work (note it presently crashes on your input) re:updating old-style NLA's (leaf reference isn't just the module, but points to the symbol in particular) since that looked super hard and I /think/ we don't need that anymore?
> 
> I'm not sure, though, will investigate a bit more. Please LMK if that sounds wrong! If not, I actually meant to push on (and perhaps bug you about) whether no longer needing to support leaf references (old-style NLA's) could significantly simplify the pass? The only symbols in NLA's we should need to update these days, I think/hope, are the ones on instances (which can't have per-field symbols anyway). WDYT?

I'm revisiting inliner and wanted to pick this up, as per-field should work everywhere when I'm done.  Either by converting to new-style for efficiency reasons (Inliner doesn't have to worry about updating anything when cloning most things, just instances) or old-style to reduce test churn on that front.

However, looking at the specific example, I'm not sure it's quite well-formed and I missed that at the time.

Probably the intent was a non-local port annotation?
The non-local module annotation in the example:

```mlir
firrtl.circuit "CollidingSymbolsFields" {
  hw.hierpath private @nla1 [@CollidingSymbolsFields::@foo, @Foo::@bar, @Bar]
  hw.hierpath private @nla2 [@CollidingSymbolsFields::@foo, @Foo::@b_0]
  firrtl.module @Bar() attributes {annotations = [{circt.nonlocal = @nla1, class = "nla1"}]} {}
  firrtl.module @Foo(in %x : !firrtl.bundle<a: uint<1>, b: uint<1>> sym [<@b_0,1,public>,<@foo,2,public>]) attributes {annotations = [{class = "firrtl.passes.InlineAnnotation"}, {circt.nonlocal = @nla2, class = "nla2"}]} {
```

Is on the module but the `hierpath` points to the port.

Anyway the code is straightforward (already written) to scan through but probably not worth the bother longer-term since we maybe don't use old-style anymore anyway.

Regardless that doesn't change the rest of our discussion from what back then, as the current inliner does /not/ rename using anything other than the inner symbol for the root.

**Pull request merged**
