### PR TITLE
[FIRRTL] Nest CSE+Canon passes to run on FModuleOp

### PR DESCRIPTION
**Pull request by youngar**
The compiler can parallelize pass which are running on distinct
IsolatedFromAbove operations.  Moving these passes to run on the
FModuleOp will increase the ability of the compiler to parallelize their
execution. Since there are no operations under the CircuitOp other than
FExtModule and FModule, this does should not change what gets CSE'd and
Canonicalized.

### CODE REVIEW

**Comment by lattner** [comment]
nice, I'll be curious to see if this speeds up any of the testcases.  AFAIK, test1/2 only have a single module so they probably won't be affected.

**Review by lattner — APPROVED** [review]

**Comment by youngar** [comment]
I was trying to compare single-threaded vs multi-threaded performance using firtool, and I realized that firtool is always running the passes multithreaded.  I added some code to respect the `--mlir-disable-threading` flag.

I'm noticing that the first round of canonicalization on firrtl modules is about the same, and the user time == wall time.  The second canonicalization pass on RTL modules has improved quite a bit. I'm not sure why its not multithreaded in the first case, maybe pass manager only parallelizes on the outermost nesting?

**Comment by lattner** [comment]
I'm not really sure, have you tried adding printfs to see if they are being run concurrently?

**Review by fabianschuiki — APPROVED** [review]
This looks like a very nice addition to me. Possibly also some perf gains for larger designs with lots of parallel `firrtl.module`s :thinking:

**Comment by lattner** [comment]
nice, lgtm

**Pull request merged**
