### PR TITLE
[FIRRTL] fix missing type conversion in FoldRegMems

### PR DESCRIPTION
**Pull request by unlsycn**
Fix https://github.com/chipsalliance/chisel/issues/4536

### CODE REVIEW

**Comment by rwy7** [comment]
Hi, the underlying issue seems to be in FoldUnusedBits (introduced in https://github.com/llvm/circt/pull/4652), a different memory canonicalizer, which wasn't correctly handling signed data in a memory. The bitcast op added in this PR hides the problem. We found a different way to produce the error which does not involve the 1-element-memory -> register fold. I have a different fix over here https://github.com/llvm/circt/pull/7913, please take a look!

Thanks for all your help!

**Comment by unlsycn** [comment]
> Hi, the underlying issue seems to be in FoldUnusedBits (introduced in #4652), a different memory canonicalizer, which wasn't correctly handling signed data in a memory. The bitcast op added in this PR hides the problem. We found a different way to produce the error which does not involve the 1-element-memory -> register fold. I have a different fix over here #7913, please take a look!
> 
> Thanks for all your help!

Hi, thanks for your explanation! #7913 won't fix https://github.com/chipsalliance/chisel/issues/4536 since the actual lack of type cast in the original issue is that `dataPart` and `nextPart` produced by `firrtl.bits` are unsigned but connect to the signed cast.  While #7913 is obviously a nice patch, it doesn't seems to be related to https://github.com/chipsalliance/chisel/issues/4536.

**Comment by rwy7** [comment]
Ugh, thanks, looks like I managed to golf the example to a different issue, sorry. I think you're right. Do you think it makes more sense to cast when applying the mask, right here: https://github.com/llvm/circt/blob/main/lib/Dialect/FIRRTL/FIRRTLFolds.cpp#L3036

Either way, LGTM.

**Review by rwy7 — APPROVED** [review]

**Comment by seldridge** [comment]
I rebased this and merged it here: https://github.com/llvm/circt/commit/996b1283d861d4f373d8b854c7f84ede8e227b1a Thanks for the PR.

**Comment by unlsycn** [comment]
> I rebased this and merged it here: [996b128](https://github.com/llvm/circt/commit/996b1283d861d4f373d8b854c7f84ede8e227b1a) Thanks for the PR.

Thank you so much, I am sorry that I forgot about this PR.

**Pull request closed without merging**
