### PR TITLE
[ESI] Wrap modules exposing latency insensitive signals to expose ESI channels

### PR DESCRIPTION
**Pull request by teqdruid**
Add two functions which are intended to be exposed over an API:
- A function to heuristically locate signal port triplets with ready valid on an RTL module.
- A function which takes an RTL module and a list of those port triplets and build a 'shell' around that module which 'uplifts' the port triplets to ESI channels.

Adds an 'esi-tester' binary to execute these two functions.

### CODE REVIEW

**Comment by teqdruid** [comment]
@mikeurbach I ended up going the C++ binary testing route. It was very useful for debugging (via gdb), something I didn't think of before.

**Comment by teqdruid** [comment]
I'll take another look with a fresh head tomorrow, but I think this is ready to review. It's complex so I've added some code docs for when I forget how it works.

**Review by mikeurbach — COMMENTED** [review]
Just took a quick scan through, and the gist makes sense. I've considered this approach before.

For my understanding, is the expected use-case something like the following? I.e. part of #733?

1. Take a Handshake module run it through HandshakeToFIRRTL
2. Run the FIRRTL LowerTypes pass to flatten bundles
3. Run the FIRRTL through LowerToRTL
4. Run this new wrapper detector/builder
5. The rest of the lowering...

I was actually thinking about this flow just last night. This works for sure, but relying on the _valid and _ready suffixes seems somewhat fragile. However, I'm really not sure if there is a more pragmatic way to get this to work. It seems like FIRRTL is going to have to support [bi-directional bundles](https://github.com/llvm/circt/issues/536) in 3. at some point, but the only solution right now is still to flatten them out with 2. first, so this method is the only way to recover that information without making deeper changes.

I'm still thinking about what this _should_ look like in the long term. Unless Handshake generated ESI directly, it seems like we'll always end up to some heuristic check like this to recover which signals were the valid, ready, and data. Maybe if HandshakeToFIRRTL [started lowering to RTLModules](https://github.com/llvm/circt/issues/742), we could then add a flag like `-generate-esi` that could update that pass to generate the ESI wrappers in the top-level module explicitly.

In general, I support this approach. I think it can definitely be improved once we do the work to start evolving Handshake's lowering away from FIRRTL.

**Comment by mikeurbach** [comment]
Another thought to maybe make this a little more explicit: what if we had some annotation added when LowerTypes flattens out bundles, to say "hey, these were originally grouped together".

I guess that would actually have almost the same information as a sv::ModportType... Maybe we should just do #536 in that case, and then ESI could work with the interface modport rather than looking for a group of three signals. I do have a branch for #536 if we want to try that.

**Comment by darthscsi** [comment]
> Another thought to maybe make this a little more explicit: what if we had some annotation added when LowerTypes flattens out bundles, to say "hey, these were originally grouped together".

(Take this with a lack of context tag) You might also not run LowerTypes and they LowerToRTL would give you structs from non-directional bundles.

**Comment by mikeurbach** [comment]
> You might also not run LowerTypes and they LowerToRTL would give you structs from non-directional bundles.

Yep, I tried the "just don't run LowerTypes" approach to see what LowerToRTL does. Looks like it makes structs but craps out with an assertion [here](https://github.com/llvm/circt/blob/4d91f1bcaa5c3e1a59ba1136873bf45e873c7cda/lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp#L1226). I checked, and the Value's type at that point is `rtl.inout<rtl.struct<...>>`. Didn't dig too far into it, but I guess this is how bi-directional bundles error out these days?

The problem is these latency insensitive bundles will always be bi-directional. That's why I opened #536 initially- to handle this case with sv.interface instead of rtl.struct. Maybe we could update LowerToRTL to not fail on bi-directional bundles? Something along the lines of "I don't know what to do with this, but I won't fail, and you're on your own". I haven't been keeping up with LowerToRTL recently, so I don't know if this is reasonable or not.

**Comment by teqdruid** [comment]
The intention here is for the "system assembly" API wherein you know _something_ about the module being wrapped. Either the specific LI ports or that the heuristics work on a particular module. The flow is that you have some MLIR representation of a module (e.g. lowered firrtl, loaded mlir file, a set of rtl.module.externs you know about), possibly combine them into one IR, then you attach the ESI ports to it, then do the system assembly. It's both the practical short term thing to do and helpful long term.

I agree there are better ways for specific dialects / languages. (Like attaching ESI channels on Handshake as part of a lowering phase.) This is meant for general usage, then we can add stuff for specific use cases down the road. Note that finding the ports via heuristic is optional, so the wrapping method could also be used with some sort of annotations.

**Comment by teqdruid** [comment]
@mikeurbach Does the handshake dialect lower to firrtl ports with ready/valid names consistent with the find heuristic I created? That wasn't the use case I had in mind, but it'd be nice nonetheless.

**Comment by mikeurbach** [comment]
> @mikeurbach Does the handshake dialect lower to firrtl ports with ready/valid names consistent with the find heuristic I created? That wasn't the use case I had in mind, but it'd be nice nonetheless.

Not quite. They get named like `arg0_data`, `arg0_valid`, `arg0_ready`. What does the current heuristic work for today?

I kind of figured the finding ports part was specific to Handshake, but if it is meant to be more general, that's great. Have you thought about how to extend it with other heuristics, i.e. if I wanted to add one that works for Handshake?

I see how the generic wrapping method is separately useful on its own.

**Comment by teqdruid** [comment]
> Not quite. They get named like `arg0_data`, `arg0_valid`, `arg0_ready`. What does the current heuristic work for today?

foo/foo_valid/foo_ready. It's intended for someone writing in a language where they have control over the port names (e.g. Chisel).

**Comment by teqdruid** [comment]
I've added <name>_data to the heuristic. In addition to a short-term hack for handshake, it sounds like a common enough naming scheme.

**Comment by mikeurbach** [comment]
Thanks, looking forward to trying it out!

**Pull request merged**
