### PR TITLE
[CI] Add BUILD_SHARED_LIBS to the pull request builds

### PR DESCRIPTION
**Pull request by youngar**
BUILD_SHARED_LIBS builds all libraries as shared libraries.
Historically, this has mostly been used as a developer productivity
flag, as it greatly speeds up linking. The real value in testing with
this flag enabled is that it reveals mistakes in CMake library
dependencies, such as missing dependencies and circular dependencies.
Additionally, there has been recent effort to increase the level of
support for shared libraries to enable MLIR C/Python bindings, and
supporting this flag down the line is probably a must.

### CODE REVIEW

**Comment by youngar** [comment]
The compile jobs worked, but the tests failed with "Assert Duplicate option categories". For this PR to pass LLVM has to be rebuilt with `BUILD_SHARED_LIBS`, and I didn't change the Github Cache ID for the LLVM install. I will push a change encoding shared libraries in the tag name.

**Comment by youngar** [comment]
With this change the LLVM cache size has changed:
```
Before: 67s copy time, ~883 MB (925914721 B)
After:  31s copy time, ~293 MB (307687254 B)
```

**Comment by teqdruid** [comment]
> With this change the LLVM cache size has changed:
> 
> ```
> Before: 67s copy time, ~883 MB (925914721 B)
> After:  31s copy time, ~293 MB (307687254 B)
> ```

Excellent! This alone will speed up the workflow.

**Review by teqdruid — APPROVED** [review]
Thanks!

**Comment by mikeurbach** [comment]
Nice, +1 from me for this change. I use this setting locally and it would be great if CI helped catch these issues before they land.

**Review by darthscsi — APPROVED** [review]
LGTM

**Comment by youngar** [comment]
I'm just waiting on an integration build over on my fork

**Comment by youngar** [comment]
Ok, looks like PR https://github.com/llvm/circt/pull/657 fixed the integration issues, I have a passing integration test [here](https://github.com/youngar/circt/actions/runs/595439600). Merging, and then I'll manually trigger the workflows.

**Pull request merged**
