### PR TITLE
[Scheduling] Overhaul simplex-based modulo scheduler.

### LINKED ISSUE #4375: [Scheduling] ModuloSimplexScheduler fails to resolve resource conflicts
*(initially reported by @matth2k in #4374)*

The following instance triggers an assertion while re-entering the scheduled operations after the II was increased to resolve a resource conflict.

```mlir
ssp.instance of "ModuloProblem" {
  library {
    operator_type @unlimited [latency<1>]
    operator_type @limited [latency<1>, limit<1>]
  }
  graph {
    %0 = operation<@unlimited>()
    %1 = operation<@limited>(%0)
    %2 = operation<@limited>(%0)
    %3 = operation<@limited>(%0)
    %4 = operation<@limited>(%0)
    operation<@unlimited>(%1, %2, %3, %4)
  }
}
```

Curiously, the bug is not triggered if we had only 3 limited operations. Hence, this could be about moving ops across the next multiple of the II, but further investigation is needed.

### PR DESCRIPTION
**Pull request by jopperm**
This PR fixes #4375 and improves the quality of solutions found by the `ModuloSimplexScheduler`.

- e779cc5f162aed257303a719c8e35103c79eb0b6 was just a simple bug that caused wrong solutions with oversubscribed operator types to be returned.
- f09ae330c485afe9562b0b16f169f79e39516dcc is the main fix. This modulo scheduler works by iteratively fixing resource-limited operations to specific time steps, which are baked into the simplex tableau. In the paper, this done as a modulo decomposition, making the value dependent on the II-parameter. I believe the intention was to automatically shift ops to keep them in the same MRT slot whenever the II changes, but I didn't get that to work properly in all cases. Instead, I now just fix operations to absolute time steps (same as for the non-cyclic `SharedOperatorsProblem`), and compensate the start times of already scheduled ops myself.
- While debugging, I saw that the scheduler sometimes produces horribly bad results, because the operations have no mobility (w.r.t. the ASAP/ALAP times). In b8f878a66aec809ffc963f177ee4de9fea5775a4, I changed the behavior to look at the II-1 next time steps instead. This might make the schedule longer, but if the partial solution is still feasible under the current II, we much prefer that over incrementing the II to resolve the resource conflict.
- Lastly, 24c39aebf5e300f8d4e7f79f783442822dff811f fixes an oversight: When considering to move already scheduled operations in order to resolve the resource conflict at hand, we can skip ops that use a different operator type.

### CODE REVIEW

**Comment by jopperm** [comment]
@matth2k Could you test if the scheduler now works correctly in context of your `AffineToPipeline` work, please?

**Comment by matth2k** [comment]
> @matth2k Could you test if the scheduler now works correctly in context of your `AffineToPipeline` work, please?

Awesome. Yes, I'll give it a go and get back to you. Thanks.

**Comment by andrewb1999** [comment]
> @matth2k Could you test if the scheduler now works correctly in context of your `AffineToPipeline` work, please?

I've tested a bunch of `AffineToPipeline` cases with this scheduler overhaul. Every case tested so far works now, so these fixes seem to do their job. Once this is merged we can add some more test cases as part of #4414.

**Comment by jopperm** [comment]
Great, thanks for trying this out.

**Pull request merged**
