### PR TITLE
Bump LLVM submodule

### PR DESCRIPTION
**Pull request by teqdruid**

### CODE REVIEW

**Comment by teqdruid** [comment]
If nobody's done this by next week, I'll put some time into it.

**Comment by youngar** [comment]
Did some work towards this and bumped to a newer LLVM SHA for something I am looking for (LocationAttr in OpBase.td)

Some of the interesting commits have been:

https://reviews.llvm.org/D141254
Rename `getLoopIVs` to `getAffineForIVs`

https://reviews.llvm.org/D139665
Rename `BlockAndValueMapping` to `IRMapping`

https://reviews.llvm.org/D141231
Generate `inferReturnTypes` for ops with `TypesMatchWith`.
No need to manually implement these functions.
Some new builders collide with out old ones.

https://reviews.llvm.org/D140886
https://reviews.llvm.org/D141604
Should later fix deprecated `kEmitRawAttributes`, use the new fold API.

**Comment by teqdruid** [comment]
@youngar Looks like you're running into this https://github.com/llvm/circt/issues/4570

**Comment by teqdruid** [comment]
Looks like I was pretty lazy about optimizing includes in the msft dialect. I just pushed a fix removing irmapping.h from the files which don't need it.

**Comment by teqdruid** [comment]
XFAIL'ing the broken Calyx tests for the time being as discussed in today's ODM.

**Comment by prithayan** [comment]
I'm working on the remaining 2 failures. Will try to fix them by late tonight.

**Comment by mikeurbach** [comment]
I fixed the tests and the ASAN issues, and made a PR into this branch: https://github.com/llvm/circt/pull/4592. We can merge it if we want, or I can land those separately later.

**Comment by teqdruid** [comment]
Nice! I say we merge it into this PR.

**Comment by prithayan** [comment]
Fixed the remaining two issues on main. Rebased this branch to top of main, but not sure why the build is still failing. All the tests passed on local run.

**Comment by teqdruid** [comment]
Might be this:

image

**Comment by youngar** [comment]
I also see this one, have to scroll up a bit from the bottom.
image

I think the target should get defined by this line: https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/Linalg/IR/CMakeLists.txt#L35

I have no clue what it could be.  I think the build that is still running is using Ninja, and the one that failed used Make, if former succeeds I think it could be a clue.

**Comment by teqdruid** [comment]
Yeah, we should probably switch the CI builds to use Ninja. And update
cmake while we're at it.

**Comment by teqdruid** [comment]
Image build with the latest version of cmake: https://github.com/circt/images/actions/runs/4018786549

**Comment by teqdruid** [comment]
@prithayan The "short integration tests" indicate that the circt-reduce test is still failing. Can you investigate further?

**Comment by teqdruid** [comment]
I've got a PR for ninja and cmake here: https://github.com/llvm/circt/pull/4597. Once it's merged, I think the builds will be green on this PR.

**Comment by prithayan** [comment]
Great, hopefully finally we have fixed all the issues.

**Comment by teqdruid** [comment]
The changes look good to me and I've merged the changes from #4597 . Anyone should feel free to click the "merge" button when the last two CI builds complete successfully (which I fully expect).

**Pull request merged**
