### PR TITLE
[CMake -- Linking] Enables / fixes dynamic linking

### PR DESCRIPTION
**Pull request by teqdruid**
Compiles fine in both dynamic and static linking mode with capnp builds. PR gate build will test static non-capnp build / test.

Tests in dynamic linking mode, however, don't work. Vast majority fail with: 
```
circt-opt: /home/jodemme/circt/llvm/llvm/lib/Support/CommandLine.cpp:361: void (anonymous namespace)::CommandLineParser::registerCategory(llvm::cl::OptionCategory *): Assertion `count_if(RegisteredOptionCategories, [cat](const OptionCategory *Category) { return cat->getName() == Category->getName(); }) == 0 && "Duplicate option categories"' failed.
Toplevel function main not found!
```

@youngar Could you take a look? Feel free to push changes directly to this branch.

### CODE REVIEW

**Comment by youngar** [comment]
I'll take a look, just wonder was your LLVM built with or without `BUILD_SHARED_LIBS`?

**Comment by teqdruid** [comment]
It was not -- that could well be the problem.

**Comment by youngar** [comment]
Testing locally, where it looks like I have built LLVM with `BUILD_SHARED_LIBS`, this patch is working.  I will build LLVM from scratch just to make sure I can get the same error.

**Comment by teqdruid** [comment]
Thanks! Feel free to merge this patch once you confirm that was my issue.

**Comment by youngar** [comment]
Problem reproduced!  Looks like you must match the BUILD_SHARED_LIBS flag between LLVM and CIRCT.  Thanks for fixing this!

**Pull request merged**
