### PR TITLE
[HW] Fix canonicalization for wires with aggregate types

### PR DESCRIPTION
**Pull request by uenoku**
The optimization to replace unwritten wires with x-values currently
assumes that the wire has integer types. So canonicalization crashes for 
aggregate types. This commit fixes the issue by bitcasting x-values into 
aggregate values.

### CODE REVIEW

**Review by prithayan — APPROVED** [review]
Looks good

**Comment by prithayan** [comment]
@uenoku , can you add tests for vectors and bundles with vector also.

**Comment by lattner** [comment]
Have you considered generalizing ConstantXOp to work with arbitrary aggregate types?  That would be more composable, and I don't see a reason to limit it to integer result.  We have to do that for ConstantOp because we need to know the width of the value.

**Comment by uenoku** [comment]
> Have you considered generalizing ConstantXOp to work with arbitrary aggregate types? That would be more composable, and I don't see a reason to limit it to integer result. We have to do that for ConstantOp because we need to know the width of the value.

Yeah, that makes sense to me. It sounds nicer. I'll do that.

**Comment by lattner** [comment]
Thank you Hideto!

**Comment by uenoku** [comment]
Closed because the issue will be fixed by #2338.

**Comment by uenoku** [comment]
The test was picked by https://github.com/llvm/circt/commit/92f83d4d37f540c2dd54cec91dec38f0139b809e

**Pull request closed without merging**
