### PR TITLE
[FIRRTL] Add Layer Association to Probes

### PR DESCRIPTION
**Pull request by seldridge**
Add support for representing an optional layer in each probe type.  This only handles storage and MLIR printing/parsing.

I'll be breaking this work up into a bunch of small pieces. This is the first.

### CODE REVIEW

**Comment by seldridge** [comment]
> How do we verify layer symbols in ref types? hw.typealias also has a symbol in a type but unfortunately a malformed type alias is rejected at ExportVerilog at last.

There's a couple of places this can happen: 

1. For ports, this can happen as part of the module verifier for ports. It can also potentially happen as a walk starting from the module, but not visiting layerblocks.
2. The layer blocks already have to walk their bodies (but not other layer blocks) to check they aren't doing any illegal capturing of values (currently this disallows capturing ref types).

I also considered if there was a way to get a symbol table into the type verifier. This seems possible if the type parameter includes a reference to the module. However, this may be problematic.

**Comment by darthscsi** [comment]
> 2\. The layer blocks already have to walk their bodies (but not other layer blocks) to check they aren't doing any illegal capturing of values (currently this disallows capturing ref types).

Layers shouldn't need to walk their ops.  If we want name resolution to be simple, probably probe ops need to check their parents to do this verification.

**Comment by seldridge** [comment]
> If we want name resolution to be simple, probably probe ops need to check their parents to do this verification.

This seems like a good idea to me.

**Review by dtzSiFive — APPROVED** [review]
IR changes LGTM.

I don't understand the full story but these changes adding the layer parameter and IR printing/parsing seem solid so far.

Thanks for touching up utilities and passes to pass this through!

**Comment by dtzSiFive** [comment]
FWIW stale branch ^ .

**Pull request merged**
