### PR TITLE
[HWMemSimImpl] Add mux pragmas to memory reads

### PR DESCRIPTION
**Pull request by uenoku**
This PR adds mux pragmas to memory reads in HWMemSimImpl in a similar way to https://github.com/llvm/circt/pull/3404.

### CODE REVIEW

**Review by darthscsi — COMMENTED** [review]
Is this a optimal change so it should be always on, or should it be under user control?

**Comment by uenoku** [comment]
I'm in flavor of making these pragmas optional (ref:https://github.com/llvm/circt/issues/3828). But if we made the pragmas 
 optional for HWMemSimImpl, we should align LowerToHW too.

**Comment by mruff-sifive** [comment]
> 

There should be module control and perhaps instance control.

**Comment by mruff-sifive** [comment]
> There should be module control and perhaps instance control.

The use of MUXes is a tradeoff between area and place/route density (net, instance count). Specifically for high read port data structures like register files MUXes can be a useful implementation strategy.

**Comment by uenoku** [comment]
> There should be module control and perhaps instance control.

Hmm, interesting. I think currently we don't have a good mechanism to control this from Chisel/FIRRTL (except for annotations). Is there some condition or threshold to identify interesting modules?

**Comment by mruff-sifive** [comment]
Perhaps for now we use the same global control for these so people can experiment. In one of my conversations with AndrewL he mentioned that there is work planned to enabled tis kind of enablement. We will need to run a bunch of experiments to begin to develop a heuristic to control this feature.

**Comment by mruff-sifive** [comment]
Can we get this in using the same global control as the other MUX pragmas. That will allow groups to generate the RTL both ways to compare and contrast and hopefully provide training for the heuristics. Most likely we'll eventually want instance control but we should not pend this on that functionality.

**Comment by uenoku** [comment]
> Can we get this in using the same global control as the other MUX pragmas. That will allow groups to generate the RTL both ways to compare and contrast and hopefully provide training for the heuristics

That makes sense, I'll update this PR to create a global flag which controls both multibit mux and memory.

**Comment by uenoku** [comment]
Added a flag `-strip-mux-pragmas` to control mux pragmas of LowerToHW and HWMemsimImpl

**Comment by mruff-sifive** [comment]
Looks good. Can I grep for 'builder.create<hw::ArrayGetOp>(array, index);' to identify other potential annotation locations?

**Comment by uenoku** [comment]
> 
Looks good. Can I grep for 'builder.createhw::ArrayGetOp(array, index);' to identify other potential annotation locations?

Probably we can grep AraryGetOp. As far as I see, LowerToHW and HWMemSimImpl cover all creations of default firtool pipeline. Possibly there are other few places which we would need to support for aggregate preservation, but aggregate preservation is not enable by default yet.

**Pull request merged**
