### PR TITLE
[Python] Updates for changes to use more kwargs in D124717

### PR DESCRIPTION
**Pull request by mikeurbach**

### CODE REVIEW

**Comment by mikeurbach** [comment]
Not for review/merging yet, this is to follow https://reviews.llvm.org/D124717.

**Comment by teqdruid** [comment]
Thanks for keeping up with this.

**Comment by teqdruid** [comment]
Did we end up not needing to do this? Or were these changes unnecessary?

**Comment by mikeurbach** [comment]
Looks like it was taken care of in https://github.com/llvm/circt/pull/3168/files, thanks @nandor!

**Pull request closed without merging**
