### PR TITLE
Update dialect overview diagram

### PR DESCRIPTION
**Pull request by jopperm**
I plan to show the dialect diagram in the EuroLLVM talk I'm preparing with @mikeurbach and @teqdruid. Concrete changes:

- PyCDE -> MSFT (instead of RTL dialects)
- MSFT <-> Scheduling (coming soon, therefore dashed)

These two edges destroyed the layout, obviously, so the remaining changes in this PR try to fix that.

Also, it's been a while since we last updated the diagram (#2072), so I wanted to ask if anyone else has changes you want me to incorporate while I'm at it.

dialects

### CODE REVIEW

**Review by teqdruid — APPROVED** [review]
LGTM. Thanks

**Comment by mikeurbach** [comment]
While you're at it, Affine -> StaticLogic and StaticLogic -> Calyx can be made solid!

**Comment by cgyurgyik** [comment]
> While you're at it, Affine -> StaticLogic and StaticLogic -> Calyx can be made solid!

Is there a StaticLogic -> Calyx conversion that I missed?

**Comment by mikeurbach** [comment]
> Is there a StaticLogic -> Calyx conversion that I missed?

It is currently grafted on to SCFToCalyx, but it can and should be separated.

**Comment by cgyurgyik** [comment]
Ah yes I recall now, thanks!

**Review by cgyurgyik — APPROVED** [review]
Super nit :-)

**Pull request merged**
