### PR TITLE
[HandshakeToFIRRTL] Add control buffering to BufferOp lowering.

### PR DESCRIPTION
**Pull request by mikeurbach**
Previously, the lowering would only buffer the data/valid
network. This adds buffering on the ready network.

### CODE REVIEW

**Comment by mikeurbach** [comment]
I only made the minimal changes to get the unit test to pass, but I can add more tests for the actual logic there. We still don't have an [integration test](https://github.com/llvm/circt/pull/464)... but in my personal tests with Verilator, this patch resolves the warnings about `Feedback to clock or circular logic`. I have also used Vivado to test this, and found that without this, any circuit that has a loop will basically have all signals undefined.

**Comment by mikeurbach** [comment]
This also came up in testing #543.

**Review by hanchenye — APPROVED** [review]
The implementation is easy to follow, LGTM!

**Comment by mikeurbach** [comment]
Thanks for the review! I will add some basic checks for the additional register to the test case and then land this. Longer term (as in the next weeks but not right now), I do want to work on #587, and I hope we can use that implementation here. It will take a little extra work to plug a new dialect/abstraction into this lowering, so having this patch should help unlock the end-to-end flow for now.

**Pull request merged**
