### PR TITLE
[Ibis] Added missing ibistool to integration test

### PR DESCRIPTION
**Pull request by Dobios**
`ibistool` was missing in the tool list in the integration test making it crash, so I simply added it in. Now the tests run without a problem.

### CODE REVIEW

**Review by teqdruid — APPROVED** [review]
Thanks!

**Comment by teqdruid** [comment]
Looks like a whitespace issue. These config files aren't well formatted anyway, so don't worry about it.

**Comment by Dobios** [comment]
> Looks like a whitespace issue. These config files aren't well formatted anyway, so don't worry about it.

I removed the trailing whitespace, hopefully now the formatting will be happy ^^"

**Comment by teqdruid** [comment]
> > Looks like a whitespace issue. These config files aren't well formatted anyway, so don't worry about it.
> 
> I removed the trailing whitespace, hopefully now the formatting will be happy ^^"

Yep. I thought it was an indentation thing.

**Pull request merged**
