### PR TITLE
[Capnp] Move the minimum CMake version logic to only run if capnp is found

### PR DESCRIPTION
**Pull request by teqdruid**

### CODE REVIEW

**Review by mikeurbach — COMMENTED** [review]
I think this makes sense. Did you test it without capnp on an older cmake?

**Comment by teqdruid** [comment]
no. I suppose I should, but I don't have a system set up with cmake >= 3.20.0 < 3.23. LLVM now requires 3.20.

**Comment by teqdruid** [comment]
Just tested with cmake 3.20. Works as expected.

**Review by mikeurbach — APPROVED** [review]
Thanks for confirming this works.

**Pull request merged**
