### PR TITLE
[ESI] [Cosim] Cap'nProto list encoding for RTL arrays

### PR DESCRIPTION
**Pull request by teqdruid**
There was a simpler way to do/structure this but I'm looking forward a bit to struct support and allocation/placement of pointer data.

### CODE REVIEW

**Review by mikeurbach — COMMENTED** [review]
The gist of this sounds really interesting, and looks good at a first glance. I'll need to take a closer look, and then I can provide some real feedback.

**Comment by teqdruid** [comment]
No rush

Thanks!

**Review by mikeurbach — APPROVED** [review]
Looks reasonable to me. I can't speak to the correctness of all the specifics like the bitwidths of the constant gasket components, but the general approach looks good.

**Comment by teqdruid** [comment]
@mikeurbach  Thanks! I think I've already flushed out some of the obvious bugs (e.g. endianness, size fields, etc) in getting the integration test working so this should be mostly correct.

**Pull request merged**
