### PR TITLE
Adding clang-format check on push and PR

### PR DESCRIPTION
**Pull request by teqdruid**
Using `git clang-format (HEAD^ | PR_BASE)` to look only at only the relevant changes.

### CODE REVIEW

**Comment by lattner** [comment]
ooooh, awesome!  I don't know how github actions work though - @drom can you take a look at this?

**Comment by teqdruid** [comment]
For some reason, the new workflow is failing to fetch the circt repo. It works on my private fork... I'm thinking someone has to authorize it?

**Comment by teqdruid** [comment]
I'm guess this option is selected in this repo:

image

**Comment by teqdruid** [comment]
Pulling back to draft. Probably makes more sense to do in the existing flow since clang-tidy (coming next) requires a compilation.

**Review by stephenneuendorffer — APPROVED** [review]
seems reasonable

**Comment by seldridge** [comment]
Another option here is to use an existing, published action. https://github.com/marketplace/actions/clang-format-lint appears to be the most popular (24 stars) option for running clang-format based on what I could find on the action marketplace.

**Comment by teqdruid** [comment]
You're right that this should be an action. (I didn't even think of that, though it should have been obvious.) I've spent some time poking around this morning, but none of the clang-format actions only look at the files a PR touches. (Or upload the necessary patch, but that's a nice-to-have.)

**Comment by teqdruid** [comment]
This is good to go

**Pull request merged**
