### PR TITLE
[MSFT] Device DB for placed instances

### PR DESCRIPTION
**Pull request by teqdruid**
- Introduces the DeviceDB class to store spatial data regarding placed instances.
- Adapts ExportTcl to use it, reporting out conflicts.

### CODE REVIEW

**Comment by teqdruid** [comment]
This detected a duplicate location in the pycde test code which I did not expect!

**Comment by teqdruid** [comment]
@mikeurbach What's going on with the CI build's python-format check?

image

That's not something I see locally and there's no pyproject.toml in the root. I've also never seen it before.

**Comment by teqdruid** [comment]
The python-format issue isn't related to this change, so I'm merging.

**Comment by mikeurbach** [comment]
The main addition seems fine to me.

Re: the python format check, it sounds like we'd need to install the `toml` package into the container. I'm curious why that just started... didn't @youngar bump the version a couple weeks back? https://github.com/llvm/circt/commit/e16c134c035cb73f47bf311ac318ec21a8a1839a

**Comment by teqdruid** [comment]
You'll see in the revision history that I tried to bump the image to one which had pytoml installed, but that didn't do jack. It also hasn't cropped up in subsequent PRs.

**Comment by teqdruid** [comment]
... and I just realized that "pytoml" != "toml".

**Pull request merged**
