### PR TITLE
[SV] Fix circt-doc documentation generation for SV passes 

### PR DESCRIPTION
**Pull request by youngar**
The filename is SVPasses.td not Passes.td, which is causing the `circt-doc` target to fail.

Initial issue reported by @xgupta [here](https://github.com/llvm/circt/commit/da80538e9f845d62ec3b2a6b7695926b93906e87#commitcomment-46730180).

### CODE REVIEW

**Comment by youngar** [comment]
To make sure this sort of thing doesn't keep happening I opened a PR to build `circt-doc` in our pre-merge check: https://github.com/llvm/circt/pull/556

**Comment by xgupta** [comment]
I think the fix of the issue is making inconsistency in the naming of Passes.td files.

**Comment by youngar** [comment]
@xgupta I assumed that all `Passes.td` files would be renamed to include the dialect name, as we have done for the rest of the files.  Is there a reason why the `Passes.td` files were skipped in the [original renaming](https://github.com/llvm/circt/pull/372)? Otherwise I will open a PR to make them consistent :)

**Comment by youngar** [comment]
@xgupta I just noticed that the website is not showing the [SV passes](https://circt.llvm.org/docs/Passes/#sv-dialect-passes), but the github action for the website looks like its [copying the file](https://github.com/llvm/circt-www/runs/1835242893?check_suite_focus=true#step:11:9) over.. There is a [trailing space](https://github.com/llvm/circt/commit/55e521e5a227520363c6c3d86786a23b7d53122d#diff-3db94081db016ad57fd8c19508b12c1f3a761148c4a8422de72dd6f102eb9fcaR27) after the filename, is there some crazy chance that is the issue?  Otherwise I might spend some time trying to build the website locally

**Comment by xgupta** [comment]
> is there a reason why the Passes.td files were skipped in the original renaming?

Oh, That renaming was done to make CIRCT filenames consistent with MLIR, and MLIR use Passes.td in every dialect so we did the same here.

> I just noticed that the website is not showing the SV passes, but the github action for the website looks like its copying the file over.. 


To display the pass documentation on the website [docs/Passes/index.html](https://github.com/llvm/circt-www/blob/gh-pages/docs/Passes/index.html) should contain the documentation. But here a different folder is SVPasses is created.
> here is a trailing space after the filename, is there some crazy chance that is the issue?

No, I don't think whitespace can be an issue.

> Otherwise, I might spend some time trying to build the website locally

I think it may be more time-consuming to solve these issues. a better solution may be just to rename the SVPasses.td file :)

**Comment by youngar** [comment]
@xgupta I managed to repro locally, removing the space seemed to fix the issue.  If you see [this line](https://github.com/llvm/circt-www/blob/main/copy_docs.sh#L41) here, there is no character allowed between the `]` and the end of the line `$`

**Comment by xgupta** [comment]
You can see due to no heading [SVpasses](https://circt.llvm.org/docs/SVPasses/) is not showing below ESI documentation in circt.llvm.org while a thin white column is there.

**Comment by youngar** [comment]
I opened a PR which I think fixes the issue and improves some of the pass documentation: https://github.com/llvm/circt/pull/561.  I didn't rename SVPasses.td yet since I think its a separate issue.

**Pull request merged**
