### PR TITLE
[Seq] Lower both registers and memories in the same pass

### PR DESCRIPTION
**Pull request by nandor**
This PR moves the conversion of FIRRTL-specific `seq` ops to their own conversion pass, `SeqToSV`. The existing register & memory lowering passes are packaged as re-usable utilities to keep them available as individual transformations. Both the memory and register lowering utilities are packaged into a single parallelized lowering to be used by `firtool`.

### CODE REVIEW

**Comment by seldridge** [comment]
Is there anything new in this PR or is this just reshuffling existing code?

**Comment by nandor** [comment]
A lot of shuffling. And slight cosmetic changes to `LowerFirReg`.

**Comment by mortbopet** [comment]
You may want to update https://github.com/llvm/circt/issues/5639 (+ general reminder of https://github.com/llvm/circt/issues/5463).  
I'll again parrot up about us all to be aware of being mindful of either eventually removing firrtl-specific stuff from Seq (i.e. elaborating it into more generic representations) or extracting it as a separate dialect; it's to me somewhat icky that there's a whole separate walled garden of firrtl inside the seq dialect).

**Comment by nandor** [comment]
I agree, we should move towards eliminating differences. Moving the FIRRTL-specific lowerings out of the `seq` dialect should help keep it cleaner though in the meantime.

**Comment by fabianschuiki** [comment]
Moving Seq-to-SV stuff from the Seq dialect into a conversion is a great improvement!

I was wondering if we couldn't just collapse everything into a `SeqToSV` conversion, combining the lowerings for the FIRRTL and non-FIRRTL ops into one. There aren't too many differences, just that the plain Seq ops use the conversion framework and don't need a global pre-pass, while FIRRTL does. Maybe we could do this in one swoop as a global pre-pass and then a dialect conversion?

**Comment by nandor** [comment]
I'd like to consider that in a subsequent PR. The register/memory lowering are substantial enough for us to keep them in separate files/header, then I think we can work on best bundling them into a transform.

**Comment by nandor** [comment]
Follow-up in #5901.

**Review by fabianschuiki — APPROVED** [review]
LGTM!

Thanks for creating a proper conversion pass. Love the follow-up #5901 as well!

**Pull request merged**
