### PR TITLE
[NFC] remove getting started as it is already on website

### PR DESCRIPTION
**Pull request by xgupta**
Similar to [mlir-www](https://github.com/llvm/mlir-www/blob/main/website/content/getting_started/_index.md) we have a page on [circt-www](https://github.com/llvm/circt-www/blob/main/website/content/getting_started/_index.md) for getting started so we don't need same page here.
See https://circt.llvm.org/getting_started/

### CODE REVIEW

**Comment by xgupta** [comment]
@lattner If it looks good, could you please update the CIRCT website link in the about section to circt.llvm.org/

**Comment by teqdruid** [comment]
I don't know who's responsible for the website or how it's generated and uploaded, but it's not Chris.

Also, I'm not sure how I feel about this change... I'd rather have the getting started doc in this repo. Is that possible?

**Comment by darthscsi** [comment]
It's worth having the in-repo docs link to the repo-version.  Once there are releases, we want the in-repo to track the repo and the static pages to track the last release.

**Comment by xgupta** [comment]
sure!

**Pull request closed without merging**
