### PR TITLE
[circt-test] fix lit config for circt-bmc

### PR DESCRIPTION
**Pull request by unlsycn**
I'm so sorry that my incorrect rebase in #7884 broke that PR. This is the correct version.

### CODE REVIEW

**Comment by unlsycn** [comment]
My mistake😢 @fabianschuiki

**Comment by fabianschuiki** [comment]
No worries at all 😃

**Review by fabianschuiki — APPROVED** [review]
LGTM!

**Comment by fabianschuiki** [comment]
I'll land this right away since it's just a tweaked version of the other PR.

**Pull request merged**
