### PR TITLE
Bump LLVM

### PR DESCRIPTION
**Pull request by darthscsi**

### CODE REVIEW

**Comment by darthscsi** [comment]
@fabianschuiki ltl was violating folding rules by replacing delays -> sequence with their i1 arguments.  folders can't change types.  Probably need a i1 -> sequence cast operator and some canonicalizers to clean things up.

**Review by fabianschuiki — APPROVED** [review]
LGTM! Thanks for fixing the LTL folder. Probably an indication that we should switch to explicit casts instead of accepting multiple types of operands in the LTL ops.

**Comment by darthscsi** [comment]
@teqdruid The WrapValidReadOp folder is changing the result type when it triggers.  This isn't allowed by folders and is being enforced now.  This folder is blocking the llvm bump (and disabling leads to legalization problems in later passes, so I can't just disable it).

**Review by teqdruid — APPROVED** [review]
Looks benign enough to me

**Comment by darthscsi** [comment]
> Looks benign enough to me

What's here is, but I need to know what to do with the ESI folder bug.

**Comment by teqdruid** [comment]
> > Looks benign enough to me
> 
> What's here is, but I need to know what to do with the ESI folder bug.

Sorry, we were posting messages in parallel. I'll look into it this afternoon.

**Comment by darthscsi** [comment]
> > > Looks benign enough to me
> > 
> > 
> > What's here is, but I need to know what to do with the ESI folder bug.
> 
> Sorry, we were posting messages in parallel. I'll look into it this afternoon.

Thanks!  ESIFolds.cpp:18 is converting a esi.channel<i0> to a i1 constant.

```
487               assert(constOp->getResultTypes()[0] == resultType &&
(gdb) print resultType.dump()
!esi.channel<i0>
$1 = void
(gdb) print constOp->getResultTypes()[0].dump()
i1
$2 = void
```

**Comment by teqdruid** [comment]
> > > > Looks benign enough to me
> > > 
> > > 
> > > What's here is, but I need to know what to do with the ESI folder bug.
> > 
> > 
> > Sorry, we were posting messages in parallel. I'll look into it this afternoon.
> 
> Thanks! ESIFolds.cpp:18 is converting a esi.channel to a i1 constant.
> 
> ```
> 487               assert(constOp->getResultTypes()[0] == resultType &&
> (gdb) print resultType.dump()
> !esi.channel<i0>
> $1 = void
> (gdb) print constOp->getResultTypes()[0].dump()
> i1
> $2 = void
> ```

Actually, I'm trying to set an unused result to a UnitAttr. Since it's never used, I didn't think it'd matter -- and it hadn't until now. Fixed in 1e78a4e.

**Pull request merged**
