### PR TITLE
[FIRRTL][EmitOMIR] Don't insert above pass level.

### PR DESCRIPTION
**Pull request by dtzSiFive**
Since EmitOMIR is a firrtl::CircuitOp pass, don't attempt to acccess or modify or insert into the operation above the one the pass is running on.

### CODE REVIEW

**Review by mikeurbach — APPROVED** [review]
It makes sense not to emit things outside the operation the pass is running on. After LowerToHW and ExportVerilog, do these verbatims still get emitted correctly? That would be my only concern.

**Review by uenoku — APPROVED** [review]
LGTM, I think verbatim op won't be erased by LowerToHW.

**Comment by dtzSiFive** [comment]
If we need to insert outside the circuit, we can make this a `ModuleOp` pass (like CreateSiFiveMetadata).

And yeah LowerToHW will make these siblings of the `hw.module` operations (and others) that it creates.

**Comment by dtzSiFive** [comment]
Thanks for the review!

**Pull request merged**
