### PR TITLE
Updated the workflow file and key

### PR DESCRIPTION
**Pull request by Ayushsunny**
Updated the github workflow caching to be based on the actual workflow content
as mention in the issue #922

### CODE REVIEW

**Comment by mikeurbach** [comment]
@teqdruid @youngar I think we have been the ones needing to change this cache key. What do you think of this update? If this workflow is stable enough, I think it makes sense. It does mean rebuilding LLVM if something potentially unrelated is needed in this file.

**Comment by teqdruid** [comment]
I'm OK with rebuilds on workfile file changes. It's the safer thing to do.

**Review by youngar — APPROVED** [review]
Awesome idea, looks good to me!

**Comment by youngar** [comment]
Should we make the same change (eventually) in nightlyIntegrationTests.yaml?

**Comment by teqdruid** [comment]
Yes

**Comment by Ayushsunny** [comment]
> Should we make the same change (eventually) in nightlyIntegrationTests.yaml?

Can I work on that too ?

**Comment by teqdruid** [comment]
Nah. Let's give this a little mileage first.

**Review by darthscsi — APPROVED** [review]

**Comment by teqdruid** [comment]
@Ayushsunny Do you need someone to merge this? Is it good to go?

**Comment by Ayushsunny** [comment]
> @Ayushsunny Do you need someone to merge this? Is it good to go?

@teqdruid Yes, SIr merge this.

**Pull request merged**
