### PR TITLE
Update LLVM submodule

### PR DESCRIPTION
**Pull request by teqdruid**
Update to 6a75041a1614af1ca787af5a18ea9ddbe4dd5c16. This breaks stuff which I don't have time to fix right now, so it will fail the CI check. Anyone who wants to fix can push to this branch.

### CODE REVIEW

**Review by seldridge — DISMISSED** [review]
lgtm as long as it passes regressions. 😄

**Comment by teqdruid** [comment]
> lgtm as long as it passes regressions. 😄

Like I said in the description, it won't.

**Comment by teqdruid** [comment]
Just wanted to get the new llvm in the ci cache and make it easier for individuals who aren't that familiar with git to help 😉 . I'll pick this up when I've got time if nobody beats me to it.

**Comment by seldridge** [comment]
It helps when I read the PR text. 😂 Sounds good, John, thanks!

**Comment by cgyurgyik** [comment]
@youngar Thanks for making the necessary changes to the Calyx dialect!

**Review by darthscsi — APPROVED** [review]

**Comment by teqdruid** [comment]
Thanks for doing this @youngar !

**Comment by lattner** [comment]
thank you so much @youngar !!

**Comment by lattner** [comment]
Thank you for driving this @teqdruid !

**Pull request merged**
