### PR TITLE
[Transforms] add a `memref` flattening pass

### PR DESCRIPTION
**Pull request by mortbopet**
This is a pass which flattens statically sized memories and indexing into them by elaborating multi-dimensional indexing into a tree of multipliers, shifts, and adders. The motivation of this is to be able to lower programs which have multi-dimensional memories through the handshake flow that currently only supports single-dimensional memories when lowering to FIRRTL.

This also creates a "Transforms" CIRCT library, following upstream MLIR conventions.

The PR is marked as draft due to an issue which I can't seem to solve. The `rewriter.convertRegionTypes` throws a memory exception deep within a `DenseMap` function. While i assume the fault is on my side, I've yet to figure out what is actually going wrong. The type conversion approach applied here is similar to what is done elsewhere. I'd very much appreciate if somebody could check out the PR on their end and see if the error can be reproduced.

### CODE REVIEW

**Comment by mikeurbach** [comment]
Thanks for pushing on this! This is another one of my long standing TODOs.

I will pull this down and take a look. My hunch about the issue you mention is the IR mutation that happens outside of the ConversionPatternRewriter. When using a PatternRewriter, you have to do _all_ IR mutation through it, and right now `flattenIndices` is creating its own builder.

**Comment by mortbopet** [comment]
> When using a PatternRewriter, you have to do all IR mutation through it, and right now flattenIndices is creating its own builder.

Will change. However, the issue still occurs when disabling the other patterns and only keeping the `MemRefTypeConversion` pattern... looking forward to hear what happens on your end!

**Comment by mikeurbach** [comment]
I hope you don't mind, I pushed a commit directly to this branch. There were a few things, all related to using the Dialect Conversion framework:

* I added a default conversion for types other than MemRefType, so the TypeConverter will work with other function arguments/results than the specific MemRefTypes we are converting here.
* With that, I was able to use the upstream `populateFuncOpTypeConversionPattern` to convert the FuncOp. That's a tricky one to get right, so it is provided upstream.
* The conversion driver itself wasn't actually using the Dialect Conversion framework, I switched it to use `applyPartialConversion`, which uses the Dialect Conversion driver.
* For that to work, I had to define a conversion target to drive the framework. This case is a little tricky, since we are converting from multi-dim memrefs to flat memrefs. To set up a good target, I had to define every possible op we care about as dynamically legal, depending on whether the memref operands, results, etc. had been converted yet. There is probably a way to do this more generically in terms of `Operation *`, but I opted for doing it once for each kind of concrete op you had in the test.
* For the patterns to work with Dialect Conversion, it is imperative to use the `OpAdaptor` when creating new operations. It will contain the new version of the operation that the framework manages. In case things are partially converted, or rolled back, there is no guarantee we can use the old version of the operation passed to `matchAndRewrite`'s first argument. In all places we call `rewriter.replaceOpWithNewOp` and friends, we should be using the `adaptor`.
* For the tests you had, a couple more conversions were needed for `ReturnOp` and `CondBranchOp`. These were trivial: just re-create the op, but using the mapped operands.

In general, this is really great work, and I totally support using Dialect Conversion for this. This is definitely a fairly advanced use of the Dialect Conversion framework, and all of the above points are somewhat obscure when you are first digging into it. We should take a look at the documentation and see how to improve it... Some of this is documented if you squint, but some of it may just come from my experiences.

**Comment by mortbopet** [comment]
> I hope you don't mind, I pushed a commit directly to this branch

No worries. Thank you very much for checking it out and pushing adding the changes. Seems like A/B'ing with other uses of type conversion around CIRCT and MLIR doesn't expose the subtleties required for this to work.

> To set up a good target, I had to define every possible op we care about as dynamically legal, depending on whether the memref operands, results, etc. had been converted yet

I'll be looking into doing this generically; that seems quite highly unscaleable (and very un-MLIR'y)... I find it strange that it is _that_ difficult to do type conversion :thinking:.

**Comment by mikeurbach** [comment]
> I'll be looking into doing this generically; that seems quite highly unscaleable (and very un-MLIR'y)... I find it strange that it is _that_ difficult to do type conversion :thinking:.

Well, to drive the dialect conversion framework in general, and to get it to do type conversions specifically, you need to use the concept of legalization. Normally you can say certain ops or even entire dialects are illegal. People generally "legalize" IR by replacing some ops with other ops. But in this pass, you aren't actually converting any op into a different op; the same op is legalized by the type conversion. In this case, dynamic legality seems to be the simplest approach. FWIW I think this is still a good use of dialect conversion, if it can be a little generalized.

I am actually quite confident you can condense the legality to one addDynamicallyLegalIOp call, which generically checks that all operands, results, and block arguments are single dimension memrefs. I'm curious if there can also be one generic conversion pattern, which just updates the operands of the op to the ones passed via the adaptor. For ops outside the memref dialect that accept memref operands (cond_br and return in your tests, but there can be others), it would be great to do something generic as well.

**Comment by mikeurbach** [comment]
If you haven't seen it, the "Type conversions the not so hard way" talk provides a lot of great thinking on how these concepts fit together: https://drive.google.com/file/d/1VfVajitgf8ZPnd-HRkJvaJiFLhBsluXN/view?usp=sharing

**Comment by mortbopet** [comment]
Thank you for the link to the talk, it was definitely helpful. I updated `flattenIndices` to compute the multiplication factor statically instead of elaborating into multiple multiplication instructions + added `CallOp` and `BranchOp` support. I think the PR is ready to go!

**Review by mikeurbach — APPROVED** [review]
Awesome, looks great!

**Pull request merged**
