### PR TITLE
[RTL] [Comb] Move comb.constant to rtl

### LINKED ISSUE #665: Move "comb.constant" back to RTL/HW dialects
In [this patch](https://github.com/llvm/circt/pull/660/files) we're having to add a dependency from SV dialect to the comb dialect just to get access to comb.constant.  I think this is a good reason to sink constant into the HW dialect, so we can have comb depend on HW, SV depend on HW, etc.

This is also how I expect the std dialect to sort out in the MLIR SW world.

### PR DESCRIPTION
**Pull request by uenoku**
Move `comb.constant` to `rtl.constant`. 

Will close #665

### CODE REVIEW

**Comment by uenoku** [comment]
Since I don't know where to put `rtl.constant` definition, I have put it in `RTLAggregates.td` for now.

**Comment by uenoku** [comment]
I really don't know why but `rtl.constant` becomes `std.constant` somewhere in canonicalization.
For example, running `circt-opt -canonicalize` for this:
```
module  {
  func @foo(%arg0: i1) {
    %false = comb.constant false
    sv.always posedge %arg0  {
      sv.if %false  {
        sv.fatal
      }
    }
    return
  }
}
```
becomes
```
module  {
  func @foo(%arg0: i1) {
    %false = constant false
    sv.always posedge %arg0  {
      sv.if %false  {
        sv.fatal
      }
    }
    return
  }
}
```
Please let me know if you have any ideas ;)

**Review by lattner — APPROVED** [review]
awesome, thank you!

**Comment by mikeurbach** [comment]
> Please let me know if you have any ideas ;)

Just a guess, but it seems some code must be using `ConstantOp` when it means `rtl::ConstantOp`. I would have expected such code to be a compile-time error because its ambiguous whether we mean `std::ConstantOp` or `rtl::ConstantOp`, but I could be wrong.

I see you already added the `rtl::` prefix in a lot of places here: https://github.com/llvm/circt/pull/673/files#diff-6f80524cbed3f3dee4e82a5f97ae9ade89be7f2132704918ec60d91889bfc751R545, so maybe there are more places it's needed in that file (or a different one)?

**Comment by lattner** [comment]
I bet it has to do with the dialect constant registration stuff.  I think all of RTL/Comb/etc dialects should have the equivalent of `CombDialect::materializeConstant` on trunk.

**Comment by uenoku** [comment]
> I bet it has to do with the dialect constant registration stuff. I think all of RTL/Comb/SV dialects should have the equivalent of CombDialect::materializeConstant on trunk.

Yes, this was the cause. Thank you both!

**Pull request merged**
