### PR TITLE
[NFCI][Conversion] Refactor TableGen Pass includes

### PR DESCRIPTION
**Pull request by fzi-hielscher**
Refactor includes of TableGen passes in the "Conversion" sub-tree to the new style.
See https://github.com/llvm/circt/issues/3962 , https://reviews.llvm.org/D143773

### CODE REVIEW

**Comment by uenoku** [comment]
I really appreciate it, thank you! :pray:

**Comment by fzi-hielscher** [comment]
Glad to see I managed to catch every single code owner in this one PR. 😁 

Regrettably, I was not able to keep a clean separation between scripted and manual changes. If you spot any quirks or have doubts regarding the general shape, do let me know. I've got all the changes accumulated in a single branch [over in my repo](https://github.com/fzi-hielscher/circt/tree/pass-refactor). I'll break out the Dialect passes into PRs after this one has landed safely.

**Review by uenoku — APPROVED** [review]
LGTM for ExportVerilog, Prepare, LowerToHW, SimToSV, VerifToSV, SeqToSV. I'm not familiar with other passes but apparently the change looks great to me. I think it's fine to merge as CI is clean :) Thank you!

**Review by fabianschuiki — APPROVED** [review]
LGTM! Thanks for doing this :partying_face:

**Comment by dtzSiFive** [comment]
Thank you!! 🎉

**Pull request merged**
