### PR TITLE
[NFC] Eliminate simple canonicalizer

### LINKED ISSUE #1294: Eliminate SimpleCanonicalizer pass
The SimpleCanonicalizer should be removable now that the Canonicalizer pass is generalized and takes an options struct.    We should make sure to get this patch first though: https://reviews.llvm.org/D104302

### PR DESCRIPTION
**Pull request by uenoku**
Will close #1294. 
This PR eliminates the implementation of simple canonicalizer and changes to use `mlir::createCanonicalizerPass(config)`. 
This PR replaces `--simple-canonicalizer` with `--canonicalize='top-down=true region-simplify=true'` in all the test files.

### CODE REVIEW

**Review by lattner — APPROVED** [review]
Thank you for cleaning this up!

**Review by seldridge — APPROVED** [review]
Nice.

Is there utility in keeping the `circt::createSimpleCanonicalizerPass()` method around?  It appears to now be only used in two places in `firtool` where a `createCanonicalizerPass(config)` could replace it.

**Comment by uenoku** [comment]
> Is there utility in keeping the `circt::createSimpleCanonicalizerPass()` method around? It appears to now be only used in two places in `firtool` where a `createCanonicalizerPass(config)` could replace it.

It seems so. Should I remove `circt/Transforms` folder because there is nothing other than simple canonicalizer?

**Comment by lattner** [comment]
sure, go ahead and remove the dir too when you have a chance, thanks!

**Review by darthscsi — APPROVED** [review]

**Pull request merged**
