### PR TITLE
Python rtl fix

### PR DESCRIPTION
**Pull request by mikeurbach**

### CODE REVIEW

**Comment by mikeurbach** [comment]
Running integration tests here: https://github.com/llvm/circt/actions/runs/724236651

**Comment by mikeurbach** [comment]
I did some digging in the `inspect` module, but I don't think there is any fancy way to infer the result names. The returned values will be `Value`s in the MLIR sense, but there's not guarantee they have an meaninful name we can dig out. I'm in favor of just building a list of empty names like this PR does, to appease the verifier.

**Comment by teqdruid** [comment]
What does ExportVerilog do with an empty string on the output port?

**Comment by mikeurbach** [comment]
I haven't checked. Let me do a quick test.

**Review by teqdruid — APPROVED** [review]
LGTM. Thanks!

**Comment by mikeurbach** [comment]
It craps out, but with a very helpful error message about needing to supply names.

**Comment by mikeurbach** [comment]
WDYT about just generating names like `result0`, `result1`, ...

**Comment by mikeurbach** [comment]
Double checking integration test suite passes, then will merge: https://github.com/llvm/circt/actions/runs/724264808

**Pull request merged**
