### PR TITLE
Update LLVM to 704a395

### PR DESCRIPTION
**Pull request by youngar**
Priming the CI pumps while I try to get this going locally.

### CODE REVIEW

**Comment by youngar** [comment]
We are pulling the new version of LLVM for [this](https://github.com/llvm/llvm-project/commit/704a39569346401e96a6a3978ddc490dfa828ccc) commit which allows 0-bit APInts.  This will help us model 0 bit constants in FIRRTL, and we properly use IntegerAttr as a (possibly 0-length) bitvector for FIRRTL port directions.

**Comment by lattner** [comment]
Thank you!

**Comment by youngar** [comment]
There is an issue with LLHD to LLVM.  This PSA from discourse seems relevant: https://llvm.discourse.group/t/psa-run-reconcile-unrealized-casts-after-all-convert-to-llvm-from-now-on/4266. 

 ```
  CIRCT :: Conversion/LLHDToLLVM/convert_process_persistence.mlir
  CIRCT :: Dialect/LLHD/Simulator/sim_array_boundary_check.mlir
  CIRCT :: Dialect/LLHD/Simulator/sim_formats.mlir
  CIRCT :: Dialect/LLHD/Simulator/sim_process.mlir
  CIRCT :: Dialect/LLHD/Simulator/sim_wait.mlir
```

Example error:
```
circt-opt test/Conversion/LLHDToLLVM/convert_process_persistence.mlir --convert-llhd-to-llvm | FileCheck test/Conversion/LLHDToLLVM/convert_process_persistence.mlir

convert_process_persistence.mlir:142:8: error: failed to legalize conversion operation generated for result #0 of operation 'llhd.constant_time' that remained live after conversion
  %0 = llhd.constant_time #llhd.time<0ns, 0d, 1e>
       ^
convert_process_persistence.mlir:142:8: note: see current operation: %8 = "llhd.constant_time"() {value = #llhd.time<0ns, 0d, 1e>} : () -> !llhd.time
```

**Comment by maerhart** [comment]
Thanks for the pointer! Just making `UnrealizedConversionCastOp` legal and applying this new pass afterwards leads to type conversion errors, apparently related to the `ProcOpConversion` pattern. I'll take a closer look.

**Comment by maerhart** [comment]
Yes exactly, that's one issue, the other was kind of the same but with a `llvm.load` operand being of the unconverted type `llhd.ptr`. `llhd.proc` and `llhd.entity` have to be converted before their regions/child ops, because some operations (I think `llhd.halt`, `llhd.wait`, etc.) use arguments added when converting e.g. `llhd.proc` to `llvm.func`. During that process they insert code to deal with the global state passed as function argument, etc. where they also replace uses of values by lookups of the global state (e.g, safed before a `llhd.wait` which I think yields execution to the engine, which later resumes there or so). Because of that the `llvm.load` and `llvm.store` (to read/update the global state) used the types of the values (created by not yet converted ops) to be remembered in the global state as they are not given explicitly and a unrealized conversion cast is not inserted automatically. I'm also no expert with the type conversion infrastructure and don't really know why that worked previously but broke with that patch.

**Comment by youngar** [comment]
Thanks for figuring it out @maerhart!

**Comment by lattner** [comment]
Fantastic, great detective work!!

**Pull request merged**
