### PR TITLE
[FIRRTL][OMIR] Fix target instance path

### PR DESCRIPTION
**Pull request by prithayan**
This commit fixes the target instance path according to the Extract Test Code logic.

1. If any target absolute path refers to a signal inside the Design Under Test, 
then truncate the absolute path to be rooted at the DUT module.
2. Special case for `dutInstance` , it should always be relative to the test bench. 
(SFC implementation in TestHarnessOMPhase.scala)
3. Add test cases for the above

### CODE REVIEW

**Comment by mwachs5** [comment]
Generally this should happen "naturally" as a result of the splitting of code during ExtractTestCode (if ETC is not run, this should not happen). IN that case the new Circuit would have the DUT as the top, and thus the absolute paths that exist at that point would be rooted at the DUT by virtuie of the fact that they are in the DUT's circuit... 

Not sure if this explanation helps or changes this PR at all, just some insight into the semantics of this functionality

**Review by mwachs5 — CHANGES_REQUESTED** [review]
This seems like too specific a solution for the general problem

**Comment by prithayan** [comment]
> Generally this should happen "naturally" as a result of the splitting of firrtl circuit during ExtractTestCode (if ETC is not run, the paths would be rooted at the TestHarness level same as those NOT in the DUT). IN that case the new Circuit would have the DUT as the top, and thus the absolute paths that exist at that point would be rooted at the DUT by virtuie of the fact that they are in the DUT's circuit...
> 
> Not sure if this explanation helps or changes this PR at all, just some insight into the semantics of this functionality, it seems strange to have a boolean for `dutInstance`.
> 
> In SFC implementation a target which is deleted (e.g. something in the TestHarness, including the dutInstance itself, being deleted by ExtractTestCode) then it gets tracked as an OMFrozenTarget which remembers what it "used to be", until time to emit the OMIR.

Thanks @mwachs5 , the problem here is that, ETC happens much later in SV dialect. So, we emit the OMIR in `FIRRTL` dialect, but the ETC happens after lowering in the `SV` dialect.
So, we might have to make the `EmitOMIR` pass aware of the ETC logic.

**Comment by mwachs5** [comment]
I'm not sure at all how emitting the OMIR so early works since it's supposed to track the final locations of things...

**Comment by prithayan** [comment]
> I'm not sure at all how emitting the OMIR so early works since it's supposed to track the final locations of things...

@mwachs5 , MFC uses symbols to make sure the final names and locations of everything is synced up when printing the OMIR after `ExportVerilog`. 
And, even though the ETC pass in MFC runs much later, we can use the `MarkDUTAnnotation` annotation to fixup the expected target paths for the OMIR target. (as in this PR)
Also, It seems like we have to special case it for `dutInstance` which is what SFC does, `TestHarnessOMPhase.scala#L51`

**Comment by darthscsi** [comment]
> > I'm not sure at all how emitting the OMIR so early works since it's supposed to track the final locations of things...
> 
> @mwachs5 , MFC uses symbols to make sure the final names and locations of everything is synced up when printing the OMIR after `ExportVerilog`. And, even though the ETC pass in MFC runs much later, we can use the `MarkDUTAnnotation` annotation to fixup the expected target paths for the OMIR target. (as in this PR) Also, It seems like we have to special case it for `dutInstance` which is what SFC does, `TestHarnessOMPhase.scala#L51`

As prithayan mentions, omir isn't exactly emitted early in the pipeline, but it is generated.

ETC in SFC is a collection of different behaviors which have been split up differently here.  "ETC" in MFC only extracts verification code to new modules and binds them.  The restructuring of the output locations happens elsewhere.

**Review by darthscsi — APPROVED** [review]
This can go in, but a question I have is if you can just subtract the dut prefix from any tracked target which contains it (assuming for now only one dut).  so:
` ~FixPath|Fixpath/c:C/cd:D - ~Fixpath|Fixpath/c -> ~C|C/cd:D`
if the dut path is not a prefix, don't subtract.

**Pull request merged**
