### PR TITLE
[FIRRTL][IMCP] Fix handling of refsub, send/resolve, fields.

### PR DESCRIPTION
**Pull request by dtzSiFive**
* Recognize RefSubOp as "aggregate indexer".
* Compute and propagate via FieldRefs into inner (base) type for refs, restore behavior lost with FieldID rework/simplification.
* Treat ref send/resolve similarly to nodes in reasoning.

Put behavior under test.

RefSub test before this PR resulted in another undriven probe wire (cc #6076).

### CODE REVIEW

**Comment by dtzSiFive** [comment]
Should be NFC for non-probe types and operations, FWIW.

**Comment by dtzSiFive** [comment]
Note mostly-to-self: After this lands, can un-revert the Inliner change introducing wires-of-probes.

**Comment by dtzSiFive** [comment]
Other than adding `RefSubOp` to list of recognized aggregate indexer operations, this restores behavior to 1-2 weeks ago re:operating on base type of probes for tracking.

**Review by uenoku — APPROVED** [review]
LGTM!

**Pull request merged**
