### PR TITLE
[RTL] Add 'and' idompotent case for canonicalization.

### PR DESCRIPTION
**Pull request by cgyurgyik**

### CODE REVIEW

**Review by drom — APPROVED** [review]

**Comment by lattner** [comment]
Nice.  LGTM.  

While you're here (or as a follow-on) you might also want to handle the "and x, cst1, cst2" case (i.e., where the last operands are both constants).   I believe that the generic code will canonicalize "and cst1, x, cst2" to put both constants on the right already, so this should generalize nicely.  

These rewrites are all nicely recursive: it would be great to add a testcase showing that "and x, y, y, y, y" gets turned into "and x, y" and that the "c1, x, c2" case gets canonicalized as well.

Thank you for working on this!

**Review by lattner — APPROVED** [review]

**Review by drom — CHANGES_REQUESTED** [review]
does MLIR guaranty that all duplicates are on the back of the argument list?
Can we get `(..., x, y, x)` ?
or `(..., x, x, y)` ?
we need more test cases.

**Comment by lattner** [comment]
No, I don't think it will generally reassociate duplicates to the end, but we can make it reassociate duplicates to be next to each other.  That would be a straightforward canonicalization to add to the generic code I think.

**Comment by River707** [comment]
> No, I don't think it will generally reassociate duplicates to the end, but we can make it reassociate duplicates to be next to each other. That would be a straightforward canonicalization to add to the generic code I think. @River707 do you have any concerns with that?

No concerns, seems fine.

**Comment by stephenneuendorffer** [comment]
Constants will always get put at the end.  
It seems like even if duplicate inputs are adjacent, its still hard to write this as a rewrite rule.  Seems like maybe we want an Idempotent trait, which is handled with some common code for any idempotent operation.

**Comment by cgyurgyik** [comment]
So what is the best next step here? Should I write a few more tests as requested by @drom before you all move forward with a decision? Given I'm still brand new to MLIR/CIRCT, I will rely heavily on your guidance.

**Comment by lattner** [comment]
Oh, sorry about that.  There is one failing test, I'm not sure why - it looks like a straight build error:

```
In file included from /home/runner/work/circt/circt/lib/Dialect/RTL/Ops.cpp:612:
/home/runner/work/circt/circt/build_assert/include/circt/Dialect/RTL/RTL.cpp.inc:2470:12: error: no member named 'verifyFModuleOp' in the global namespace
  return ::verifyFModuleOp(*this);
         ~~^
```

@drom, is this a transient problem?  Do you know how to rerun tests?

Assuming the code builds, then I'm happy to land it.  If you'd like to get commit access so you can land your own patches, please read the [llvm developer policy](https://llvm.org/docs/DeveloperPolicy.html).

**Comment by cgyurgyik** [comment]
I believe that is a result of #76, but it seems to have been fixed since. I just need to rebase.

**Comment by lattner** [comment]
Cool, please do, then I'll be happy to land it

**Comment by cgyurgyik** [comment]
Are you talking about landing with LLVM? I do have access if that's what you mean.

**Comment by lattner** [comment]
Awesome, thanks!

**Comment by amaleewilson** [comment]
> 
> 
> > No, I don't think it will generally reassociate duplicates to the end, but we can make it reassociate duplicates to be next to each other. That would be a straightforward canonicalization to add to the generic code I think. @River707 do you have any concerns with that?
> 
> No concerns, seems fine.

Should we file an issue on Phabricator for this duplicate operands canonicalization / idempotent trait?

**Comment by lattner** [comment]
Yeah it would be great to file a tracking bug in bugzilla (llvm.org/bugs).  I think that @drom was interested in tackling this?   It looks like this should be handled in the `OperationFolder::tryToFold` method in `mlir/lib/Transforms/Utils/FoldUtils.cpp`. 
 Check somewhere near the call to `std::stable_partition`.

**Comment by drom** [comment]
filed here: https://bugs.llvm.org/show_bug.cgi?id=47639

**Pull request merged**
