### PR TITLE
Fix the lint steps in the GH workflow to compare against the target branch

### PR DESCRIPTION
**Pull request by teqdruid**
It was apparently comparing against the fork point. (Two different
meanings of the word 'base' I think.) As a result, it would pick up
differences in the target branch since the fork point! Users would have
to merge before the PR to avoid this.

### CODE REVIEW

**Comment by teqdruid** [comment]
This is good to go immediately after a review. Approving reviewer should hit the merge button on my behalf.

**Comment by lattner** [comment]
@stephenneuendorffer can you review this?  I'm not sure how this stuff works

**Comment by stephenneuendorffer** [comment]
I don't completely grok the code either.  @teqdruid Can you add some comments, please?

**Comment by teqdruid** [comment]
Sure. There's actually a number of formatting and unintuitive things in this workflow so I've documented and formatted it.

**Review by stephenneuendorffer — APPROVED** [review]
Thanks! Comments are very clear.

**Pull request merged**
