### PR TITLE
[ExportVerilog] Pass an Operation to print type instead of Location.

### PR DESCRIPTION
**Pull request by mikeurbach**
Previously, the location was used to emit any errors. By passing an
Operation pointer, we still have the ability to do that, but it opens
up other possibillities. Specifically, we can use the Operation as an
anchor to lookup symbols, which is looking like it will be necessary
in order to emit types that reference type declarations.

### CODE REVIEW

**Comment by mikeurbach** [comment]
This is a smaller refactor in anticipation of a larger change related to type declarations. If it isn't clear why I would want to do this, or what the larger change is about, I can share more about how the type declaration stuff is shaping up.

**Comment by teqdruid** [comment]
I understand why this may be desirable. Is it necessary for your typedef
emission or just useful?

Either way, these changes look great fine to me, but GitHub mobile web
doesn't show an approve button. Will click when I'm back at a desk.

**Comment by mikeurbach** [comment]
>  Is it necessary for your typedef emission or just useful?

It is necessary. I may be able to implement ExportVerilog support another way, but at some point we will have to resolve the reference to a symbol. This lets us do that as we encounter a type to print that references a declaration. I've just finished my the type referencing change that uses this, so let me make a PR and we can discuss the broader approach there...

**Comment by mikeurbach** [comment]
See the linked draft for more info. This may be moot depending on what we decide.

**Review by teqdruid — APPROVED** [review]

**Comment by lattner** [comment]
I don't really understand where you're going with this, but I have no objections to it, LGTM, thanks!

**Review by lattner — APPROVED** [review]

**Pull request merged**
