### PR TITLE
[StandardToHandshake] Handling affine load/store

### PR DESCRIPTION
**Pull request by kumasento**
This PR implements a fraction of #71 (which will be eventually discarded) that handles conversion from `affine.load` to `handshake.load`, and from `affine.store` to `handshake.store`. It contains only the simplest test case and the dependence analysis has not been implemented yet.

FYI @stephenneuendorffer

### CODE REVIEW

**Comment by stephenneuendorffer** [comment]
Feel free to factor out the dyn_cast -> isa fixes and commit them separately without review.

**Comment by kumasento** [comment]
> Feel free to factor out the dyn_cast -> isa fixes and commit them separately without review.

Sure thing, thanks @stephenneuendorffer ! Just that I don't have write access. Would you mind granting me one later?

**Comment by stephenneuendorffer** [comment]
> > Feel free to factor out the dyn_cast -> isa fixes and commit them separately without review.
> 
> Sure thing, thanks @stephenneuendorffer ! Just that I don't have write access. Would you mind granting me one later?

@lattner can help with that.

**Comment by kumasento** [comment]
Hi Steve @stephenneuendorffer I've factored out those `dyn_cast` to `isa` changes in another PR and merged that :) Would you mind taking a look at this one with some simple incremental changes towards supporting affine dialect? Thanks!

**Review by stephenneuendorffer — APPROVED** [review]
Looks good.

**Pull request merged**
