### PR TITLE
[Handshake] Support source ops in FIRRTL emission

### PR DESCRIPTION
**Pull request by mortbopet**

### CODE REVIEW

**Comment by mikeurbach** [comment]
LGTM. Do you have a test case? I'm curious how this is used.

**Comment by mortbopet** [comment]
Could add a sanity test, but i figured it such a narrow usecase that i didn't bother - i'll use it for comparing our circuits to [dynamatic](https://github.com/lana555/dynamatic) which uses sourceOps for its constants. Wrote a [parser](https://github.com/circt-hls/circt-hls/blob/main/tools/DynamaticParser/DynamaticParser.py) to facilitate from the format used there.

**Comment by mikeurbach** [comment]
Makes sense, but please add a sanity test. I think LLVM the policy is generally to cover any new additions with a test, even if it's just a simple one on the happy path.

**Comment by mortbopet** [comment]
Will do, sorry about that :+1:

**Pull request merged**
