### PR TITLE
[FIRRTL][IMDCE] Don't try to remove main module, don't warn if empty.

### PR DESCRIPTION
**Pull request by dtzSiFive**

### CODE REVIEW

**Review by uenoku — COMMENTED** [review]
I don't block but why do you want this change? Even though it's very unrealistic that top-level module is empty but it would cause some error in synthesis.

**Comment by dtzSiFive** [comment]
The warning is phrased to suggest that the problem is IMDCE can't do it's job (as effectively as it perhaps might, "cannot be removed") because of visibility, similar to when it can't delete because of an annotation or such.

That isn't the case for the main module -- it would be invalid IR if it deleted the main module, it can't be removed regardless of whether it's empty.

Sounds like we want a warning diagnostic for when the main module ends up being empty (by this point, if not because of this pass, possibly input was empty?), phrased appropriately for "hey FYI your design is empty, either because you wrote it that way or because we optimized out what you had, hope that's expected" / "public module is empty, is this expected?" ?

I was motivated by testing some optimization pass that worked "too well" and caused this diagnostic to be printed for a lot of our tests, and because of the above reasoning it seemed it wasn't quite right as-is.  Don't feel strongly, but maybe there's something to touchup here.  WDYT?

**Review by uenoku — APPROVED** [review]
Thanks! I don't have strong opinions and either but your exploration does sound reasonable to me! LGTM

**Comment by dtzSiFive** [comment]
Okay, let's run with this for now.  Thanks!

**Pull request merged**
