### PR TITLE
[Arc] LowerState: fix memory read materialization

### PR DESCRIPTION
**Pull request by zyedidia**
Applies @maerhart's fix for LowerState memory read materialization, and uses a comb mux to lower memory read ports instead of control flow (for data-flow conditions it's best to use Mux to avoid problems with backends that might have worse performance with control flow, and a later pass can transform muxes into SCF blocks if desired).

@fabianschuiki

### CODE REVIEW

**Review by fabianschuiki — APPROVED** [review]
LGTM! Thanks for PRing the fix :slightly_smiling_face:

**Comment by maerhart** [comment]
We should add regression tests for this fix.

**Comment by zyedidia** [comment]
Sounds good, I've added a regression test that is reduced from Rocket.

**Comment by fabianschuiki** [comment]
Thanks a lot! Merging this.

**Pull request merged**
