### PR TITLE
[README] Add link to the dialect diagram

### PR DESCRIPTION
**Pull request by fabianschuiki**
* Add a link to the dialect diagram on draw.io / diagrams.net, prepared by @mikeurbach and @fabianschuiki

### CODE REVIEW

**Comment by teqdruid** [comment]
Why not commit the diagram itself?

**Comment by fabianschuiki** [comment]
> Why not commit the diagram itself?

That would also be possible. The diagram is an XML, so for ease of use it might be worthwhile to then commit the generated SVG/PNG as well. There's also an offline version of draw.io (uses Electron AFAIK) which could be used to update the SVG/PNG as part of a Makefile. The drawback of committing the XML is that editing becomes more cumbersome (upload to draw.io, edit, download into the repo, commit); but it would make it part of the git history. I'm torn… what do others think?

**Comment by teqdruid** [comment]
The disadvantage of an external link is that it can be moved or deleted.

**Comment by fabianschuiki** [comment]
> The disadvantage of an external link is that it can be moved or deleted.

Excellent point.

**Comment by mikeurbach** [comment]
I'm definitely in favor of having a diagram as part of the official documentation.

I think having the source of truth in the repo would be best. I've only used draw.io online, but I can imagine a workflow with the desktop version that just opens/saves an xml in the repo and exports to overwrite a svg/png in the repo.

More broadly, is this everyone's preferred tool for diagram editing? I like draw.io well enough but there are other options. For example, we could use a dot file and graphviz to achieve a similar result.

**Comment by lattner** [comment]
I'd recommend checking in the diagram source and a rendered version of it both into circt/docs.  Even better if there is a shell script that regenerates the output in circt/utils :-)

**Comment by fabianschuiki** [comment]
Done! Added `docs/dialects.{drawio,png,svg}`, and `utils/update-docs-dialects.sh` regenerates the renders. Also updated the link in the README.

Do we want to include the diagram in the README somewhere, or is that too cluttered and distracting?

**Comment by teqdruid** [comment]
I think it would make a good addition to the overview in the README.

**Review by teqdruid — APPROVED** [review]

**Comment by fabianschuiki** [comment]
> I think it would make a good addition to the overview in the README.

Done; see here for a proper rendering: https://github.com/llvm/circt/blob/975a06f3d835b8e3e6022ae15ad88859223d5531/README.md

**Review by teqdruid — APPROVED** [review]

**Comment by mikeurbach** [comment]
Sweet!

**Pull request merged**
