### PR TITLE
[CI] Add macosx_arm64 python wheel

### PR DESCRIPTION
**Pull request by leonardt**
See https://github.com/llvm/circt/issues/6153

@mikeurbach is there a way for me to manually trigger a run of this action to test? Otherwise maybe I can have you do it for me.

### CODE REVIEW

**Comment by mikeurbach** [comment]
We don't support triggering builds from forks, which is sort of best practice so random folks can't fork the repo and run nefarious code within the CI environment. I'll push this branch to the main repo and trigger a run of CI.

**Comment by mikeurbach** [comment]
Testing branch added here: https://github.com/llvm/circt/compare/mikeurbach/test-macos-wheel?expand=1

CI running here: https://github.com/llvm/circt/actions/runs/6278965921

**Comment by mikeurbach** [comment]
The cibuildwheel seems to fail: https://github.com/llvm/circt/actions/runs/6278965921/job/17053772036#step:6:14

Do we need something else to support `cp38-macosx_arm64`? In the cibuildwheel configuration, I see macos is selected, but it's pointing to the x86 architecture: https://github.com/llvm/circt/actions/runs/6278965921/job/17053772036#step:6:23

Maybe we need something like this for these?

```
- os: [macos-latest, ARM64]
```

I'm looking at these docs: https://github.com/llvm/circt/actions/runs/6278965921/job/17053772036#step:6:23

**Comment by makslevental** [comment]
The way that I do this is by settings `CIBW_ARCHS=arm64` and `CIBW_BUILD=cp38-*`.

**Pull request closed without merging**
