### PR TITLE
[PyCDE] Start of proper documentation

### PR DESCRIPTION
**Pull request by teqdruid**
Adds some updated markdown docs and some basic examples. Not complete, but a start.

### CODE REVIEW

**Comment by teqdruid** [comment]
I'm hoping the website publishing pipeline will like this.

Ideally we'd get this stuff on readthedocs.io, but setting that up is more complicated than they make it seem.

**Review by mikeurbach — APPROVED** [review]
+1 for updating the docs, the content looks good to me in general.

Regarding how the documentation generator will pick this up... I'm not totally sure how this works, but looking at how the CommandGuide and Dialects directories work, I think if you want to override the index page, it might need to be in _index.md (i.e. just move what you have in index.md to _index.md): https://github.com/llvm/circt/tree/main/docs/Dialects.

It looks like this logic is here: https://github.com/llvm/circt-www/blob/eeeff4504c51f84ea6299d14e290b3eda53a84ea/copy_docs.sh.

**Comment by teqdruid** [comment]
Thanks @mikeurbach. Made the name change you suggested.

@drom Is [this the GH workflow](https://github.com/llvm/circt-www/actions/workflows/main.yml) which does the publishing? Do the failures mean that the website hasn't been updated in 2 months?

**Comment by teqdruid** [comment]
Yeah, looks like the documentation publishing pipeline is broke.

**Pull request merged**
