### PR TITLE
[Physical] New dialect for physical design

### PR DESCRIPTION
**Pull request by teqdruid**
From the dialect description:

"The `physical` design dialect houses stuff applicable to physical design -- placement and routing (PnR). By constraining the PnR tool, we make the tools job easier leading to more predictable outcomes. If done well, those outcomes improve on what the PnR engine does unconstrained."

This will initially contain only a `Location` attribute to designate placement of a specific operation. It will also be used to create TCL scripts to inform the tool as to where a thing should be placed on the device.

This PR is boilerplate to create the dialect. We can also bikeshed on the dialect name here. I won't merge it until the aforementioned attribute is ready to go to avoid having an empty dialect sitting around (like the `seq` dialect).

### CODE REVIEW

**Comment by lattner** [comment]
Superficial comment without having looked at the patch: I would recommend picking a different and more specific name for this dialect instead of squatting on "physical" or "pd".  Maybe something like "jpd" for John's physical design or something.  

We should generally start things outside of the core namespace and pull them into global concepts like this after a bunch of discussion and iteration.

**Comment by teqdruid** [comment]
That makes the naming problem easier.

**Comment by teqdruid** [comment]
Should I just create a "MSFT" dialect for stuff I (and hopefully my colleagues in the future) want/need to do to support Microsoft projects but haven't been thoroughly discussed?

**Comment by lattner** [comment]
Sure.  Though msft may have its own issues if a colleague in a different group gets interesting in circt ;-)

**Comment by teqdruid** [comment]
At least they'd have a pointer to me!

**Pull request closed without merging**
