### PR TITLE
[HW] Fix bug with unknown location

### PR DESCRIPTION
**Pull request by leonardt**
Fixes https://github.com/llvm/circt/issues/6388

**NOTE**: This patch was originally provided by @fzi-hielscher (see referenced issue).  I'm submitting this via PR in hopes to accelerate integration as it fixes a blocking bug.

### CODE REVIEW

**Comment by leonardt** [comment]
Is there a place I can easily add a test to check compiling the MLIR code provided in the issue?

**Comment by fzi-hielscher** [comment]
Sorry for the delay. We discussed this at the end of last week's zoom meeting and there were some concerns left.

The test should most likely go into "test/Dialect/HW/locations.mlir". But if you add it, you'll notice that the unknown locations will (incorrectly) still be missing from the debug printout. As far as I can see this is because `printModuleSignatureNew` grabs the location array directly instead of using the patched getter. I'm not sure whether patching that in the same way is the right thing to do.

IMHO we can merge this PR now to at least stop it from crashing. But it will need revisiting to fix the printer, depending on whether we go forward with stripping the unknown locations.

**Review by uenoku — APPROVED** [review]
This looks good to me.

**Comment by fzi-hielscher** [comment]
Thanks, @uenoku. I'm going to merge this and open a new issue for the printer.

**Pull request merged**
