### PR TITLE
[FIRRTL][Annotation] Support port annotations for MemOp

### PR DESCRIPTION
**Pull request by hanchenye**
Similar to `InstanceOp`, this patch supports multi-port annotations for `MemOp`. Several methods that can be shared, such as `parse/printElidePortAnnotations`, are factored out.

### CODE REVIEW

**Comment by lattner** [comment]
Is this still a draft or ready for review?

**Comment by hanchenye** [comment]
@lattner This is still a draft!

**Comment by hanchenye** [comment]
This PR should be ready for review.

The complicated stuffs of this PR comes from that if the data type of `MemOp` is an aggregate type, we allows to annotate the sub-field/sub-index of the data field. For example, we can annotate things like `~Foo|Foo>mem.r.data.baz`, `~Foo|Foo>mem.w.data.qux`, etc. Then in the LowerTypes pass, we will need to convert these annotation targets to `~Foo|Foo>mem_baz.r.data` and `~Foo|Foo>mem_qux.w.data` because the data field is flattened now. This makes the annotation lowering of `MemOp` quite different to other operations.

I'm wondering whether we have users of this type of annotations. If not, perhaps we can just disable `~Foo|Foo>mem.r.data.baz`-like annotations and only allow `~Foo|Foo>mem.r.data`, `~Foo|Foo>mem.r.en`, etc., which will simplify quite some logic.

**Review by lattner — APPROVED** [review]
really nice!  great work

**Pull request merged**
