### PR TITLE
LLVM bump

### PR DESCRIPTION
**Pull request by darthscsi**
Blocked on #6661 , #6660, #6659, #6658

### CODE REVIEW

**Comment by mikeurbach** [comment]
More blockers: https://github.com/llvm/circt/issues/6667, https://github.com/llvm/circt/issues/6668, https://github.com/llvm/circt/issues/6669

**Comment by mikeurbach** [comment]
Since most of the linked issues are resolved, I've merged main and pushed it here. Just waiting on #6658.

**Comment by mikeurbach** [comment]
@teqdruid looked into the Ibis situation, and it's complicated and no one has time to work on it, so he recommended to XFAIL those tests so we can move forward, which I've done on this PR.

**Review by seldridge — APPROVED** [review]
LGTM

Thanks for coordinating with the Ibis folks on the (now) XFAIL'd tests.

**Review by teqdruid — APPROVED** [review]
Thanks!

**Pull request merged**
