### PR TITLE
[ExportVerilog] Remove unused function

### PR DESCRIPTION
**Pull request by youngar**

### CODE REVIEW

**Review by fabianschuiki — APPROVED** [review]
LGTM

**Review by dtzSiFive — APPROVED** [review]
LGTM thanks!

**Review by seldridge — APPROVED** [review]
Nice. 

Feel free to land stuff like this without review.

**Review by uenoku — APPROVED** [review]
Thanks! Right now `getSymOpName` is doing what `getDeclarationName` previously did. I admit `getSymOpName` is abused a lot for managin names so it's would be necessary to clean up in the future 🙈

**Pull request merged**
