### PR TITLE
[CI] Add macos wheels

### PR DESCRIPTION
**Pull request by rsetaluri**

### CODE REVIEW

**Comment by rsetaluri** [comment]
> This seems to be working here: https://github.com/llvm/circt/actions/runs/5060542988, but if I look at other runs (https://github.com/llvm/circt/actions/runs/5009139934), I see errors. So it looks like there are transient errors possible...

Digging into it, I see actual C++ build errors: https://github.com/llvm/circt/actions/runs/5009139934/jobs/8977750389#step:6:2362. Doesn't seem like anything to do with macos/python/buildwheel. Any idea why this comes up? It also seems non-deterministic, i.e. it works sometimes.

**Comment by mikeurbach** [comment]
This error looks like a basic dependency issue, I can take a look at it or @mortbopet , @RamirezLucas , and @Dinistro might have an idea, since it is on the conversion to handshake. Probably this is just exposed by this environment for some reason.

In general looks great, thanks for trying this out and testing it!

**Comment by mikeurbach** [comment]
Looks like this line is just missing in StandardToHandshake: https://github.com/llvm/circt/blob/6bc7e7bca1eb7e07ee2b0457587972c11f8c49b6/lib/Conversion/ExportVerilog/CMakeLists.txt#L12-L13. I'll fix that really quick and if you rebase/merge main you should be able to test successfully.

**Comment by mikeurbach** [comment]
Should be fixed after https://github.com/llvm/circt/commit/9d924a6807abf91c293ba6405459dc06151e795c.

**Comment by rsetaluri** [comment]
Thanks for the prompt action @mikeurbach ! Rebased. See https://github.com/llvm/circt/actions/runs/5062704176 for the latest run.

**Comment by rsetaluri** [comment]
@mikeurbach also, once this is in, what is the path to making a firtool release to get the packages to pypi?

**Comment by mikeurbach** [comment]
We have regular firtool releases created weekly by folks from SiFive, so this will be included in the next release and the wheels pushed to PyPI when it is cut.

**Pull request merged**
