### PR TITLE
[Python] Use the "private namespace" approach for mlir dep

### LINKED ISSUE #3475: [Python] Use the "private namespace" approach to include the upstream `mlir` packages within the `circt` package.
This was discussed on Discord nearly a year ago: https://discord.com/channels/636084430946959380/742572728787402763/873039553517215854. We just never got around to implementing it.

The Discord points out a patch where IREE adopts a similar approach: https://github.com/google/iree/pull/6668/files.

For us, I think this boils down to a couple CMake changes.

1. adjusting the INSTALL_COMPONENT, INSTALL_DESTINATION, and OUTPUT_DIRECTORY of our CAPI library: https://github.com/llvm/circt/blob/2715c2dde8aee1dd8ea8f83c332e0a9b8b1824a8/lib/Bindings/Python/CMakeLists.txt#L132
2. remove the CIRCTMLIRPythonModules target completely: https://github.com/llvm/circt/blob/2715c2dde8aee1dd8ea8f83c332e0a9b8b1824a8/lib/Bindings/Python/CMakeLists.txt#L149
3. add the `MLIRPythonSources.Core` target under DECLARED_SOURCES for CIRCT Python modules: https://github.com/llvm/circt/blob/2715c2dde8aee1dd8ea8f83c332e0a9b8b1824a8/lib/Bindings/Python/CMakeLists.txt#L162

In essence, this lets us get replace `import mlir.ir` with `import circt.ir`. We only depend on the builtin dialect from upstream, but that woudl also become `circt.dialects.builtin`.

Taking control of these packages within the `circt` package will give us more flexibility and control. One specific use-case I have in mind, will come after https://reviews.llvm.org/D128593 is incorporated. This gives the ability for the `ir.Context` to be configured in a site-specific way. We could customize it so that our dialects and passes automatically come registered, which is something we have sought for a while.

I think technically we could implement that customization without doing the change in this issue, but having `import mlir.ir.Context` import a CIRCT-specific context seems to violate the principle of least suprise. So I'm suggesting we do this change, and update users to `import circt.ir.Context`. This could be done before or after the above patch is incorporated, and seems like a generally good thing to do that we just never got to. It will be somewhat painful to find and replace all users of CIRCT's Python bindings to import the relevant packages from under `circt` instead of `mlir`, but that should be a mechanical, one-time change.

@teqdruid what do you think about this? It's not strictly necessary, but I believe this is the expected way for downstreams to do things.

### PR DESCRIPTION
**Pull request by teqdruid**
Closes #3475. Also switch to relative imports in the hope that other projects (ie PyCDE) can include the CIRCT bindings privately.

### CODE REVIEW

**Comment by teqdruid** [comment]
This seems to create the proper directory structure:

```
$ tree -h -I __pycache__ ~/internal_circt_build/tools/circt/python_packages/
/home/jodemme/internal_circt_build/tools/circt/python_packages/
└── [  10]  circt_core
    └── [ 138]  circt
        ├── [  85]  __init__.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/__init__.py
        ├── [ 258]  _mlir_libs
        │   ├── [  92]  __init__.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/llvm/mlir/python/mlir/_mlir_libs/__init__.py
        │   ├── [9.0M]  _circt.cpython-39-x86_64-linux-gnu.so
        │   ├── [  66]  _mlir
        │   │   ├── [  99]  __init__.pyi -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/llvm/mlir/python/mlir/_mlir_libs/_mlir/__init__.pyi
        │   │   ├── [  93]  ir.pyi -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/llvm/mlir/python/mlir/_mlir_libs/_mlir/ir.pyi
        │   │   └── [ 102]  passmanager.pyi -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/llvm/mlir/python/mlir/_mlir_libs/_mlir/passmanager.pyi
        │   ├── [ 26M]  _mlir.cpython-39-x86_64-linux-gnu.so
        │   └── [293M]  libCIRCTBindingsPythonCAPI.so
        ├── [ 628]  dialects
        │   ├── [  99]  _comb_ops_ext.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/_comb_ops_ext.py
        │   ├── [  98]  _comb_ops_gen.py -> /home/jodemme/internal_circt_build/tools/circt/lib/Bindings/Python/circt/dialects/_comb_ops_gen.py
        │   ├── [  98]  _esi_ops_ext.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/_esi_ops_ext.py
        │   ├── [  97]  _esi_ops_gen.py -> /home/jodemme/internal_circt_build/tools/circt/lib/Bindings/Python/circt/dialects/_esi_ops_gen.py
        │   ├── [  98]  _fsm_ops_ext.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/_fsm_ops_ext.py
        │   ├── [  97]  _fsm_ops_gen.py -> /home/jodemme/internal_circt_build/tools/circt/lib/Bindings/Python/circt/dialects/_fsm_ops_gen.py
        │   ├── [  97]  _hw_ops_ext.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/_hw_ops_ext.py
        │   ├── [  96]  _hw_ops_gen.py -> /home/jodemme/internal_circt_build/tools/circt/lib/Bindings/Python/circt/dialects/_hw_ops_gen.py
        │   ├── [ 102]  _hwarith_ops_ext.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/_hwarith_ops_ext.py
        │   ├── [ 101]  _hwarith_ops_gen.py -> /home/jodemme/internal_circt_build/tools/circt/lib/Bindings/Python/circt/dialects/_hwarith_ops_gen.py
        │   ├── [  99]  _msft_ops_ext.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/_msft_ops_ext.py
        │   ├── [  98]  _msft_ops_gen.py -> /home/jodemme/internal_circt_build/tools/circt/lib/Bindings/Python/circt/dialects/_msft_ops_gen.py
        │   ├── [  93]  _ods_common.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/llvm/mlir/python/mlir/dialects/_ods_common.py
        │   ├── [  98]  _seq_ops_ext.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/_seq_ops_ext.py
        │   ├── [  97]  _seq_ops_gen.py -> /home/jodemme/internal_circt_build/tools/circt/lib/Bindings/Python/circt/dialects/_seq_ops_gen.py
        │   ├── [  97]  _sv_ops_ext.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/_sv_ops_ext.py
        │   ├── [  96]  _sv_ops_gen.py -> /home/jodemme/internal_circt_build/tools/circt/lib/Bindings/Python/circt/dialects/_sv_ops_gen.py
        │   ├── [  90]  comb.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/comb.py
        │   ├── [  89]  esi.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/esi.py
        │   ├── [  89]  fsm.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/fsm.py
        │   ├── [  88]  hw.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/hw.py
        │   ├── [  93]  hwarith.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/hwarith.py
        │   ├── [  90]  msft.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/msft.py
        │   ├── [  89]  seq.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/seq.py
        │   └── [  88]  sv.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/dialects/sv.py
        ├── [  75]  ir.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/llvm/mlir/python/mlir/ir.py
        ├── [  84]  passmanager.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/llvm/mlir/python/mlir/passmanager.py
        └── [  84]  support.py -> /home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/lib/Bindings/Python/circt/support.py
```

But when I run `python3.9 integration_test/Bindings/Python/import.py` I get:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ModuleNotFoundError: No module named 'mlir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jodemme/FPGAToolsAndCompilers/CIRCT/circt/integration_test/Bindings/Python/import.py", line 4, in <module>
    import circt
  File "/home/jodemme/internal_circt_build/tools/circt/python_packages/circt_core/circt/__init__.py", line 6, in <module>
    from ._mlir_libs._circt import *
ImportError: initialization failed
```

This implies to me that somewhere in the pybind11 code something is trying to `import mlir`. But I can't find where.

**Comment by teqdruid** [comment]
Figured it out. I think this is ready to go. Haven't tested wheel builds though.

**Review by mikeurbach — APPROVED** [review]
Thanks for doing this. This looks good to me!

**Comment by teqdruid** [comment]
The wheel build succeeded. Thanks for the review Mike!

**Pull request merged**
