### PR TITLE
[HW] Add top module inference to InstanceGraph

### PR DESCRIPTION
**Pull request by mortbopet**
This commit adds support for inferring a top-level module in an InstanceGraph.
The implementation is based on a topological sort of the instance graph. Through this, error messages will be generated in case of a cycle in the instance graph or when multiple candidate top modules are found.

### CODE REVIEW

**Review by mikeurbach — APPROVED** [review]
I think this looks good to me, thanks for the addition.

**Comment by teqdruid** [comment]
I haven't reviewed, but the reason I don't use this class is PyCDE can create multiple top modules (which get instantiated in multiple places in the SystemVerilog design). Can this class be made to facilitate that use-case?

**Comment by mortbopet** [comment]
> Can this class be made to facilitate that use-case?

Definitely! I was hesitating whether or not to define multiple top modules as an error. Right now it is the case, but if there's a use-case then I'm in favor of allowing it - and then letting downstream users determine what to do when multiple top modules are found.

**Comment by teqdruid** [comment]
Excellent! If that functionality is added I could ditch my janky partial ordering and instantiation code.

**Comment by mikeurbach** [comment]
Actually, yes, I think updating the api to return top-module(s) (plural) would be great. I forgot about this point during review, but supporting multiple tops is something I am trying to remember to account for moving forward.

**Comment by youngar** [comment]
I'm not totally sure I understand this change, but I have some questions:
1. Shouldn't the algorithm just be, if a module has no instances of it then it must be a top level module? See [here](https://github.com/llvm/circt/blob/main/include/circt/Dialect/HW/InstanceGraphBase.h#L103).
2. Modules have visibility and can be private or public.  Isn't a top-level module actually anything that is marked public?
3. The instance graph can be updated on the fly and we aren't invalidating the cached result anywhere, maybe we should just stop caching the result?

**Pull request merged**
