### PR TITLE
[Handshake] Fix canonicalizer not going through rewriter for RAUW.

### PR DESCRIPTION
**Pull request by dtzSiFive**
Detected by -DMLIR_ENABLE_EXPENSIVE_PATTERN_API_CHECKS=ON.

cc #7047.

### CODE REVIEW

**Review by teqdruid — COMMENTED** [review]
Is `modifyOpInPlace` not a valid thing to use anymore? It's generally used for good reason. There may be some subtlety here that necessitates it.

**Comment by dtzSiFive** [comment]
> Is `modifyOpInPlace` not a valid thing to use anymore? It's generally used for good reason. There may be some subtlety here that necessitates it.

Thanks for taking a critical look here!

The RAUW's are updating ops using `parentForkOp` results, not that op itself, which is what I think was going wrong and addressed here.  Possibly could keep it and also use rewriter for the RAUW from within? 🤔

**Comment by teqdruid** [comment]
I'm not sure. Did Morten write this code? If so, the conservative thing to do is to wait for him to come back from vacation and get his review. Should be back in two or three weeks, but this doesn't seem urgent... yes?

**Comment by dtzSiFive** [comment]
> I'm not sure. Did Morten write this code? If so, the conservative thing to do is to wait for him to come back from vacation and get his review. Should be back in two or three weeks, but this doesn't seem urgent... yes?

Not urgent AFAIK.  Sounds good to me, thanks!

**Review by mortbopet — APPROVED** [review]

**Pull request merged**
