### PR TITLE
[Calyx to FSM]Fix the bug when calyx multi-component design lower to fsm.

### PR DESCRIPTION
**Pull request by linuxlonelyeagle**
I found this problem while learning circt during this time, and I have solved it.You can see it [here](https://github.com/llvm/circt/issues/5296).The names of the state machines generated in the calyx-to-fsm pass are all called control. This leads to a problem when designing with multiple components, where components may instantiate the state machines of other components.

### CODE REVIEW

**Review by mikeurbach — APPROVED** [review]
Nice, thanks for working on this! I think this solution makes sense. @mortbopet I believe you initially implemented this. Any concerns?

**Review by mortbopet — APPROVED** [review]
Makes sense to me, thank you for finding and fixing the bug!

**Comment by linuxlonelyeagle** [comment]
@mikeurbach  Thank you!I remember that you answered my question last year.:smiley:

**Comment by linuxlonelyeagle** [comment]
@mikeurbach  @mortbopet I should modify the test case again.

**Comment by mikeurbach** [comment]
@linuxlonelyeagle looks like some tests will need to be updated. For example, this name will need to be updated: https://github.com/llvm/circt/blob/2a6ecf77b58cbec87eec6d60274078f4a3de2957/test/Conversion/CalyxToFSM/lower-seq.mlir#L3

You can run the tests with `ninja check-circt` to try it out.

**Comment by linuxlonelyeagle** [comment]
> @linuxlonelyeagle looks like some tests will need to be updated. For example, this name will need to be updated:
> 
> https://github.com/llvm/circt/blob/2a6ecf77b58cbec87eec6d60274078f4a3de2957/test/Conversion/CalyxToFSM/lower-seq.mlir#L3
> 
> You can run the tests with `ninja check-circt` to try it out.

Thank you.

**Comment by linuxlonelyeagle** [comment]
I have modified the test and run `ninja check-circt` on my own machine.I also tested `ninja check-circt-integration`.There are two error, but this error was already there,not related to the patch.You can view the results below.
```
Failed Tests (2):
  CIRCT :: Dialect/FSM/variable/top.mlir
  CIRCT :: ESI/system/basic.mlir


Testing Time: 5.65s
  Unsupported: 44
  Passed     : 33
  Failed     :  2
```

**Comment by mikeurbach** [comment]
Great. Assuming the tests pass in CI I will merge it.

**Comment by rachitnigam** [comment]
Awesome, thanks for fixing this @linuxlonelyeagle

**Pull request merged**
