### PR TITLE
[Python][CI] Fix formatting check by using an image with toml.

### PR DESCRIPTION
**Pull request by mikeurbach**
This is required by the yapf tool we use to enforce formatting.

### CODE REVIEW

**Review by teqdruid — APPROVED** [review]
lgtm

**Comment by mikeurbach** [comment]
Thanks, just want to ensure the fix works by failing on the most recent commit, then will merge.

**Comment by mikeurbach** [comment]
Including format updates in this PR too, to a) fix them, and b) check the formatting gate accepts them.

**Comment by mikeurbach** [comment]
Back to this:
```
/__w/_temp/06aa5828-8b96-4b2b-806b-12820d8a37b7.sh: 2: [: frontends/PyCDE/src/pycde/instance.py: unexpected operator
```

**Pull request merged**
