### PR TITLE
[CI] Strip md5sum filename when building cache key

### PR DESCRIPTION
**Pull request by seldridge**
Testing CI fixes.

### CODE REVIEW

**Comment by youngar** [comment]
The CI is off to a good start, its rebuilding LLVM right now.

**Comment by seldridge** [comment]
This change is probably unnecessary. I'm curious if the LLVM rebuild gets things working, though.

**Comment by fabianschuiki** [comment]
:+1: for `awk`

**Comment by fabianschuiki** [comment]
The breakage in CI now seems to be realted to what @teqdruid observes in #1052, where a debug build of LLVM uncovers a bunch of test failures.

**Comment by seldridge** [comment]
Closing as this was just a test to try to fix CI (which was eventually fixed differently).

**Pull request closed without merging**
