### PR TITLE
[CI] Unshallow llvm to include past 30 days, so have revs to bisect over.

### LINKED ISSUE #4566: Track LLVM changes git bisect broken
The git bisect command in summarize changes is claiming that a relatively recent commit broke us, when an older commit actually did.

https://github.com/llvm/circt/actions/runs/3966597034/jobs/6797590060 points the finger at https://github.com/llvm/llvm-project/tree/0e13ccc69cf23b1d4a84d59d882717c6b2d5759e which is far newer by ~10 days than the tracking build has failed.

### PR DESCRIPTION
**Pull request by dtzSiFive**
Couldn't easily determine how to selectively fetch the desired range, so rely on this running regularly and grab based on time.

Fixes #4566.

### CODE REVIEW

**Comment by dtzSiFive** [comment]
(2 days because didn't chase down how running near midnight might impact the range)

**Review by teqdruid — APPROVED** [review]
I don't think 2 days is sufficient seeing as this runs nightly and I wouldn't want to look at the build history to see the commit which broke us. Why not increase it to like 30 days? That would avoid the _vast_ majority of llvm commits, which is really the intent of shallow fetches, yes?

**Comment by dtzSiFive** [comment]
Oh I was just thinking about this entirely wrong, thank you @teqdruid .  Whoops.  I was thinking "2 days is enough to cover between runs" but obviously that's not the distance between the current revision and what's on master now (nor even the range covering the failure point, similarly).

Totally, let's just do like 30 days and ship it.  Good call, thanks!

**Comment by dtzSiFive** [comment]
(or just don't worry about the shallow, but let's try 30 for now.  Thanks!)

**Pull request merged**
