### PR TITLE
bump llvm submodule to tip of main (103fa3250c46)

### PR DESCRIPTION
**Pull request by mwachs5**
This is also doing a simple find-and-replace due to https://github.com/llvm/llvm-project/pull/78260

### CODE REVIEW

**Comment by mwachs5** [comment]
This is failing with:
```
/__w/circt/circt/lib/Conversion/AffineToLoopSchedule/AffineToLoopSchedule.cpp:219:14: error: no member named 'updateRootInPlace' in 'mlir::ConversionPatternRewriter'
    rewriter.updateRootInPlace(op, [&]() {
    ~~~~~~~~ ^
```

Any suggestions?

**Comment by mwachs5** [comment]
looks like maybe I just need to use the new `modifyOpInPlace` name https://github.com/llvm/llvm-project/pull/78260

**Comment by mwachs5** [comment]
This is now failing due to apparent upstream support for arithmetic overflow flags:

```
/__w/circt/circt/test/Transforms/map-arith-to-comb.mlir:6:11: error: CHECK: expected string not found in input
// CHECK: %[[VAL_3:.*]] = comb.add %[[VAL_0]], %[[VAL_1]] : i32
          ^
<stdin>:2:65: note: scanning from here
 hw.module @foo(in %arg0 : i32, in %arg1 : i32, in %arg2 : i1) {
                                                                ^
<stdin>:2:65: note: with "VAL_0" equal to "arg0"
 hw.module @foo(in %arg0 : i32, in %arg1 : i32, in %arg2 : i1) {
                                                                ^
<stdin>:2:65: note: with "VAL_1" equal to "arg1"
 hw.module @foo(in %arg0 : i32, in %arg1 : i32, in %arg2 : i1) {
                                                                ^
<stdin>:3:2: note: possible intended match here
 %0 = comb.add %arg0, %arg1 {overflowFlags = #arith.overflow<none>} : i32
 ^

Input file: <stdin>
Check file: /__w/circt/circt/test/Transforms/map-arith-to-comb.mlir

-dump-input=help explains the following input dump.

Input was:
<<<<<<
           1: module { 
           2:  hw.module @foo(in %arg0 : i32, in %arg1 : i32, in %arg2 : i1) { 
check:6'0                                                                     X error: no match found
check:6'1                                                                       with "VAL_0" equal to "arg0"
check:6'2                                                                       with "VAL_1" equal to "arg1"
           3:  %0 = comb.add %arg0, %arg1 {overflowFlags = #arith.overflow<none>} : i32 
check:6'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:6'3      ?                                                                         possible intended match
           4:  %1 = comb.sub %arg0, %arg1 {overflowFlags = #arith.overflow<none>} : i32 
check:6'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           5:  %2 = comb.mul %arg0, %arg1 {overflowFlags = #arith.overflow<none>} : i32 
check:6'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mwachs5** [comment]
another issue:

**Review by darthscsi — APPROVED** [review]
LGTM

**Comment by mwachs5** [comment]
Can someone merge? I do not have the permissions to do so

**Review by dtzSiFive — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
