### PR TITLE
[llvm] Update submodule to latest

### PR DESCRIPTION
**Pull request by teqdruid**
This upgrade is gonna take some digging. I got it to compile but it fails a bunch of tests. I managed to fix several.

Updated list:
```
Failed Tests (1):
  CIRCT :: Dialect/SV/hw-cleanup.mlir
```

On the upside, none of the integration tests fail!

### CODE REVIEW

**Comment by teqdruid** [comment]
On the LLHD tests: they all appear to be failing with something along the lines of:

```
Command Output (stderr):
--
loc("/home/jodemme/circt/test/Dialect/LLHD/Simulator/sim_simple.mlir":14:1): error: 'llvm.call' op calling function with void result must not produce values
loc("/home/jodemme/circt/test/Dialect/LLHD/Simulator/sim_simple.mlir":20:3): error: 'llvm.call' op calling function with void result must not produce values
failed to apply the MLIR passes
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /home/jodemme/circt_build/bin/FileCheck /home/jodemme/circt/test/Dialect/LLHD/Simulator/sim_simple.mlir
```

@fabianschuiki Could you look into this?

**Comment by teqdruid** [comment]
Looks like a lot of this is due to MLIR starting to count `builtin` as a dialect which happens to be auto-loaded. A few more down.

**Comment by teqdruid** [comment]
@lattner Could you or a delegate (@darthscsi seems to have the second most fingers in HWCleanup.cpp based on git blame) look into `hw-cleanup.mlir`? The cleanup pass doesn't seem be running at all -- AFAICT none of the expected transforms are occurring and it's just a pass-through.

```
FAIL: CIRCT :: Dialect/SV/hw-cleanup.mlir (6 of 12)
******************** TEST 'CIRCT :: Dialect/SV/hw-cleanup.mlir' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/jodemme/circt_build/bin/circt-opt -hw-cleanup /home/jodemme/circt/test/Dialect/SV/hw-cleanup.mlir | /home/jodemme/circt_build/bin/FileCheck /home/jodemme/circt/test/Dialect/SV/hw-cleanup.mlir
--
Exit Code: 1

Command Output (stderr):
--
/home/jodemme/circt/test/Dialect/SV/hw-cleanup.mlir:4:15: error: CHECK-NEXT: is not on the line after the previous match
//CHECK-NEXT: sv.initial {
              ^
<stdin>:9:2: note: 'next' match was here
 sv.initial {
 ^
<stdin>:2:51: note: previous match ended here
 hw.module @alwaysff_basic(%arg0: i1, %arg1: i1) {
                                                  ^
<stdin>:3:1: note: non-matching line after previous match is here
 sv.alwaysff(posedge %arg0) {
^
/home/jodemme/circt/test/Dialect/SV/hw-cleanup.mlir:40:16: error: CHECK-NEXT: is not on the line after the previous match
// CHECK-NEXT: sv.fwrite "A2"
               ^
<stdin>:27:2: note: 'next' match was here
 sv.fwrite "A2"
 ^
<stdin>:22:16: note: previous match ended here
 sv.fwrite "A1"
               ^
<stdin>:23:1: note: non-matching line after previous match is here
 }(asyncreset : negedge %arg1) {
^
/home/jodemme/circt/test/Dialect/SV/hw-cleanup.mlir:66:16: error: CHECK-NEXT: is not on the line after the previous match
// CHECK-NEXT: sv.fwrite "A2"
               ^
<stdin>:45:2: note: 'next' match was here
 sv.fwrite "A2"
 ^
<stdin>:35:16: note: previous match ended here
 sv.fwrite "A1"
               ^
<stdin>:36:1: note: non-matching line after previous match is here
 }(asyncreset : negedge %arg1) {
^
/home/jodemme/circt/test/Dialect/SV/hw-cleanup.mlir:109:15: error: CHECK-NEXT: is not on the line after the previous match
//CHECK-NEXT: sv.fwrite "B1"
              ^
<stdin>:62:2: note: 'next' match was here
 sv.fwrite "B1"
 ^
<stdin>:59:16: note: previous match ended here
 sv.fwrite "A1"
               ^
<stdin>:60:1: note: non-matching line after previous match is here
 }
^
/home/jodemme/circt/test/Dialect/SV/hw-cleanup.mlir:131:16: error: CHECK-NEXT: is not on the line after the previous match
// CHECK-NEXT: sv.fwrite "B1"
               ^
<stdin>:73:2: note: 'next' match was here
 sv.fwrite "B1"
 ^
<stdin>:70:16: note: previous match ended here
 sv.fwrite "A1"
               ^
<stdin>:71:1: note: non-matching line after previous match is here
 }
^
/home/jodemme/circt/test/Dialect/SV/hw-cleanup.mlir:223:15: error: CHECK-NEXT: is not on the line after the previous match
//CHECK-NEXT: sv.initial {
              ^
<stdin>:120:2: note: 'next' match was here
 sv.initial {
 ^
<stdin>:113:49: note: previous match ended here
 hw.module @always_basic(%arg0: i1, %arg1: i1) {
                                                ^
<stdin>:114:1: note: non-matching line after previous match is here
 sv.always posedge %arg0 {
^

Input file: <stdin>
Check file: /home/jodemme/circt/test/Dialect/SV/hw-cleanup.mlir

-dump-input=help explains the following input dump.

Input was:
<<<<<<
          1: builtin.module {
          2:  hw.module @alwaysff_basic(%arg0: i1, %arg1: i1) {
          3:  sv.alwaysff(posedge %arg0) {
          4:  sv.fwrite "A1"
          5:  }
          6:  sv.alwaysff(posedge %arg1) {
          7:  sv.fwrite "B1"
          8:  }
          9:  sv.initial {
next:4        !~~~~~~~~~~~  error: match on wrong line
         10:  sv.fwrite "Middle\0A"
         11:  }
         12:  sv.alwaysff(posedge %arg0) {
         13:  sv.fwrite "A2"
         14:  }
          .
          .
          .
         22:  sv.fwrite "A1"
         23:  }(asyncreset : negedge %arg1) {
         24:  sv.fwrite "B1"
         25:  }
         26:  sv.alwaysff(posedge %arg0) {
         27:  sv.fwrite "A2"
next:40       !~~~~~~~~~~~~~  error: match on wrong line
         28:  }(asyncreset : negedge %arg1) {
         29:  sv.fwrite "B2"
         30:  }
         31:  hw.output
         32:  }
          .
          .
          .
         40:  sv.fwrite "C1"
         41:  }(asyncreset : posedge %arg1) {
         42:  sv.fwrite "D1"
         43:  }
         44:  sv.alwaysff(posedge %arg0) {
         45:  sv.fwrite "A2"
next:66       !~~~~~~~~~~~~~  error: match on wrong line
         46:  }(asyncreset : negedge %arg1) {
         47:  sv.fwrite "B2"
         48:  }
         49:  sv.alwaysff(posedge %arg0) {
         50:  sv.fwrite "C2"
          .
          .
          .
         57:  sv.ifdef "FOO" {
         58:  sv.alwaysff(posedge %arg0) {
         59:  sv.fwrite "A1"
         60:  }
         61:  sv.alwaysff(posedge %arg0) {
         62:  sv.fwrite "B1"
next:109      !~~~~~~~~~~~~~  error: match on wrong line
         63:  }
         64:  }
         65:  hw.output
         66:  }
         67:  hw.module @ifdef_merge(%arg0: i1) {
         68:  sv.ifdef "FOO" {
         69:  sv.alwaysff(posedge %arg0) {
         70:  sv.fwrite "A1"
         71:  }
         72:  sv.alwaysff(posedge %arg0) {
         73:  sv.fwrite "B1"
next:131      !~~~~~~~~~~~~~  error: match on wrong line
         74:  }
         75:  }
         76:  hw.output
         77:  }
         78:  hw.module @ifdef_proc_merge(%arg0: i1) {
          .
          .
          .
        115:  sv.fwrite "A1"
        116:  }
        117:  sv.always posedge %arg1 {
        118:  sv.fwrite "B1"
        119:  }
        120:  sv.initial {
next:223      !~~~~~~~~~~~  error: match on wrong line
        121:  sv.fwrite "Middle\0A"
        122:  }
        123:  sv.always posedge %arg0 {
        124:  sv.fwrite "A2"
        125:  }
          .
          .
          .
>>>>>>

--
```

**Comment by fabianschuiki** [comment]
I'll take a look!

**Comment by darthscsi** [comment]
It's not a complete pass through, a couple tests are passing.

**Comment by darthscsi** [comment]
sv.if and sv.ifdef.* and sv.alwayscomb are merging correctly, always.* are not merging

**Comment by darthscsi** [comment]
Specifically, this: https://github.com/llvm/llvm-project/commit/0be5d1a96c8973a4aa56b3fdd8fc22c8a95a7171#diff-30fbfa5104018f2e849ebe42268fb5f2d79768ddba533093c0f0547d3c2274dc
breaks hwcleanup by adding unconditional structural equality checks to OperationEquivalence::isEquivalentTo.
@joker-eph any chance you can add back the previous behavior?  We were specifically group operations as equivalent despite having different regions and region contents.

**Comment by fabianschuiki** [comment]
The LLHD stuff was hitting a new requirement where calls to void functions could would no longer return `!llvm.void` as their return type, but required an explicit empty result list (e.g. through `llvm::None`). Fixed in 1e6ff7758efa3b83114498d7d5aacd7738c51aeb.

**Comment by teqdruid** [comment]
@fabianschuiki Excellent! Thanks! We're down to one. @darthscsi would it be possible to replicate the changed behavior in CIRCT in the meantime? (I really need this patch.)

**Comment by teqdruid** [comment]
Thanks @youngar ! I've confirmed locally that all the tests pass, so once the CI checks pass I'll merge.

Thanks everyone!

**Review by darthscsi — APPROVED** [review]

**Pull request merged**
