### PR TITLE
[PyCDE] PyTorch (dot product) integration test

### PR DESCRIPTION
**Pull request by teqdruid**
Introduces a integration test which takes a PyTorch kernel, builds an ESI system around it, then executes a cosim test. We commit and use MLIR assembly as as to avoid (1) having to install torch_mlir, (2) having to register the cf/arith/memref dialects, and (3) changes to torch_mlir or upstream dialects breaking this test.

### CODE REVIEW

**Review by mortbopet — COMMENTED** [review]
I'm not the biggest fan of having the "pre-lowered" handshake/cf level parts of this be included in the commit, although i understand the intention (this is a PyCDE integration test and attempts to isolate things to be so). However (at least for handshake), i'd expect/hope semantics wouldn't change in the near future, so I'd for this case be inclined to include the handshake lowering instead of checking in >1000 lines of autogenerated mlir.

**Comment by teqdruid** [comment]
> I'm not the biggest fan of having the "pre-lowered" handshake/cf level parts of this be included in the commit, although i understand the intention (this is a PyCDE integration test and attempts to isolate things to be so). However (at least for handshake), i'd expect/hope semantics wouldn't change in the near future, so I'd for this case be inclined to include the handshake lowering instead of checking in >1000 lines of autogenerated mlir.

I'd agree, but there's a technical problem: in order to load the cf/arith/memref ops/types, those dialects must be registered. I can't find a way to register them via python, so it would have to be done via C/C++. PyCDE, however, doesn't have any C code. I also don't want to introduce a hard arith/cf/memref dependency to circt proper. Unless I'm missing something...

**Comment by mortbopet** [comment]
I agree that this shouldn't introduce any new hard dependencies, so this approach seems sane for when using tools that aren't built by default when building CIRCT.

For the handshake one (which is the eyesore, to me), could you not run handshake lowering prior to running the main ESI python test file ([here](https://github.com/llvm/circt/pull/4352/files#diff-66bc228612f69c83c066d2e74426f67e641896680aa85df9b5560bcca9853a63R2)], place that in the working directory and reference it [here](https://github.com/llvm/circt/pull/4352/files#diff-66bc228612f69c83c066d2e74426f67e641896680aa85df9b5560bcca9853a63R80)?

**Comment by teqdruid** [comment]
> I agree that this shouldn't introduce any new hard dependencies, so this approach seems sane for when using tools that aren't built by default when building CIRCT.
> 
> For the handshake one (which is the eyesore, to me), could you not run handshake lowering prior to running the main ESI python test file ([here](https://github.com/llvm/circt/pull/4352/files#diff-66bc228612f69c83c066d2e74426f67e641896680aa85df9b5560bcca9853a63R2)]), place that in the working directory and reference it [here](https://github.com/llvm/circt/pull/4352/files#diff-66bc228612f69c83c066d2e74426f67e641896680aa85df9b5560bcca9853a63R80)?

*sigh* why didn't I think of that?

**Comment by teqdruid** [comment]
> For the handshake one (which is the eyesore, to me), could you not run handshake lowering prior to running the main ESI python test file ([here](https://github.com/llvm/circt/pull/4352/files#diff-66bc228612f69c83c066d2e74426f67e641896680aa85df9b5560bcca9853a63R2)]), place that in the working directory and reference it [here](https://github.com/llvm/circt/pull/4352/files#diff-66bc228612f69c83c066d2e74426f67e641896680aa85df9b5560bcca9853a63R80)?

Done. Is this what you are talking about?

**Review by mortbopet — APPROVED** [review]
Yup! much cleaner 🎉.

Ideally you should be able to replace
```
circt-opt dot.cf.mlir --flatten-memref --flatten-memref-calls --handshake-legalize-memrefs --lower-std-to-handshake --canonicalize --handshake-lower-extmem-to-hw=wrap-esi --handshake-insert-buffers --canonicalize --handshake-remove-block-structure --handshake-materialize-forks-sinks --lower-handshake-to-hw --canonicalize > dot.hw.mlir
```
with
```
hlstool dot.cf.mlir --with-esi --dynamic-hw -ir -ir-output-level 2 > dot.hw.mlir
```

**Comment by teqdruid** [comment]
DONE!

**Pull request merged**
