### PR TITLE
Update LLVM version to 34ddf0b2b040

### PR DESCRIPTION
**Pull request by stephenneuendorffer**
A small fixup is required to avoid conflicts between ODS-generated build
methods because of default arguments.

### CODE REVIEW

**Comment by lattner** [comment]
Feel free to land these without review @stephenneuendorffer  :)

**Comment by stephenneuendorffer** [comment]
> Feel free to land these without review @stephenneuendorffer :)

That was my plan but stuff is broken in the LLHDtoLLVM type conversion.  It looks like the standard LLVM type converter is choking on an llhd.sig type whereas previously this passed through to the op conversion which handled the type conversion.  @maerhart @fabianschiuki  one of you is probably going to have to fix this up.

**Comment by maerhart** [comment]
@rodonisi May I forward this to you as you are the author of the LLVM conversion pass?

**Comment by rodonisi** [comment]
> @rodonisi May I forward this to you as you are the author of the LLVM conversion pass?

Yep, building LLVM right now.

**Comment by rodonisi** [comment]
@stephenneuendorffer I opened a [PR](https://github.com/stephenneuendorffer/circt/pull/1) on this branch of your fork which should be passing the tests.

**Comment by stephenneuendorffer** [comment]
> @stephenneuendorffer I opened a [PR](https://github.com/stephenneuendorffer/circt/pull/1) on this branch of your fork which should be passing the tests.

Awesome!  Thanks!

**Pull request merged**
