### PR TITLE
[CMake] [NFC] Eliminate cmake `glob`s

### PR DESCRIPTION
**Pull request by teqdruid**
CMake `glob`s only get run at configuration time; so, when one adds a file,
they must cmake re-configure. When a file gets added and someone git-pulls it
in, they must manually re-configure (since Ninja doesn't detect the
cmake-affecting change). This change makes it so `git pull && ninja` just
works.

### CODE REVIEW

**Review by stephenneuendorffer — APPROVED** [review]
Definitely a good idea.

**Comment by teqdruid** [comment]
> Thanks for putting this in. Is there anywhere meaningful we could document this footgun for the future?

This is definitely fodder for a developer's policy document: "Thou shalt not use cmake glob". Since MLIR doesn't seem to have any, I think the right place for it is in their developer policy.

**Comment by teqdruid** [comment]
FYI @richardxia -- penance for my mistake earlier.

**Comment by richardxia** [comment]
Thanks! And I'm glad that we're eliminating this type of problem from the repo!

**Pull request merged**
