### PR TITLE
[Docs] Update dialects diagram

### PR DESCRIPTION
**Pull request by maerhart**
* Remove arrow from Comb to ExportSystemC since it has to be lowered through SystemC
* Add arrow from Moore to LLHD since it lowers things that Seq/HW/Comb cannot represent to LLHD
* Move SV from the Core Dialects cluster to the backend dialects since it is targeted towards printing and not analysis and transformations

### CODE REVIEW

**Review by mortbopet — APPROVED** [review]

**Comment by mikeurbach** [comment]
I understand the motivation to move SV out of the core dialects, but I think it's somewhat misleading now. Seq is not the only thing that emits the SV dialect, there are many other routes: like FIRRTL and MSFT, among others. Rather than drawing all those arrows, having SV under core dialects enables some simplifications in the diagram.

**Comment by maerhart** [comment]
Thanks for the clarification @mikeurbach ! What would be the full list of dialects/frontends that lower to SV? FSM, FIRRTL, ESI, MSFT?

I think it would add value to the diagram if one could see what dialects are entirely (maybe except for some unimportant details) lowered to the 'core' dialects for easy analysis and transformations. It would also indicate which frontends could be completely captured by a new backend when only lowering from the 'core' dialects (since lowering from SV is probably not the best idea except printing). Could one of the following diagrams solve both concerns without introducing new ones?

(1)
dialects
(2)
dialects
(3)
dialects

**Comment by mikeurbach** [comment]
Thanks for playing around with this. I am not sure yet which dialects emit SV, but we will get the list. I think any of the proposed options could work, and personally I prefer (1). IMO it's nice to show which dialects directly emit SV in some cases, without imposing visual grouping on distinct things, like FSM, ESI, etc.

**Comment by teqdruid** [comment]
I think MSFT only outputs SV's VerbatimOp to output the TCL file, which I don't really count (VerbatimOp for this use is a misnomer and also shouldn't be in the SV dialect). ESI does output SV ops.

**Pull request merged**
