### PR TITLE
Disable llhd-sim tests when the executable is not built

### PR DESCRIPTION
**Pull request by youngar**

### CODE REVIEW

**Review by teqdruid — APPROVED** [review]
LGTM. Thanks much!

**Comment by youngar** [comment]
220 tests run when llhd is disabled (tested locally), 229 when enabled (tested in PR build), looks like its working as intended on Linux.  Waiting for the windows job here: https://github.com/llvm/circt/runs/3070559618

**Comment by youngar** [comment]
The windows cmake invocation is happy now, but it's still failing overall (as expected)

**Comment by teqdruid** [comment]
Thanks for noticing this problem and fixing it!

**Pull request merged**
