### PR TITLE
[SCFToCalyx] replace shell command with %S for Windows in the test file

### PR DESCRIPTION
**Pull request by jiahanxie353**
I'm not very familiar with the Windows command and test, would this proposed fix address the failing tests?

### CODE REVIEW

**Comment by jiahanxie353** [comment]
Or how can I run the Windows CI check before actually merging?

**Comment by uenoku** [comment]
You can launch CI from https://github.com/llvm/circt/actions/workflows/buildAndTestWindows.yml. Probably you need to push the branch to llvm/circt for that though.

**Comment by jiahanxie353** [comment]
> You can launch CI from https://github.com/llvm/circt/actions/workflows/buildAndTestWindows.yml. Probably you need to push the branch to llvm/circt for that though.

I'll try, thanks!

**Comment by jiahanxie353** [comment]
confirmed and merged here: https://github.com/llvm/circt/pull/7956

**Pull request closed without merging**
