### PR TITLE
[MSFT] Add LogicLockedRegion attribute.

### PR DESCRIPTION
**Pull request by mikeurbach**

### CODE REVIEW

**Comment by seldridge** [comment]
Random nit: "logic locking" has a very specific meaning in the literature. Namely, I'm familiar with this as a security technique to add gates to a circuit that must be set in a specific way in order for the circuit to work correctly. When I saw this fly by, I thought this was about automating the addition of logic locking to a design. 😅  (There was some cool work doing this for the Scala FIRRTL Compiler a while back: https://github.com/jpsety/obfuscation)

You may want to consider a different name here to avoid the name collision (unless this is some FPGA-specific language that I'm unaware of).

**Comment by teqdruid** [comment]
"logic locked region" is what quartus calls it. I don't know what Xilinx
calls it, but I am open to suggestions.

**Comment by mikeurbach** [comment]
I don't feel strongly about the name, but since "Region" means something important in MLIR, I didn't want to just call it that. Maybe "PhysicalRegion"?

**Comment by teqdruid** [comment]
I’d suggest adding a “PhysicalRegion” op with a name as the symbol. Then, accept an attribute called “msft:locate” with a symbolref attribute which refers to the Region to indicate that that instance/reg should be in that region.

**Comment by mikeurbach** [comment]
I thought about this as well, but wasn't sure if the indirection through a symbol reference was warranted. Since we have to stick an attribute on every located op anyway, it seemed like putting all the information into the attribute would save a symbol lookup and extra op(s) in the IR. We should be able to have this attribute uniqued and immortalized in the context, so this doesn't cause duplication and bloat memory (although it will be duplicated in the printed form). Is there a downside the the current approach I'm missing? Or an upside to having a Symbol op that I'm missing?

**Comment by teqdruid** [comment]
> Is there a downside the the current approach I'm missing? Or an upside to having a Symbol op that I'm missing?

It's all about modeling -- we want the MLIR model to match as closely as possible with our mental model and the pycde entry model as possible. The physical region is logically a separate entity which pycde will create first, so it should be a separate op.



> EDIT: Another small upside to the current approach is it sidesteps any issues related to introducing a new op ExportVerilog will need to handle or skip over.

Yeah, this isn't a great reason. Did you had a chance to bring up this problem in the meeting? If not, could you start the discussion with an issue? I'm not familiar with the new way ExportVerilog works wrt side effects and error messages.


> it seemed like putting all the information into the attribute would save a symbol lookup

Is there no `SymbolLookupCache` class in MLIR? That seems like a really useful thing to have. Ideally, all symbol lookups would be cached and MLIR would handle cache invalidations but I don't know if that's in the cards.

MLIR symbols seem like they need work (I'm not familiar enough with the current deficiencies to say what specifically), but that shouldn't stop us from using them for their intended purpose.

**Comment by mikeurbach** [comment]
> The physical region is logically a separate entity which pycde will create first, so it should be a separate op.

I think this is where we are diverging. In https://github.com/llvm/circt/pull/2059, I added a PyCDE API analogous to what we have to locate a module on a primitive. That call just creates this attribute. Is this not the intended entry method for PyCDE?

I honestly don't know the requirements here. What is the use case to have PyCDE declare the physical region first, and then do the association of operations to regions second? So far I have modelled them the same as PhysLocation, which PyCDE just attaches to an operation ad-hoc.

**Comment by mikeurbach** [comment]
> Did you had a chance to bring up this problem in the meeting?

We didn't talk about it. I can open an issue.

> Is there no SymbolLookupCache class in MLIR?

I don't think so. There is something in CIRCT for this that we may be able to use.

**Comment by mikeurbach** [comment]
Will open a separate PR for "PhysicalRegion". After some discussion, the design is more different than just renaming.

**Pull request closed without merging**
