### PR TITLE
[LLVM bump] Bump to the last working version

### PR DESCRIPTION
**Pull request by teqdruid**
One of my Windows python builds is broken with the current version of the submodule. Since then, it got fixed.

### CODE REVIEW

**Comment by teqdruid** [comment]
I started in on updating to the latest and fixing all the stuff that upstream broken. But that onion proved thicker than I had the patience to peel on a Friday night.

**Comment by seldridge** [comment]
FYI: we (SiFive) have a rotating task to do this every week which is why you would normally see an LLVM bump always land on Fridays. We recently changed our sprint schedule, so these will now go on Wednesday or Thursday morning starting next week. (Normally we'd have one in today, but the sprint switchover created a lag.) Thanks for getting this going, John!

**Comment by teqdruid** [comment]
Yeah, I just don't want to be a freeloader. Plus, a bunch of the errors are coming from my code this time around.

**Comment by teqdruid** [comment]
This small bump compiles fine, but has test failures I thought was as a result of VS2022 (https://github.com/llvm/circt/issues/4570) were actually this bump.

**Comment by teqdruid** [comment]
This has now been subsumed by #4568.

**Pull request closed without merging**
