### PR TITLE
[ESI] C API and Python bindings

### PR DESCRIPTION
**Pull request by teqdruid**
Just the ability to 'import' ESI into Python. All of the ESI ops require `ChannelType`, so I didn't include anything in the integration test other than importing esi.

### CODE REVIEW

**Comment by teqdruid** [comment]
@mikeurbach In the short term, how do I create types?

**Comment by mikeurbach** [comment]
You essentially need to depend on this: https://github.com/llvm/llvm-project/blob/69ca50bd7dfdb54aab8b0b262df635e25cf6baf0/mlir/lib/Bindings/Python/IRTypes.cpp#L35-L36

That's what I hacked up locally, at least. Is this something you'd want for Python before any of the longer term stuff we talked about lands? I would prefer to spend time on the long term solution, but if there is a need for custom types in the Python bindings before that, we can try and expose the above template (and friends) in a public way upstream.

**Comment by teqdruid** [comment]
Ah, so that's the best way. Yeah, I'll want that shortly but it need not be upstream. This looks like something we can copy and customize until the long term solution is complete. If you agree, I can do this now.

**Comment by mikeurbach** [comment]
Yep that is how upstream does it. I think it should be straightforward to copy out PyConcreteType to something like a PyCIRCTType base class. The upstream classes hook into all the stuff related to contexts, not sure if we want that part or can just copy out the template to start stamping out C API wrappers.

A good example would be rtl.array or rtl.inout type. They should both have the required C API in CIRCT already, just need to bind it up.

**Comment by teqdruid** [comment]
> The upstream classes hook into all the stuff related to contexts,

Are you referring to Python "context-manger" or `MLIRContext`? Is the `DefaultingPyMlirContext`  ([from here](https://github.com/llvm/llvm-project/blob/69ca50bd7dfdb54aab8b0b262df635e25cf6baf0/mlir/lib/Bindings/Python/IRTypes.cpp#L82)) what you're talking about? If context-manager, yes I think we'll want them.

> They should both have the required C API in CIRCT already, just need to bind it up.

Are you talking pybind11 it up or just exposing the C API functions via MLIR functionality I don't really know or understand?

**Comment by mikeurbach** [comment]
> Is the DefaultingPyMlirContext (from here) what you're talking about? If context-manager, yes I think we'll want them.

Yep that stuff, PyMlirContext, really everything up the class hierarchy to PyObjectRef. We already have the ability to use that defaulting style [here](https://github.com/llvm/circt/blob/fef21d8ca90f8c6e7577357caac81faf3ac58cff/integration_test/Bindings/Python/dialects/rtl.py#L10). If we are extracting the PyType stuff, I'm not sure if we will need to duplicate some of the PyObjectRef hierarchy or not.

> Are you talking pybind11 it up or...

I mean we could write a pybind11 module for the InOutType today, using the C API that exists in CIRCT right now. Whether you copy over the PyConcreteType stuff or duplicate that functionality in another way, the necessary C API is there, and we need to wrap that up with a pybind11 C++ class.

**Comment by teqdruid** [comment]
OK. I'm gonna land this one separately then copy over the helper from IRTypes.cpp. Sound good?

**Comment by mikeurbach** [comment]
Landing this as-is sounds good to me. I started the "copy over the helper" approach, and found that it was harder than expected to disentangle it from the rest of IRTypes.cpp and the IRModule.h classes. After I copied over PyConcreteType to CIRCT locally, I ended up needing to link against the whole _mlir native extension and depend on its headers:

```
+# TODO(mikeurbach): Temporary measures to be able to borrow upstream PyType.
+target_include_directories(CIRCTBindingsPythonExtension PRIVATE                                                                                                                                                   
+  ${MLIR_MAIN_SRC_DIR}/lib/Bindings/Python)                                                                                                                                                                       
+target_link_libraries(CIRCTBindingsPythonExtension PRIVATE                                                                                                                                                        
+  MLIRCoreBindingsPythonExtension)  
```

I also had to change some stuff related to how our extensions are layered/loaded to make the above work. Basically, this hack: https://github.com/llvm/mlir-npcomp/blob/c3f1f8ebf4df151d618f092f75fe81e05e26c345/python/npcomp/__init__.py#L1-L16

This is a long winded way of saying it's more than just copying PyConcreteType and PyType, you probably end up copying most of IRModule.h and PybindUtils.h. I was working on a patch to just expose all of that upstream so it can be depended on with CMake... but I won't be able to take a look till next week at this point.

**Review by mikeurbach — APPROVED** [review]

**Comment by mikeurbach** [comment]
More thoughts on the Python type definitions: instead of just copying PyConcreteType and PyType, I'm sort of expanding the template out mentally and looking at what we need. It seems to boild down to:
* constructor
* to/from capsule methods
* operator helpers for == and casting to/from MlirType
* static `isinstance` definition that calls C API for isa
* static `get` definition that calls C API for construction/getters

If you are trying to extract those to make base classes in CIRCT, I think that's the minimum to replicate the needed functionality.

However, I'm also remembering why I ended up taking the hacky dependency on the upstream class directly. Originally, I just created a new base class on our side with the above functionality, but something in the upstream bindings threw an error like this:

```
ValueError: Result 0 of operation "sv.wire" must be a Type (Unable to cast Python instance of type <class 'PyCapsule'> to C++ type 'mlir::python::PyType')
```

In the static get method on InOutType, I made an MlirType and called mlirPythonTypeToCapsule, but the resulting capsule failed with the above. This is a more concrete example of "it was harder than expected to disentangle it from the rest of IRTypes.cpp and the IRModule.h classes". I haven't really understood how the casting functionality works here, so maybe I'm just missing a bullet point above for "make casting work like the other PyTypes".

Let me at least clean up my branch so you can more concretely see what I mean.

**Comment by mikeurbach** [comment]
@teqdruid here you go: https://github.com/llvm/circt/pull/876.

This was going to be my big integration branch for getting the counter tests working, and I was going to chip off changes to land either here or upstream as needed. Up to you where you want to go, but personally I think the CMake hacks are too much of a kludge to land in CIRCT in their current state, which is why I was going to investigate/propose exposing some of that upstream.

**Comment by teqdruid** [comment]
Yeah, this looks like a lot more than I thought we'd need. @stellaraccident, Are you amenable to making [`PyConcreteType`](https://github.com/llvm/llvm-project/blob/69ca50bd7dfdb54aab8b0b262df635e25cf6baf0/mlir/lib/Bindings/Python/IRTypes.cpp#L35-L36) (and everything it may require in terms of linking and cmake support) publicly accessible as a short term solution to the custom types/attributes issue?

**Comment by stellaraccident** [comment]
I think this is more entangled than is immediately obvious. This was one of the first things we wrote in the bindings and I think we could extract some out of module helpers that would work, but I do think it needs to be done a bit carefully. Done wrong and it will create subtle cross module c++ linkages that will break or be fragile.

If you want to hack on this, the best way is to copy what you want to an isolated header in your project, strip out down and then upstream when we have something that works. On the discourse thread, I reference a PybindUtils.h file that has some of the casting support you want.

Can write more later. I don't think this is super hard but there is some subtlety to it.

**Pull request merged**
