### PR TITLE
[RTL] Adding 'array' type

### PR DESCRIPTION
**Pull request by teqdruid**

### CODE REVIEW

**Comment by teqdruid** [comment]
@lattner Is this worth merging without support in EmitVerilog.cpp? I'm leaning towards yes but not strongly. I'll eventually want it for modeling and printing ESI but I can always copy it into the ESI dialect.

**Comment by lattner** [comment]
I'd prefer for this to include EmitVerilog support (e.g. when used in a module port list and wire) :-), but I don't think that is a hard blocker if there is a reason to land this without it.

**Comment by darthscsi** [comment]
What's the reason to add a type rather than using the existing vector type?

**Comment by teqdruid** [comment]
https://llvm.discourse.group/t/optimizations-and-the-rtl-dialect/1923/21?u=jdd

**Comment by lattner** [comment]
Just FYI, I'm going to commit this and build on top of it, assuming CI approves it. Thx

**Comment by teqdruid** [comment]
I assume this is for the firrtl lowering to rtl you mentioned you were going to be working on today?

**Comment by lattner** [comment]
Yeah, I'm not using array specifically, I wanted to use the patch as the basis for the inout type.

**Pull request merged**
