### PR TITLE
[Handshake] Only buffer merge-like outputs in the 'cycles' buffering strategy

### PR DESCRIPTION
**Pull request by mortbopet**
Previously, the DFS based approach would naively place a buffer on every site that was determined a cycles. Cycles should only occur at merge-like operations; due to this, buffers would essentially be placed on all of the inputs to a merge-like operation, instead of placing it on the output of the merge-like op.

In this commit, we insert a buffer at the output of a merge-like operation whenever the op is determined to be within a cycle. This greatly reduces the number of buffers placed by the "cycles" strategy.

Additionally, cleaned up some of the buffering code to extract buffer placement routines to separate functions.
A follow up commit will remove all of the buffering passes from StandardToHandshake to be Handshake dialect passes.

### CODE REVIEW

**Comment by mortbopet** [comment]
I think we can ignore clang-tidy here; it's complaining about inCycle being a recursive function.

**Review by mikeurbach — APPROVED** [review]
Nice, that is a good improvement to the code. I've experimented with something like this before, but never bothered to add it since it still doesn't prevent deadlocks. But simplifying the tool to prevent cycles makes good sense to me.

**Comment by mortbopet** [comment]
> since it still doesn't prevent deadlocks

I am deep in deadlock investigation mode at the moment - things should theoretically work with just buffers to break cycles so _somewhere_ there is _something_ going wrong.

**Comment by mikeurbach** [comment]
> I am deep in deadlock investigation mode at the moment - things should theoretically work with just buffers to break cycles so somewhere there is something going wrong.

You would think... I tried to find a better way before to no avail. Certainly there is a solution somewhere in between.

**Pull request merged**
