### PR TITLE
[PyCDE] Implement new DynamicInstance operation methodology

### PR DESCRIPTION
**Pull request by teqdruid**

### CODE REVIEW

**Comment by teqdruid** [comment]
@mikeurbach This is "working" (passing all the PyCDE tests, module the most recent main merge). It "just" needs a lot of cleanup and documentation. But the overall structure is unlikely to change. Not ready for review.

**Comment by teqdruid** [comment]
@jptech @mikeurbach I think this is the closest it's gonna get before I leave. This passes all the tests, so it _should_ work internally, though some modifications may be necessary. I tried my best to keep the API surface the same, but that wasn't my primary goal.

**Review by mikeurbach — COMMENTED** [review]
This looks pretty good to me. I think the new pieces make a lot more sense, let's see how the performance looks.

**Comment by mikeurbach** [comment]
This looks good to me. I will merge it to fix the PyCDE builds on main.

**Pull request merged**
