### PR TITLE
[RFC][Scheduling] A dialect for scheduling problems

### PR DESCRIPTION
**Pull request by jopperm**
**Current state**: https://github.com/llvm/circt/pull/3244#issuecomment-1192360140

-----

This is a first step towards #2760: **Setup of the dialect**, but no import/export of the underlying scheduling problem yet. Happy to break this down into smaller PRs after the general discussion.

Quoting the rationale from the referenced issue:

> @mikeurbach and I think it would be useful to have an import/export format for scheduling problem instances, e.g. for writing test cases and benchmarking independent from the concrete (and potentially proprietary!) synthesis flow.
> 
> Going with the dialect approach (instead of just going with Cap'n'Proto, JSON, etc.) allows to generate Python bindings for the scheduling infrastructure with the usual mechanism. This would further benefit prototyping of new problem models and algorithms.
> 
> Note: The proposed dialect is intended for testing/prototyping/benchmarking purposes only! Synthesis flows are supposed to use the API provided by the Problem class hierarchy directly.

This PR defines the proposed IR to look like this:
```mlir
ssp.instance "canis14_fig2" of "ModuloProblem" {
  ssp.operator_type @MemPort {latency = 1, limit = 1}
  ssp.operator_type @Add {latency = 1}
  ssp.operator_type @Implicit {latency = 0}

  %0 = ssp.operation @load_A(@store_A {distance = 1}) {opr = @MemPort, startTime = 2}
  %1 = ssp.operation @load_B() {opr = @MemPort, startTime = 0}
  %2 = ssp.operation @add(%0, %1) {opr = @Add, startTime = 3}
  ssp.operation @store_A(%2) {opr = @MemPort, startTime = 4}
  ssp.operation @last(@store_A) {opr = @Implicit, startTime = 5}
} {initiationInterval = 3}
```

The above example would replace the following test case, where especially the encoding of auxiliary dependence edges and their properties is kind of awkward:
```mlir
func.func @canis14_fig2() attributes {
  problemInitiationInterval = 3,
  auxdeps = [ [3,0,1], [3,4] ],
  operatortypes = [
    { name = "mem_port", latency = 1, limit = 1 },
    { name = "add", latency = 1 }
  ] } {
  %0 = "dummy.load_A"() { opr = "mem_port", problemStartTime = 2 } : () -> i32
  %1 = "dummy.load_B"() { opr = "mem_port", problemStartTime = 0 } : () -> i32
  %2 = arith.addi %0, %1 { opr = "add", problemStartTime = 3 } : i32
  "dummy.store_A"(%2) { opr = "mem_port", problemStartTime = 4 } : (i32) -> ()
  return { problemStartTime = 5 }
}
```

### CODE REVIEW

**Comment by mortbopet** [comment]
Since the intention of this dialect is to be strictly for testing purposes, then

**Comment by mikeurbach** [comment]
Awesome to see this! Some initial thoughts below.

> I'd generally have some apprehension about the ssp.operation encoding everything, but, given that this dialect is strictly for generating scheduling problems and not about maintaining some source program structure (that is, if a source program were not dummy operations but real IR), then i understand the intent.

I think there is a little more nuance here, so let me try to provide my perspective, and maybe Julian can fill in the blanks. I don't think the ssp.operation needs to encode everything, but I do think it needs to maintain some source program structure that is vital to creating scheduling problems: the SSA graph. I think it would be safe to drop other aspects of the IR being scheduled, like attributes and whatnot, but the scheduling infrastructure uses the SSA def-use chains for dependences.

If I'm reading this correctly, the current proposal is to have `ssp.operation` be a Symbol, and either express dependences via SSA values or Symbol references for auxiliary dependences. This initially felt a little awkward to me but I'm not sure I have a better idea... here's one half baked thought:

I initially thought "why not make ssp.operation anonymous", i.e. not a Symbol. Then I saw that aux dependences are encoded via Symbol references. But maybe this doesn't have to be the case. Since we are capturing the scheduling problem in our own dialect, we don't have to just stick to the original SSA graph, we could also add SSA values for auxiliary dependences, which might make the IR a little more uniform. My gut feeling is this might be easier to import/export, build, transform etc., since you just have to worry about a graph of dependences using MLIR's SSA tools, rather than also sometimes breaking out into Symbol land, where all the SSA rules go out the window. I imagined something like (opr and start time elided):

```
%0 = ssp.operation aux(%4) {distance = 1}
%1 = ssp.operation
%2 = ssp.operation ssa(%0), ssa(%1)
%3 = ssp.operation ssa(%2)
%4 = ssp.operation aux(%3)
```

> latency, limit and startTime attributes could also be folded into ODS as required or optional parts of the asm format, if desired.

+1, I would suggest defining all attributes used here in ODS with proper type constraints. This signals to both the infrastructure and compiler engineers that these things are [inherent and not discardable](https://mlir.llvm.org/docs/LangRef/#attributes). For "properties" specifically, rather than making it a DictionaryAttr, I would suggest defining a new AttrDef with the fields you care about, or splatting out all those fields on the dependence attr. It seems like a great opportunity to make this well defined in ODS, which can lead to autogenerated docs, verifiers, helper methods, etc. and be a little more explicit about the problem model.

**Comment by jopperm** [comment]
Many thanks for your feedback!

> > I'd generally have some apprehension about the ssp.operation encoding everything, but, given that this dialect is strictly for generating scheduling problems and not about maintaining some source program structure (that is, if a source program were not dummy operations but real IR), then i understand the intent.
> 
> I think there is a little more nuance here, so let me try to provide my perspective, and maybe Julian can fill in the blanks. I don't think the ssp.operation needs to encode everything, but I do think it needs to maintain some source program structure that is vital to creating scheduling problems: the SSA graph. I think it would be safe to drop other aspects of the IR being scheduled, like attributes and whatnot, but the scheduling infrastructure uses the SSA def-use chains for dependences.

:100:

`ssp` would be kind of a one-way street, dialect-conversion-wise, intended for situations where constructing or storing the real source IR for a scheduling problem is inconvenient (see current scheduling test cases :wink:) or impossible (internal dialects etc.).

> One suggestion would be to create a separate region for operator type definitions, and operations themselves.

I like that!

> If I'm reading this correctly, the current proposal is to have `ssp.operation` be a Symbol, and either express dependences via SSA values or Symbol references for auxiliary dependences. 

Right. I went with the symbols to be able to faithfully reproduce (i.e. distinguishing defuse and auxiliary deps) a scheduling problem as it was constructed using the API. I like how you the IR looks in your example snippet, and I think I could introduce custom MLIR types to distinguish which SSA value denotes which kind of dependence. The problem is that "aux-type" SSA values would still be SSA dependences in the problem, because the scheduling problems currently consider *all* def-use-edges between registered operations, and there's no way to exclude them.

As a middle ground, how would you feel about making the symbols optional on the operations, so that only operations that serve as the source for an auxiliary dep (which should be just a few) would need to carry one?

>  > latency, limit and startTime attributes could also be folded into ODS as required or optional parts of the asm format, if desired.
> 
> +1, I would suggest defining all attributes used here in ODS with proper type constraints. This signals to both the infrastructure and compiler engineers that these things are [inherent and not discardable](https://mlir.llvm.org/docs/LangRef/#attributes). For "properties" specifically, rather than making it a DictionaryAttr, I would suggest defining a new AttrDef with the fields you care about, or splatting out all those fields on the dependence attr. It seems like a great opportunity to make this well defined in ODS, which can lead to autogenerated docs, verifiers, helper methods, etc. and be a little more explicit about the problem model.

The idea behind having generic dicts to encode all scheduling properties was to support future or OOT problem definitions (with additional properties). But I do see the appeal of defining proper assembly formats for at least the properties used in the in-tree problems (such as latency, startTime, etc.). Generic attr dicts would still have to be supported, but used much less frequently.

**Comment by jopperm** [comment]
Incorporating the above, the IR could look like this:
```mlir
ssp.instance @canis14_fig2 of "FancyModuloProblem" operators {
  ssp.operator_type @MemPort {latency = 1, limit = 1}
  ssp.operator_type @Add {latency = 1}
  ssp.operator_type @Implicit {latency = 0}
} graph {
  %0 = ssp.operation<@MemPort>(@store_A {distance = 1}) {startTime = 2}
  %1 = ssp.operation<@MemPort>() {startTime = 0}
  %2 = ssp.operation<@Add>(%0, %1) {startTime = 3}
  ssp.operation<@MemPort>@store_A(%2) {startTime = 4}
  ssp.operation<@Implicit>(@store_A) {startTime = 5}
} properties {initiationInterval = 3}
```
(properties would be attributes in the ODS, but IMHO it's hard to derivate from the attributes-in-curly-braces-syntax, which feels natural)

**Comment by jopperm** [comment]
> This might be a dumb question, but auxiliary edge <=> backedge?

Backedges are a canonical example, but in general, everything that is otherwise implicit in the source IR, but needs to be modeled in the scheduling problem. For example, in `AffineToStaticLogic`, aux deps are inserted for memory dependences, control dependences (from `yield` to `if`), and for the `iter_args` in the affine loop.

**Comment by mikeurbach** [comment]
> properties would be attributes in the ODS, but IMHO it's hard to derivate from the attributes-in-curly-braces-syntax, which feels natural

IMO this syntax looks fine too, so long as the known properties are defined as inherent attributes.

> Generic attr dicts would still have to be supported, but used much less frequently.

That sounds like a good plan to me.

> I think I could introduce custom MLIR types to distinguish which SSA value denotes which kind of dependence. 

I guess I only hinted at this, but I think you might not even need to so far as to introduce types. What I imagined was an enum attribute to distinguish def-use from aux deps, and for each `ssp.operation` you could have an array of such attributes (and check in the verifier that the length of the array matches the length of the operands). I don't know if it's materially any different than adding them as types though.

> The problem is that "aux-type" SSA values would still be SSA dependences in the problem, because the scheduling problems currently consider all def-use-edges between registered operations, and there's no way to exclude them.

Hmm that's a good point, I guess if the graph of `ssp.operation`s were fed to the infrastructure that will have to be the case. So with the proposed approach with Symbols, after feeding in the `ssp.operation`s, the problem import layer would then traverse the symbol table to feed in aux dependences? That seems like a good approach now that you've clarified it.

**Comment by jopperm** [comment]
Quick update:
- The IR now looks like this:
```mlir
ssp.instance "canis14_fig2" of "ModuloProblem" [II<3>] {
  operator_type @MemPort [latency<1>, limit<1>]
  operator_type @Add [latency<1>]
  operator_type @Implicit [latency<0>]
  %0 = operation<@MemPort> @load_A(@store_A [dist<1>]) [t<2>]
  %1 = operation<@MemPort> @load_B() [t<0>]
  %2 = operation<@Add> @add(%0, %1) [t<3>]
  operation<@MemPort> @store_A(%2) [t<4>]
  operation<@Implicit> @last(@store_A) [t<5>]
}
```

- The properties are now individual attributes, defined with minimal tablegen specifying the name, data type and defining `Problem` class (example below). Attribute interfaces didn't work out here, because I'd need the interface method(s) to accept the concrete `Problem` subclass a property is defined on.
```tablegen
def Distance : DependenceProperty<SSPDialect,
  "Distance", "unsigned", "::circt::scheduling::CyclicProblem"> {
  let mnemonic = "dist";
}
```

- Unfortunately, the `SymbolTable` trait prevents the `InstanceOp` from having separate regions for operator types and the dependence graph.

- I also started to flesh out the machinery to load a `Problem` instance from an `InstanceOp`, and vice versa (see: [`Utilities.h`](https://github.com/llvm/circt/pull/3244/files#diff-721a60bb3d9302f5b7c38e7ccf45462d6e1ba75d4d61349913fd30251b08228e), [`TestPasses.cpp`](https://github.com/llvm/circt/pull/3244/files#diff-d5bf9e04aff3fd1df1980a179b75278a9458357273968a0a650e2c32e18b527dR566)). The code is heavily templated to work with any problem/properties, even out-of-tree ones.

I plan to submit the usual first PR with the dialect boilerplate and rationale soon (currently working on the prose for the latter), but will leave this one up for people to see the entire system in action.

**Comment by jopperm** [comment]
> Awesome update! Looking forward to seeing the PRs. I think the current implementation looks like a nice sweet spot of leaning on ODS instead of interfaces, and using MLIR's symbol table as best as it can be used.

Thanks @mikeurbach! The first PR us here: #3558

**Comment by jopperm** [comment]
Update: The IR now has separate container ops for the operator library and the dependence graph (thanks @mortbopet):

```mlir
ssp.instance "canis14_fig2" of "ModuloProblem" [II<3>] {
  library {
    operator_type @MemPort [latency<1>, limit<1>]
    operator_type @Add [latency<1>]
    operator_type @Implicit [latency<0>]
  }
  graph {
    %0 = operation<@MemPort>(@store_A [dist<1>]) [t<2>]
    %1 = operation<@MemPort>() [t<0>]
    %2 = operation<@Add>(%0, %1) [t<3>]
    operation<@MemPort> @store_A(%2) [t<4>]
    operation<@Implicit>(@store_A) [t<5>]
  }
}
```

**Comment by jopperm** [comment]
Closing this -- the last piece is currently up for review as #3636 (and this branch has diverged a bit from what has landed in main due to the reviews).

**Pull request closed without merging**
