### PR TITLE
[Scheduling] Add simplex scheduler for the cyclic problem.

### PR DESCRIPTION
**Pull request by jopperm**
This scheduler uses linear programming and a handwritten simplex solver to compute the II and start times for the `CyclicProblem`. I'll add support for the basic `Problem` in a later PR.

This is an implementation of the approach proposed in:
> B. D. de Dinechin, "Simplex Scheduling: More than Lifetime-Sensitive Instruction Scheduling", PRISM 1994.22, 1994.
([Paper on ResearchGate](https://www.researchgate.net/publication/2607040_Simplex_Scheduling_More_than_Lifetime-Sensitive_Instruction_Scheduling))

**Rationale** Linear programming is the superior framework for tackling the "computing start times"-aspect of scheduling problems, so I wanted to have LP-based scheduling technology as soon as possible. This, of course, requires an LP solver. I decided to implement this very basic and non-generic simplex solver myself to have a default option available in CIRCT that does not require external libraries. I do not plan to expose the simplex solver as a standalone utility to other parts of CIRCT, but will rather look into integrating existing solvers ([Google OR tools](https://developers.google.com/optimization/) look promising) as optional library dependencies.

### CODE REVIEW

**Comment by jopperm** [comment]
I consulted the following text book for a better understanding of the simplex algorithm:
> Hamacher, H. W., Klamroth, K. (2007). Lineare Optimierung und Netzwerkoptimierung  

Despite the German title, this book is actually bilingual. The relevant part (§3.3 The Dual Simplex Method) is available in the [Google Books preview](https://www.google.de/books/edition/Lineare_Optimierung_und_Netzwerkoptimier/MntwLszx8H0C).

**Comment by jopperm** [comment]
Reverted to draft to investigate a problem found while adding more test cases.

**Comment by jopperm** [comment]
I fixed yesterday's problem in 56def02 and did some more polishing, so this should be ready to review now.

**Review by mikeurbach — APPROVED** [review]
A couple minor nits, but this looks good to me at the macro level.

> I decided to implement this very basic and non-generic simplex solver myself to have a default option available in CIRCT that does not require external libraries. I do not plan to expose the simplex solver as a standalone utility to other parts of CIRCT, but will rather look into integrating existing solvers (Google OR tools look promising) as optional library dependencies.

This all makes sense to me. I'm not familiar with the particular paper and algorithm you've implemented, but the implementation is clear to read and from what I know of simplex methods it makes sense.

Thanks for adding this! Having the ability to model and solve this kind of problem in CIRCT is super cool.

**Comment by jopperm** [comment]
Thanks, @mikeurbach!

**Comment by mikeurbach** [comment]
Thank you! I've been taking this for a spin, and it's working well for me.

**Pull request merged**
