### PR TITLE
[Scheduling] Add an algorithm-independent problem test.

### PR DESCRIPTION
**Pull request by jopperm**
This allows testing the `check()`/`verify()` facilities in the `Problem` class by reading a given schedule from the test case.

I think it's important to have tests like this, because it lets us test the problem modeling in case a suitable algorithm is still being implemented, or can only live out-of-tree.

### CODE REVIEW

**Comment by jopperm** [comment]
Caveat: The duplication of test case code, as the MLIR functions from which I construct the scheduling problems are mostly the same in `test_problem.mlir` and `test_asap.mlir`.

I thought about having one file per test problem (`problem_simple.mlir`, `problem_with_latencies.mlir` etc.), with multiple `// RUN`-lines then, but I fear that makes the individual tests harder to understand. Also I don't see a way to `-verify-diagnostics` conditionally.

@mikeurbach @teqdruid Any thoughts on this?

**Comment by teqdruid** [comment]
I haven't had a chance to review, but in general, it's safe to keep `-verify-diagnostics` on regardless of the context since it'll only look for `// expected-error@+` and won't do anything without them. Having multiple `RUN` lines is commonly done, however; it's become our convention to separate out error checks into a separate test file which generally runs with `-split-input-file`, so the "normal" tests don't require that flag.

**Comment by lattner** [comment]
Random request: please put test passes in the lib/ directory along with your dialect passes, rather than in test/. I know that MLIR core does this in some cases, but this slows down build parallelism.

**Comment by jopperm** [comment]
I changed the ASAP scheduler test to emit the computed schedule as attributes (instead of remarks), and check them with `FileCheck`, which made it possible to unify the positive tests into one file. @teqdruid thanks for pointing out the error-test convention, which I adopted here as well.

**Comment by jopperm** [comment]
> @lattner: Random request: please put test passes in the lib/ directory along with your dialect passes, rather than in test/. I know that MLIR core does this in some cases, but this slows down build parallelism.

Will do! (in a new PR, if that's ok)

**Comment by jopperm** [comment]
Merging this without further formal review, on the grounds that this is test code (local to the scheduling infra) which I'll likely have to iterate/adapt in the future anyways.

**Pull request merged**
