### PR TITLE
[PyCDE] Remove unused kwargs parameter from user-defined initializer.

### PR DESCRIPTION
**Pull request by mikeurbach**

### CODE REVIEW

**Comment by mikeurbach** [comment]
@teqdruid not sure if this is what you had in mind, but it seems like we just don't need to pass the kwargs to the user-defined constructor. They're only used within the `__Module` constructor. Or is there some use-case for having the user-defined constructor take arbitrary kwargs?

**Comment by teqdruid** [comment]
They're how the user's constructor get keyword args. Like `Foo(length=4)` wherein `length` is not an input.

There's an argument that the `__Module` constructor should be explicit and take an `input_port_mapping` (or something less verbose) to differentiate it from args to pass through to the user's constructor.

**Comment by mikeurbach** [comment]
Right now the current behavior is a little weird. In the callee like `Foo(...)`, all arguments to the constructor the user wrote are positional arguments, and all `Input`s are keyword arguments, that automagically set the inputs inside the hidden `__Module` constructor. In keeping with that split, I was able to just not pass the keyword arguments to the user-defined constructor, and the tests as currently written pass. This does mean that the user-defined constructor couldn't accept keyword arguments, as it stands in this revision.

If that's not satisfactory, I can split arbitrary constructor arguments from known `Input`s. With a little reworking of the `__Module` constructor, we should be able to tell which kwargs are actual `Input`s and pass the rest to the user-defined constructor.

**Comment by teqdruid** [comment]
If you replace line 74 of polynomial.py with `poly = PolynomialCompute("example", coefficients=[62, 42, 6], x=x)`, does it still work? We don't currently test this case, but it's one I'd like to support.

As for detecting `Input`s, bear in mind that the user's constructor can add `Input`s, so we can't get a list of them until after the constructor is called. (Which makes this a tricky problem.) I was considering using the introspection API. Or switching to a separate parameter for inputs. The latter being the simpler and more explicit option.

**Comment by mikeurbach** [comment]
That would not work, that's what I'm getting at. If that is something we need to support, I won't do what's in this current revision.

It's weird to me that these Inputs can either be class members, or set in the constructor. It's also weird that the Output is set in the constructor rather than being a class member like the Input.

I'll think on this and try to make a more unified, explicit API.

**Comment by teqdruid** [comment]
> It's weird to me that these Inputs can either be class members, or set in the constructor. It's also weird that the Output is set in the constructor rather than being a class member like the Input.

Yeah... Classmembers are for the simple, non-parameterized case. Parameters can (and do) affect the number, type, and name input and output ports so we need to have them settable in the constructor.

Ideally, we'd have a parameterized class so all the inputs and outputs would be classmembers. Haven't figured out how do this neatly in python yet, and I'm not sure it's worth it. But it would be more intuitive, I think.

**Comment by teqdruid** [comment]
> That would not work, that's what I'm getting at. If that is something we need to support, I won't do what's in this current revision.

I had trouble with the Python terminology precision. Yeah, I think this is a scenario we have to support. I asked Aaron today what he thinks about this and he didn't have much of an opinion, so I'm thinking we should go with less magic: `poly = PolynomialCompute("example", coefficients=[62, 42, 6], inputs={ 'x' : x })`

**Comment by mikeurbach** [comment]
@teqdruid please take a look when you get a chance. Now, `inputs` is called out as an explicit keyword argument that takes a dict. Positional and keyword arguments (other than `inputs`) are passed through to the user-defined constructor, so they are free to pass their arguments positionally or as keywords. Updated the test to show that both work.

**Review by teqdruid — APPROVED** [review]
lgtm. Thanks!

**Pull request merged**
