### PR TITLE
[FIRRTL][Dedup] Include port types in ext module hashing

### PR DESCRIPTION
**Pull request by youngar**
When hashing port types, the hasher was ignoring the `portType`
attribute of the operation, and using the block argument instead.  In
other words, it didn't make sense to hash the type twice.

This is a huge problem for `extmodules`, which do not have block
arguments, only a `portTypes` attribute. This changes the hasher
to use the `portTypes` attribute instead of hashing the block argument
types.

### CODE REVIEW

**Review by fabianschuiki — APPROVED** [review]
LGTM!

**Comment by youngar** [comment]
On my end it looks like the CI did not trigger..

**Comment by fabianschuiki** [comment]
Yeah something's off about CI :-(

**Comment by youngar** [comment]
`push --force` to the rescue

**Pull request merged**
