### PR TITLE
[FSMToSV] Add support for FSM variables

### PR DESCRIPTION
**Pull request by mortbopet**
This commit adds support for `fsm.variable` operations in the FSMToSV lowering pass. The meat of this PR is a rewriting of how case muxes are materialized. This procedure is now built around `CaseMuxItem`s which describes a set of state-guarded assignments to a wire. Furthermore, this rewrite allows for nested case muxes (recursive `CaseMuxItem`s).

### CODE REVIEW

**Comment by mortbopet** [comment]
@mikeurbach @teqdruid any comments on this? If not, i'd prefer to go ahead and merge since it IMO refactors things for the better (especially case mux generation).

**Review by mikeurbach — APPROVED** [review]
I think the refactor looks good, and the test case updates/additions make sense.

One minor nitpick: I think in general we have pushed back on adding integration tests like this. I think an integration test that does one small thing has usually been subsumed by larger tests that cover many things at once. In the past, integration tests like that have met feedback like "your unit test already covers this, and you should confirm the behavior out-of-tree rather than on each integration run". Personally, I think it's not taking too much time, but thought I should bring it up.

**Comment by mortbopet** [comment]
Hmm - I definitely understand the concern there. Especially considering that Verilator can take a significant amount of time to spin up + compilation of the model. The only issue here is then that there currently are no users of FSM out of tree, and so it's either going to get tested here, or not get tested at all...!

**Comment by mikeurbach** [comment]
I don't think it really depends on whether it's used somewhere in or out of tree. Once you've confirmed the generated output simulates correctly (locally), and you have a unit test covering the generated output, and you don't need to confirm that verilator still correctly simulates the generated output with an integration test. Anyway, I'm not too concerned about it, just food for thought on the role of unit tests.

**Pull request merged**
