### PR TITLE
[HandshakeToHW] Don't use rewriter infra in HandshakeToHW

### PR DESCRIPTION
**Pull request by mortbopet**
This reverts the "monolithic pattern rewriter" pattern from HandshakeToHW which I've found to be error prone now multiple times (i.e. the HandshakeToHW has a single "top-level" pattern that converts a `handshake.func` to it's HW module, and while doing so, creates a bunch of other modules corresponding to each variation of the Handshake operators). The motivation for this removal has been some local work on elaborating HandshakeToHW, wherein the pattern rewriter (as far as i can tell) tripped up on `BackedgeBuilder` usage when those backedges reside inside a new region created during a rewriter step.

This is close to an NFC since - due to the monolithic, single pattern - the pattern rewriter didn't really provide anything of significance.

### CODE REVIEW

**Comment by Dinistro** [comment]
Wouldn't we ideally want to use the rewrite infrastructure completely? Instead of matching on top-level operation, one could implement patterns for each handshake operation. Keeping state would be more complicated for sure, but such a change will make the pass more in line with what MLIR usually does.

**Comment by mortbopet** [comment]
Based on experience, I have a fair amount of concerns when using the rewrite infrastructure to do top-level operation rewrites. Rewriting top-level operations with to-be-rewritten ops in the inner region (`handshake.func` to `hw.module`):
   - Either you have an intermediate step where the top-level operation is rewritten, and the inner region ops will be in an illegal intermediate state (handshake ops inside a hw.module)
   - Or you perform a match on the top-level operation and do everything inside that pattern rewriter (what HandshakeToHW currently does).

My take on when the pattern rewriter is appropriate:
1. Each operation that you match on can be matched-and-replaced in a peephole manner.
2. Rewriting needs to be performed recursively
3. Rewriting needs to be able to be rolled back

I've seen it be really useful for in-dialect transformations but less so when doing cross-dialect conversions - the biggest issue being rewriting of top-level "container" operations.

**Comment by Dinistro** [comment]
I'm using this approach to lower the streaming dialect to handshake in one go. https://github.com/Dinistro/circt-stream/blob/main/lib/Conversion/StreamToHandshake/StreamToHandshake.cpp

The main pain point is that values might change, thus one has to be careful in connecting the changed inputs to the lowered modules. 
As far as I understand, you can specify on what granularity a rewrite should be applied, so if you let it run on a Module, the patterns will be run sequentially. These patterns can also share state and you are allowed to create new top-level operations.

**Comment by mortbopet** [comment]
Converting to draft just to do a bit more local experimentation on a rewriter-based approach.

**Comment by mikeurbach** [comment]
As a bit of a counterpoint, I actually think the (Conversion)PatternRewriter is pretty good at handling both container ops and bridging type systems. For example, I've done the HW dialect to LLHD dialect conversion using the dialect conversion infrastructure: https://github.com/llvm/circt/blob/main/lib/Conversion/HWToLLHD/HWToLLHD.cpp. This handles containers (hw.module -> llhd.entity), as well as contained ops (hw.instance -> llhd.inst, hw.output -> llhd.drv on entity ports). It also converts from the HW type system (IntegerType and friends) to the LLHD type system (SigType and friends). It is just patterns, no extra state needed. This talk should be required reading; I followed that exactly while writing the above pass: https://drive.google.com/file/d/1VfVajitgf8ZPnd-HRkJvaJiFLhBsluXN/view?usp=sharing

That said, this is just one way to approach it. Dialect conversion is a complex tool with a steep learning curve, but it's one tool in the toolbox. I don't have a strong opinion either way, but if I were writing this conversion from scratch, I'd use it.

**Comment by mortbopet** [comment]
I think my scepticism to it in large part stems from 1. a lack of documentation when it "grew up" and i "learned it", 2. ... a general lack of documentation and 3. a lot of tribal knowledge about when/how rewritings are performed and what types to expect operands to be at what point in time.

Nevertheless, spending some quality time with it, i seemed to get stuff working in #3851, so i will be closing this (rant) issue.

... for now...!

**Pull request closed without merging**
