### PR TITLE
Add LLVM license info to file headers

### PR DESCRIPTION
**Pull request by xgupta**
As stated in [circt/LICENSE](https://github.com/llvm/circt/blob/main/LICENSE), CIRCT is under the Apache License v2.0 with LLVM Exceptions license. But some files didn't contain this license header. so this PR is for that. This should now close issue no. #334 and #66.

### CODE REVIEW

**Comment by xgupta** [comment]
Some files under circt/lib directory did not contain one line file description. I will try to add them based on my understanding and also update the PR soon.

**Review by stephenneuendorffer — APPROVED** [review]
Thanks for this!  It looks like you'll need to run "git clang-format" to fix up some whitespace issues, but feel free to commit this after you've done that.

**Comment by xgupta** [comment]
Sorry, I was not an experienced git user. I am trying to resolve merge conflict with integration_test/Driver.cpp. But other dev commits also included in this PR. Is there any way to remove these 7 commits from this PR or should I close this PR and create a new.

**Comment by xgupta** [comment]
Sorry, I was not an experienced git user. I am trying to resolve merge conflict with integration_test/Driver.cpp. But other dev commits also included in this PR. Is there any way to remove these 7 commits from this PR? or should I close this PR and create a new.

**Comment by xgupta** [comment]
Sorry for the inconvenience. Reopen in #352.

**Pull request closed without merging**
