### PR TITLE
Directly use the cache action with CCACHE_DIR per matrix arm.

### PR DESCRIPTION
**Pull request by mikeurbach**

### CODE REVIEW

**Comment by mikeurbach** [comment]
By directly using the `cache` action, I can not only see the correct cache being loaded, but also a decent cache hit rate from ccache stats.

From scratch build with the current revision: https://github.com/llvm/circt/actions/runs/1142111652 (each job take ~1.5hrs)
Rebuild with the same: https://github.com/llvm/circt/actions/runs/1144062119

In the rebuild, half the jobs (all of the Release jobs) were done in a few minutes, with cach hit rate around 34%. The Debug jobs seemed to suffer from a much lower hit rate. I guess this makes sense, all that debuginfo must be overflowing the 300MB I've allotted for the cache. I picked this number because 16 x 300MB = 4800MB which is below the 5GB limit and means most caches have a shot at being retained between nightly runs. GitHub evicts the least recently used, so the LLVM cache for the PR builds shouldn't ever get evicted.

@teqdruid this doesn't actually solve the "taking >1hr" problem, but I'm not sure what else to do. With a 5GB cap on the cache size, it seems doing 8 different unified builds with Debug is going to be hard to fit into the cache.

**Comment by teqdruid** [comment]
So it's strictly better, but still not great. If you don't get further, we should merge this PR.

One thing I'm noticing is that the debug caches are not that much large than the release caches. They're nowhere near the size limit you specified. If the problem was the cache filling up, I would expect the (pre-compressed) cache size to be very close to the 300 max. I would also expect a higher hit rate 0.37%, but that could easily be due to a poor cache replacement policy.

image

Have you tried removing the max_size constraint? Since many of the builds are full builds anyway, if the ccache tar ends up getting evicted from the github cache, it's no worse than that. I'm not convinced that the issue is the caches filling up since this is not the behavior I would expect. I still suspect that the wrong ccache is being pulled down in the long build cases.

**Review by teqdruid — APPROVED** [review]
I'm approving since this is strictly better than what we're currently doing. Thanks @mikeurbach !

**Comment by teqdruid** [comment]
Is it worth adding `log_file (CCACHE_LOGFILE)` to the ccache config (and uploading it as an artifact) to debug further?

If you're sick of debugging this issue, feel free to just merge. We'll keep the issue around for further investigation when someone has the patience/time to get back to this investigation.

**Comment by mikeurbach** [comment]
> Have you tried removing the max_size constraint? 

I hadn't tried that. Agreed that it's strange the cache hit rate is so horrible for a cache that was under the max size.

> I still suspect that the wrong ccache is being pulled down in the long build cases.

I know, it still seems suspicious. It'd have to be a bug in the `cache` action at this point, because its log messages seem to indicate the cache saved by one build is restored by the next.

For example, this [save](https://github.com/llvm/circt/runs/3358262350?check_suite_focus=true#step:16:6) and [restore](https://github.com/llvm/circt/runs/3363867961?check_suite_focus=true#step:5:13):

```
Cache Size: ~238 MB (249453804 B)
Cache saved successfully
Cache saved with key: clang-Debug-ON-ON-01e1dc27f441da7894d982337d3fac1fff03b876
```

```
Cache Size: ~238 MB (249453804 B)
Cache restored successfully
Cache restored from key: clang-Debug-ON-ON-01e1dc27f441da7894d982337d3fac1fff03b876
```

It's the right key, and the same number of bytes...  but a 0.37% hit rate.

It might be worth adding logging if that can help debug the misses. For now, I am going to merge this as it is at least an improvement over the current situation, which is clearly wrong.

**Pull request merged**
