### PR TITLE
[FIRRTL/IMConstantProp] Add new state "ValidValue"

### LINKED ISSUE #2237: [FIRRTL/IMConstantProp] Reach pessimistic fixpoint if one of operands is an invalid value
Currently, if the lattice value of one of operands is an invalid value and folding fails, we mark the current operation as overdefined immediately. 
It causes to reach some pessimistic fixpoint even though there is a room for constant propagation. For example,
``` mlir
// circt-opt -pass-pipeline='firrtl.circuit(firrtl-imconstprop)'
firrtl.circuit "PessimisticFixpoint"   {
  firrtl.module @PessimisticFixpoint(in %clock: !firrtl.clock, in %a: !firrtl.uint<1>, out %b: !firrtl.uint<2>) {
    %r1 = firrtl.reg %clock  : !firrtl.uint<1>
    %r2 = firrtl.reg %clock  : !firrtl.uint<1>
    %r3 = firrtl.reg %clock  : !firrtl.uint<1>
    %r4 = firrtl.reg %clock  : !firrtl.uint<1>


    %c1_ui1 = firrtl.constant 1 : !firrtl.uint<1>
    firrtl.connect %r1, %c1_ui1 : !firrtl.uint<1>, !firrtl.uint<1>
    firrtl.connect %r3, %c1_ui1 : !firrtl.uint<1>, !firrtl.uint<1>
    firrtl.connect %r2, %r1 : !firrtl.uint<1>, !firrtl.uint<1>
    firrtl.connect %r4, %r3 : !firrtl.uint<1>, !firrtl.uint<1>
    %0 = firrtl.add %r2, %r4 : (!firrtl.uint<1>, !firrtl.uint<1>) -> !firrtl.uint<2>
    firrtl.connect %b, %0 : !firrtl.uint<2>, !firrtl.uint<2>
  }
}
```
currently becomes
``` mlir
firrtl.circuit "PessimisticFixpoint"   {
  firrtl.module @PessimisticFixpoint(in %clock: !firrtl.clock, in %a: !firrtl.uint<1>, out %b: !firrtl.uint<2>) {
      %c1_ui1 = firrtl.constant 1 : !firrtl.uint<1>
      %c1_ui1_0 = firrtl.constant 1 : !firrtl.uint<1>
      %0 = firrtl.add %c1_ui1, %c1_ui1_0 : (!firrtl.uint<1>, !firrtl.uint<1>) -> !firrtl.uint<2>
      firrtl.connect %b, %0 : !firrtl.uint<2>, !firrtl.uint<2>
  }
}
``` 
In this example, we visit `%0 = firrtl.add %r2, %r4` when the lattice of `%4` is invalid value, and therefore `%0` is marked as overdefined.

### PR DESCRIPTION
**Pull request by uenoku**
Currently, when we fail to fold operations, we immediately change their lattice values to be overdefined in the process of fixpoint iterations. The problem here is that we may success to fold after a number of iterations. This commit fix the issue by adding a new lattice value called "ValidValue" into between "InvalidValue" and "Constant".  Generally, it introduces better constant propagation (1%~40% depending on tests). For example  `perf/regress/chipyard.TestHarness.RocketSmall1Medium1Big1_BoomMedium1Large1Mega1.top.v.lo.fir`
```
* num-folded-op - Number of operations folded 
425 -> 574
* num-erased-op - Number of operations erased 
293 -> 434
```

The extension to aggregate types was blocked by this issue so I hope this is a proper fix. Will close #2237.

### CODE REVIEW

**Comment by uenoku** [comment]
> My main question with this is if this can be fixed with, instead, adding a folder involving addition and invalid value. Alternatively, can this be fixed with something like #2251 where canonicalizers interpret invalid as zero?

For the example I added as a test (4 x reg, add), yes. IR is folded into the desirable result. But it seems difference in the larger example (`perf/regress/chipyard.TestHarness.RocketSmall1Medium1Big1_BoomMedium1Large1Mega1.top.v.lo.fir`). Will take a look closer.

**Comment by uenoku** [comment]
Ok, I understand the reason. You are right. The difference comes from missing folders for invalid values. If we can cover all the other operations, we will get the same results. 

> My main question with this is if this can be fixed with, instead, adding a folder involving addition and invalid value. Alternatively, can this be fixed with something like #2251 where canonicalizers interpret invalid as zero?

I think this is correct. It seems we are doing the same thing essentially.

**Comment by lattner** [comment]
I agree with @seldridge that it would be better to fix this in the fold methods if possible, that will be more general throughout the compiler.

**Comment by uenoku** [comment]
Thanks, I’d like to close

**Pull request closed without merging**
